### ISSUE TITLE
check-links check fails on pkg/stanza/docs/operators/generate_input.md

### ISSUE THREAD

**Issue by bertysentry** [open-telemetry/opentelemetry-collector-contrib#10362]
**Describe the bug**
Build consistently fails on **check-links** check:

```
Run markdown-link-check \
node:fs:1551
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, stat 'pkg/stanza/docs/operators/generate_input.md'
    at Object.statSync (node:fs:1551:3)
    at Command.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/markdown-link-check:85:38)
    at Command.listener [as _actionHandler] (/usr/local/lib/node_modules/markdown-link-check/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/usr/local/lib/node_modules/markdown-link-check/node_modules/commander/index.js:1002:14)
    at Command.parse (/usr/local/lib/node_modules/markdown-link-check/node_modules/commander/index.js:801:10)
    at getInputs (/usr/local/lib/node_modules/markdown-link-check/markdown-link-check:9[7](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6609204131?check_suite_focus=true#step:4:8):7)
    at main (/usr/local/lib/node_modules/markdown-link-check/markdown-link-check:215:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/markdown-link-check:22[9](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6609204131?check_suite_focus=true#step:4:10):1)
    at Module._compile (node:internal/modules/cjs/loader:1[10](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6609204131?check_suite_focus=true#step:4:11)5:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:[11](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6609204131?check_suite_focus=true#step:4:12)59:10) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'pkg/stanza/docs/operators/generate_input.md'
}
Error: Process completed with exit code 1.

**Steps to reproduce**
Submit a PR with a change in a Markdown file. The **check-links** check will run and fail.

**What did you expect to see?**
No failure on **check-links** for a file that was not changed in the PR.

**What did you see instead?**
An error message stating that links were broken in `pkg/stanza/docs/operators/generate_input.md`

**What version did you use?**
Current (**main** branch)

**What config did you use?**
Not applicable

**Environment**
GitHub

**Additional context**
N/A
```

**Comment by bertysentry** [comment]
Actually, this has been already fixed. Closing.
