### ISSUE TITLE
kubelet receiver panics with a cryptic message when kubelet API is not reachable

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#1098]
**Describe the bug**
When collector with kubelet receiver is running in an environment where it cannot access kubelet API for some reason it panics with this message:
```
goroutine 199 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver/kubelet.rxBytesMetric(0x30e92b7, 0x8, 0x0, 0xc00d7af050)
	/home/circleci/project/receiver/kubeletstatsreceiver/kubelet/network.go:35 +0x80
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver/kubelet.networkMetrics(0x30e92b7, 0x8, 0x0, 0xc00e434ab0, 0x6, 0x6)
	/home/circleci/project/receiver/kubeletstatsreceiver/kubelet/network.go:25 +0x43
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver/kubelet.(*metricDataAccumulator).podStats(0xc00e3f97b8, 0xc00e45c480, 0xc00dc3db70, 0x10, 0xc00dc3db80, 0xb, 0xc00e0a8420, 0x24, 0x0, 0xed6fc1bc9, ...)
	/home/circleci/project/receiver/kubeletstatsreceiver/kubelet/accumulator.go:90 +0x1e5
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver/kubelet.MetricsData(0xc00d382900, 0xc0002f1ef0, 0xc00e4349c0, 0xc00dd3d110, 0xc00e44b6a0, 0x30f0dcd, 0xc, 0xc00d3908a0, 0x0, 0x0, ...)
	/home/circleci/project/receiver/kubeletstatsreceiver/kubelet/metrics.go:40 +0x43c
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver.(*runnable).Run(0xc0002f0c60, 0xc0005e0750, 0xc0005e0701)
	/home/circleci/project/receiver/kubeletstatsreceiver/runnable.go:94 +0x341
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/redisreceiver/interval.(*Runner).run(0xc00da53de0, 0x0, 0x0)
	/home/circleci/project/receiver/redisreceiver/interval/interval_runner.go:74 +0xba
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/redisreceiver/interval.(*Runner).Start(0xc00da53de0, 0x0, 0x0)
	/home/circleci/project/receiver/redisreceiver/interval/interval_runner.go:54 +0x4c
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver.(*receiver).Start.func1(0xc00da02d00, 0x3760600, 0xc0007b2240)
	/home/circleci/project/receiver/kubeletstatsreceiver/receiver.go:65 +0x2f
created by github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver.(*receiver).Start
	/home/circleci/project/receiver/kubeletstatsreceiver/receiver.go:64 +0x246
```

**Steps to reproduce**
Run otel-collector with kubeletstats receiver on Mac OS with minikube and hyperkit as vm.

**What did you expect to see?**
A warning message that Kubelet API cannot be reached, and kubelet receiver doesn't produce any metrics.

**What did you see instead?**
Collector panics with nil pointer exception.

**What version did you use?**
Version: `01929002a8cb5029a338bda86d06778e3017c672`

**What config did you use?**
Kubeletstats config: 
```
  kubeletstats:
    collection_interval: 10s
    auth_type: serviceAccount
    endpoint: ${K8S_NODE_IP}:10250
    extra_metadata_labels:
      - container.id
```

**Environment**
OS: Minikube on MacOS with hyperkit as vm

**Comment by tigrannajaryan** [comment]
@pmcollins please have a look.

**Comment by pmcollins** [comment]
Will do.

**Comment by tigrannajaryan** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1326
