### ISSUE TITLE
[extension/filestorage] Flaky test - TestClientConcurrentCompaction

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#11039]
Observed here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6886126980?check_suite_focus=true#step:8:1527

```
=== RUN   TestClientConcurrentCompaction
unexpected fault address 0x7fd68d6f5326
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7fd68d6f5326 pc=0x434ed4]
goroutine 179 [running]:
runtime.throw({0xfd9697?, 0xc0000f9c78?})
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/panic.go:992 +0x71 fp=0xc0000f9c30 sp=0xc0000f9c00 pc=0x469df1
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/signal_unix.go:815 +0x125 fp=0xc0000f9c80 sp=0xc0000f9c30 pc=0x4818a5
memeqbody()
	/opt/hostedtoolcache/go/1.18.3/x64/src/internal/bytealg/equal_amd64.s:109 +0xd4 fp=0xc0000f9c88 sp=0xc0000f9c80 pc=0x434ed4
bytes.Equal(...)
	/opt/hostedtoolcache/go/1.18.3/x64/src/bytes/bytes.go:20
github.com/stretchr/testify/assert.ObjectsAreEqual({0xebc9e0, 0xc00000e288}, {0xebc9e0?, 0xc00000e2a0})
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.7.2/assert/assertions.go:75 +0x125 fp=0xc0000f9cf0 sp=0xc0000f9c88 pc=0xe44965
github.com/stretchr/testify/assert.Equal({0x111b180, 0xc000202d00}, {0xebc9e0, 0xc00000e288}, {0xebc9e0, 0xc00000e2a0}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.7.2/assert/assertions.go:343 +0x213 fp=0xc0000f9da8 sp=0xc0000f9cf0 pc=0xe46033
github.com/stretchr/testify/require.Equal({0x111d738, 0xc000202d00}, {0xebc9e0, 0xc00000e288}, {0xebc9e0, 0xc00000e2a0}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.7.2/require/require.go:162 +0xc9 fp=0xc0000f9e00 sp=0xc0000f9da8 pc=0xe498a9
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction.func2(0x0?)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:335 +0x6ea fp=0xc0000f9fb8 sp=0xc0000f9e00 pc=0xe6004a
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction.func3()
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:347 +0x48 fp=0xc0000f9fe0 sp=0xc0000f9fb8 pc=0xe5f928
runtime.goexit()
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000f9fe8 sp=0xc0000f9fe0 pc=0x49ecc1
created by github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:347 +0x5bb
goroutine 1 [chan receive]:
testing.(*T).Run(0xc000202b60, {0xfedecb, 0x1e}, 0x1024958)
	/opt/hostedtoolcache/go/1.18.3/x64/src/testing/testing.go:1487 +0x750
testing.runTests.func1(0x0?)
	/opt/hostedtoolcache/go/1.18.3/x64/src/testing/testing.go:1839 +0x9a
testing.tRunner(0xc000202b60, 0xc00035fba0)
	/opt/hostedtoolcache/go/1.18.3/x64/src/testing/testing.go:1439 +0x214
testing.runTests(0xc0001bee60?, {0x1631340, 0x10, 0x10}, {0x40?, 0x7fd6d172f390?, 0x163eac0?})
	/opt/hostedtoolcache/go/1.18.3/x64/src/testing/testing.go:1837 +0x7e5
testing.(*M).Run(0xc0001bee60)
	/opt/hostedtoolcache/go/1.18.3/x64/src/testing/testing.go:1719 +0xa72
main.main()
	_testmain.go:95 +0x2e5
goroutine 167 [semacquire]:
sync.runtime_Semacquire(0xc0002de988?)
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0xc0002de980)
	/opt/hostedtoolcache/go/1.18.3/x64/src/sync/waitgroup.go:136 +0x9c
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction(0xc000202d00)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:350 +0x66a
testing.tRunner(0xc000202d00, 0x1024958)
	/opt/hostedtoolcache/go/1.18.3/x64/src/testing/testing.go:1439 +0x214
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.18.3/x64/src/testing/testing.go:1486 +0x725
goroutine 159 [semacquire]:
sync.runtime_SemacquireMutex(0x8?, 0x7?, 0xc000160700?)
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc000164638)
	/opt/hostedtoolcache/go/1.18.3/x64/src/sync/mutex.go:162 +0x21d
sync.(*Mutex).Lock(0xc000164638)
	/opt/hostedtoolcache/go/1.18.3/x64/src/sync/mutex.go:81 +0x65
go.etcd.io/bbolt.(*DB).beginRWTx(0xc000164480)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:640 +0x8e
go.etcd.io/bbolt.(*DB).Begin(0xc00003a1bd?, 0x1)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:589 +0x3e
go.etcd.io/bbolt.(*DB).Update(0xc000032058?, 0xc000099d28)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:725 +0x5d
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*fileStorageClient).Batch(0xc000032050, {0xfb8b60?, 0xc0002060d0?}, {0xc000099da8, 0x1, 0x1})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client.go:135 +0x125
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*fileStorageClient).Get(0xfdd58c?, {0x1120d60, 0xc00013e008}, {0xc00003a4f9, 0x7})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client.go:86 +0xc5
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction.func2(0x0?)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:333 +0x61e
created by github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:347 +0x5bb
goroutine 168 [runnable]:
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*fileStorageClient).startCompactionLoop.func1()
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client.go:238 +0x2ee
created by github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*fileStorageClient).startCompactionLoop
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client.go:230 +0x13a
goroutine 160 [semacquire]:
sync.runtime_SemacquireMutex(0x8?, 0x7?, 0xc000[1601](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6886126980?check_suite_focus=true#step:8:1602)c0?)
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc000164638)
	/opt/hostedtoolcache/go/1.18.3/x64/src/sync/mutex.go:162 +0x21d
sync.(*Mutex).Lock(0xc000164638)
	/opt/hostedtoolcache/go/1.18.3/x64/src/sync/mutex.go:81 +0x65
go.etcd.io/bbolt.(*DB).beginRWTx(0xc000164480)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:640 +0x8e
go.etcd.io/bbolt.(*DB).Begin(0xc0002de37d?, 0x1)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:589 +0x3e
go.etcd.io/bbolt.(*DB).Update(0xc000032058?, 0xc000095d28)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:725 +0x5d
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*fileStorageClient).Batch(0xc000032050, {0xfb8b60?, 0xc0001224e0?}, {0xc000095da8, 0x1, 0x1})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client.go:135 +0x125
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*fileStorageClient).Get(0xfdd58c?, {0x1120d60, 0xc00013e008}, {0xc0002de389, 0x7})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client.go:86 +0xc5
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction.func2(0x0?)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:333 +0x61e
created by github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:347 +0x5bb
goroutine 169 [semacquire]:
sync.runtime_SemacquireMutex(0x2?, 0x38?, 0x4a1bf7?)
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc000164638)
	/opt/hostedtoolcache/go/1.18.3/x64/src/sync/mutex.go:162 +0x21d
sync.(*Mutex).Lock(0xc000164638)
	/opt/hostedtoolcache/go/1.18.3/x64/src/sync/mutex.go:81 +0x65
go.etcd.io/bbolt.(*DB).beginRWTx(0xc000164480)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:640 +0x8e
go.etcd.io/bbolt.(*DB).Begin(0xc0002aa17f?, 0x1)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:589 +0x3e
go.etcd.io/bbolt.(*DB).Update(0xc000032058?, 0xc0000dbdd0)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:725 +0x5d
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*fileStorageClient).Batch(0xc000032050, {0x9?, 0xc0000dbef8?}, {0xc0000dbec0, 0x1, 0x1})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client.go:135 +0x125
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction.func2(0x0?)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:323 +0x425
created by github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:347 +0x5bb
goroutine 161 [runnable]:
sync.runtime_Semrelease(0xc000164638?, 0xff?, 0x44?)
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/sema.go:66 +0x19
sync.(*Mutex).unlockSlow(0xc000164638, 0x44)
	/opt/hostedtoolcache/go/1.18.3/x64/src/sync/mutex.go:248 +0x74
sync.(*Mutex).Unlock(0xc000164638)
	/opt/hostedtoolcache/go/1.18.3/x64/src/sync/mutex.go:214 +0x55
go.etcd.io/bbolt.(*Tx).close(0xc000[1603](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6886126980?check_suite_focus=true#step:8:1604)80)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:302 +0x4b0
go.etcd.io/bbolt.(*Tx).Commit(0xc000160380)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:214 +0x778
go.etcd.io/bbolt.(*DB).Update(0xc000032058?, 0xc0000f5dd0)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:748 +0x153
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*fileStorageClient).Batch(0xc000032050, {0x9?, 0xc000131ef8?}, {0xc000131ec0, 0x1, 0x1})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client.go:135 +0x125
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction.func2(0x0?)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:323 +0x425
created by github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:347 +0x5bb
goroutine 170 [semacquire]:
sync.runtime_SemacquireMutex(0x2?, 0x38?, 0x4a1bf7?)
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc000164638)
	/opt/hostedtoolcache/go/1.18.3/x64/src/sync/mutex.go:162 +0x21d
sync.(*Mutex).Lock(0xc000164638)
	/opt/hostedtoolcache/go/1.18.3/x64/src/sync/mutex.go:81 +0x65
go.etcd.io/bbolt.(*DB).beginRWTx(0xc000164480)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:640 +0x8e
go.etcd.io/bbolt.(*DB).Begin(0x43a3cd?, 0x1)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:589 +0x3e
go.etcd.io/bbolt.(*DB).Update(0xc000032058?, 0xc00012bdd0)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:725 +0x5d
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*fileStorageClient).Batch(0xc000032050, {0x9?, 0xc00012bef8?}, {0xc00012bec0, 0x1, 0x1})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client.go:135 +0x125
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction.func2(0x0?)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:323 +0x425
created by github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:347 +0x5bb
goroutine 171 [runnable]:
go.etcd.io/bbolt.(*freelist).addSpan(...)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/freelist_hmap.go:129
go.etcd.io/bbolt.(*freelist).mergeWithExistingSpan(0xc0000fcf00, 0x71e)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/freelist_hmap.go:122 +0x52c
go.etcd.io/bbolt.(*freelist).hashmapMergeSpans(0x445b80?, {0xc0001af800, 0x2df, 0xc00027c0c0?})
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/freelist_hmap.go:93 +0x5f
go.etcd.io/bbolt.(*freelist).release(0xc0000fcf00, 0xfffffffffffffffe)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/freelist.go:195 +0x2a8
go.etcd.io/bbolt.(*DB).freePages(0xc000164480)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:670 +0x14e
go.etcd.io/bbolt.(*DB).beginRWTx(0xc000164480)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:657 +0x1f9
go.etcd.io/bbolt.(*DB).Begin(0xc0002b65ff?, 0x1)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:589 +0x3e
go.etcd.io/bbolt.(*DB).Update(0xc000032058?, 0xc00009bdd0)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:725 +0x5d
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*fileStorageClient).Batch(0xc000032050, {0x9?, 0xc00009bef8?}, {0xc00009bec0, 0x1, 0x1})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client.go:135 +0x125
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction.func2(0x0?)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:323 +0x425
created by github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:347 +0x5bb
goroutine 178 [semacquire]:
sync.runtime_SemacquireMutex(0x8?, 0x7?, 0xc0001716c0?)
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc000164638)
	/opt/hostedtoolcache/go/1.18.3/x64/src/sync/mutex.go:162 +0x21d
sync.(*Mutex).Lock(0xc000164638)
	/opt/hostedtoolcache/go/1.18.3/x64/src/sync/mutex.go:81 +0x65
go.etcd.io/bbolt.(*DB).beginRWTx(0xc000164480)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:640 +0x8e
go.etcd.io/bbolt.(*DB).Begin(0xc00003a1bd?, 0x1)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:589 +0x3e
go.etcd.io/bbolt.(*DB).Update(0xc000032058?, 0xc0000f7d28)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:725 +0x5d
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*fileStorageClient).Batch(0xc000032050, {0xfb8b60?, 0xc0002060d0?}, {0xc0000f7da8, 0x1, 0x1})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client.go:135 +0x125
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*fileStorageClient).Get(0xfdd58c?, {0x1120d60, 0xc00013e008}, {0xc00003a369, 0x7})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client.go:86 +0xc5
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction.func2(0x0?)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:333 +0x61e
created by github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:347 +0x5bb
goroutine 180 [semacquire]:
sync.runtime_SemacquireMutex(0x8?, 0x7?, 0x0?)
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc000164638)
	/opt/hostedtoolcache/go/1.18.3/x64/src/sync/mutex.go:162 +0x21d
sync.(*Mutex).Lock(0xc000164638)
	/opt/hostedtoolcache/go/1.18.3/x64/src/sync/mutex.go:81 +0x65
go.etcd.io/bbolt.(*DB).beginRWTx(0xc000164480)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:640 +0x8e
go.etcd.io/bbolt.(*DB).Begin(0xc0002de05d?, 0x1)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:589 +0x3e
go.etcd.io/bbolt.(*DB).Update(0xc000032058?, 0xc000097d28)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:725 +0x5d
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*fileStorageClient).Batch(0xc000032050, {0xfb8b60?, 0xc0001220d0?}, {0xc000097da8, 0x1, 0x1})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client.go:135 +0x125
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*fileStorageClient).Get(0xfdd58c?, {0x1120d60, 0xc00013e008}, {0xc0002de069, 0x7})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client.go:86 +0xc5
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction.func2(0x0?)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:333 +0x61e
created by github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:347 +0x5bb
goroutine 181 [semacquire]:
sync.runtime_SemacquireMutex(0x2?, 0x38?, 0x4a1bf7?)
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc000164638)
	/opt/hostedtoolcache/go/1.18.3/x64/src/sync/mutex.go:162 +0x21d
sync.(*Mutex).Lock(0xc000164638)
	/opt/hostedtoolcache/go/1.18.3/x64/src/sync/mutex.go:81 +0x65
go.etcd.io/bbolt.(*DB).beginRWTx(0xc000164480)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:640 +0x8e
go.etcd.io/bbolt.(*DB).Begin(0xc0002b65ff?, 0x1)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:589 +0x3e
go.etcd.io/bbolt.(*DB).Update(0xc000032058?, 0xc00012ddd0)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:725 +0x5d
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*fileStorageClient).Batch(0xc000032050, {0x9?, 0xc00012def8?}, {0xc00012dec0, 0x1, 0x1})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client.go:135 +0x125
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction.func2(0x0?)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:323 +0x425
created by github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.TestClientConcurrentCompaction
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/storage/filestorage/client_test.go:347 +0x5bb
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage	2.234s
```

**Comment by djaglowski** [comment]
cc @pmm-sumo
