### ISSUE TITLE
CodeQL action is frequently failing on main branch 

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#12607]
```
  Error: 7-19 20:44:00] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/opt/hostedtoolcache/CodeQL/0.0.0-20220623/x64/codeql/tools/linux64/preload_tracer, /opt/hostedtoolcache/CodeQL/0.0.0-20220623/x64/codeql/go/tools/autobuild.sh])
  A fatal error occurred: Exit status 1 from command: [/opt/hostedtoolcache/CodeQL/0.0.0-20220623/x64/codeql/go/tools/autobuild.sh]
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220623/x64/codeql/codeql' failed with exit code 2
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220623/x64/codeql/codeql' failed with exit code 2
      at toolrunnerErrorCatcher (/home/runner/work/_actions/github/codeql-action/v2/lib/toolrunner-error-catcher.js:86:19)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.extractScannedLanguage (/home/runner/work/_actions/github/codeql-action/v2/lib/codeql.js:548:13)
      at async createdDBForScannedLanguages (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze.js:82:13)
      at async finalizeDatabaseCreation (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze.js:101:5)
      at async runFinalize (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze.js:249:5)
      at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze-action.js:83:9)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze-action.js:221:9)
```

**Comment by dmitryax** [comment]
It seems like a timeout issue but not 100% sure

**Comment by dmitryax** [comment]
Increasing github actions timeout didn't help

**Comment by jpkrohling** [comment]
This actually looks like a problem with GHA's infra. This happens from time to time and is typically fixed within a couple of hours. It's awful that it's happening on our release day, though :-/

**Comment by dmitryax** [comment]
I also think that the process is might be killed due to excessive CPU/memory utilization. Maybe we should play with CodeQL config and tune it

**Comment by djaglowski** [comment]
I've been looking into this a bit more, and noticed this near the beginning of the failed step:
```
  [2022-08-02 13:29:33] [build-stderr] 2022/08/02 13:29:33 Makefile found.
  [2022-08-02 13:29:33] [build-stderr] 2022/08/02 13:29:33 Trying build command make []
  [2022-08-02 13:29:41] [build-stdout] make[1]: Entering directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib'
  [2022-08-02 13:29:44] [build-stdout] Running target 'common' in module 'receiver/activedirectorydsreceiver' as part of group 'all'
  [2022-08-02 13:29:44] [build-stdout] make -C receiver/activedirectorydsreceiver common
  [2022-08-02 13:29:44] [build-stdout] make[2]: Entering directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/activedirectorydsreceiver'
  [2022-08-02 13:29:44] [build-stderr] go: downloading google.golang.org/genproto v0.0.0-20211208223120-3a66f561d7aa
  [2022-08-02 13:29:44] [build-stderr] go: downloading golang.org/x/net v0.0.0-20220225172249-27dd8689420f
  [2022-08-02 13:29:45] [build-stderr] go: downloading golang.org/x/sys v0.0.0-20220520151302-bc2c85ada10a
  [2022-08-02 13:29:46] [build-stdout] addlicense FAILED => add License errors:
  [2022-08-02 13:29:46] [build-stdout] /bin/sh: 1: addlicense: not found
  [2022-08-02 13:29:46] [build-stdout] Use 'make addlicense' to fix this.
  [2022-08-02 13:29:46] [build-stderr] make[2]: *** [../../Makefile.Common:89: checklicense] Error 1
  [2022-08-02 13:29:46] [build-stderr] make[1]: *** [Makefile:184: receiver/activedirectorydsreceiver] Error 2
  [2022-08-02 13:29:46] [build-stdout] make[2]: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/activedirectorydsreceiver'
  [2022-08-02 13:29:46] [build-stdout] make[1]: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib'
  [2022-08-02 13:29:46] [build-stderr] make: *** [Makefile:63: all-common] Error 2
  [2022-08-02 13:29:46] [build-stderr] 2022/08/02 13:29:46 Running /usr/bin/make failed, continuing anyway: exit status 2
  [2022-08-02 13:29:46] [build-stderr] 2022/08/02 13:29:46 Build failed, continuing to install dependencies.
  [2022-08-02 13:29:46] [build-stderr] 2022/08/02 13:29:46 Installing dependencies using `go get -v ./...`.
```

From there, it downloads and extracts many packages, and abruptly fails for what may just be a timeout:

```
  [2022-08-02 13:57:35] [build-stderr] 2022/08/02 13:57:35 Extraction failed: signal: killed
  Error: 8-02 13:57:35] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/opt/hostedtoolcache/CodeQL/0.0.0-20220623/x64/codeql/tools/linux64/preload_tracer, /opt/hostedtoolcache/CodeQL/0.0.0-20220623/x64/codeql/go/tools/autobuild.sh])
  A fatal error occurred: Exit status 1 from command: [/opt/hostedtoolcache/CodeQL/0.0.0-20220623/x64/codeql/go/tools/autobuild.sh]
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220623/x64/codeql/codeql' failed with exit code 2
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220623/x64/codeql/codeql' failed with exit code 2
      at toolrunnerErrorCatcher (/home/runner/work/_actions/github/codeql-action/v2/lib/toolrunner-error-catcher.js:86:19)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.extractScannedLanguage (/home/runner/work/_actions/github/codeql-action/v2/lib/codeql.js:561:13)
      at async createdDBForScannedLanguages (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze.js:82:13)
      at async finalizeDatabaseCreation (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze.js:101:5)
      at async runFinalize (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze.js:249:5)
      at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze-action.js:83:9)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze-action.js:221:9)
```

Based on the first bit, `Trying build command make`, and the error, `/bin/sh: 1: addlicense: not found`, I've noticed that the default make target should require `install-tools`. I'll try adding this and see if this allows it to build successfully.

**Comment by djaglowski** [comment]
After merging #12891, the error I had noticed is resolved. However, the action still times out due to the default make target being extremely long. 

I've looked into this some more and believe I've pinned down the problem in #12968. Successful run here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7678886296?check_suite_focus=true#step:6:339
