### ISSUE TITLE
SIGSEGV when using Prometheus receiver without scrape_configs

### ISSUE THREAD

**Issue by KevinSnyderCodes** [open-telemetry/opentelemetry-collector-contrib#13424]
**Describe the bug**
SIGSEGV when using Prometheus receiver without `scrape_configs`.

**Steps to reproduce**
Enable the Prometheus receiver with minimal configuration (see below).

**What did you expect to see?**
"Error: field `scrape_configs` is required" or some other more graceful handling.

**What did you see instead?**
OpenTelemetry collector crashes with the following output:

```
2022-08-18T18:25:34.318Z	info	pipelines/pipelines.go:102	Receiver is starting...	{"kind": "receiver", "name": "prometheus", "pipeline": "metrics"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x3b2d5be]

goroutine 1 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver.(*pReceiver).Start(0xc000596b40, {0x58bfc24?, 0xc00007e018?}, {0x6334298?, 0xc000c8cf18})
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver@v0.56.0/metrics_receiver.go:66 +0x13e
go.opentelemetry.io/collector/service/internal/pipelines.(*Pipelines).StartAll(0xc000e07220, {0x632ec68, 0xc00007e018}, {0x6334260?, 0xc0003b3420})
	go.opentelemetry.io/collector@v0.56.0/service/internal/pipelines/pipelines.go:103 +0x452
go.opentelemetry.io/collector/service.(*service).Start(0xc000080800, {0x632ec68, 0xc00007e018})
	go.opentelemetry.io/collector@v0.56.0/service/service.go:116 +0xa6
go.opentelemetry.io/collector/service.(*Collector).setupConfigurationComponents(0xc001499ae8, {0x632ec68, 0xc00007e018})
	go.opentelemetry.io/collector@v0.56.0/service/collector.go:200 +0x1e9
go.opentelemetry.io/collector/service.(*Collector).Run(0xc001499ae8, {0x632ec68, 0xc00007e018})
	go.opentelemetry.io/collector@v0.56.0/service/collector.go:210 +0x45
go.opentelemetry.io/collector/service.NewCommand.func1(0xc000395180, {0x586beb1?, 0x1?, 0x1?})
	go.opentelemetry.io/collector@v0.56.0/service/command.go:50 +0x499
github.com/spf13/cobra.(*Command).execute(0xc000395180, {0xc00006e050, 0x1, 0x1})
	github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000395180)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
main.runInteractive({{0xc00014b260, 0xc000154e70, 0xc00014be90, 0xc00014a360}, {{0x588e298, 0xf}, {0x58fbdd9, 0x1f}, {0x5866273, 0x6}}, ...})
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main.go:32 +0x5d
main.run(...)
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main_others.go:11
main.main()
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main.go:25 +0x1d8
```

**What version did you use?**
Version: `v0.58.0`
Docker image: `otel/opentelemetry-collector-contrib:0.58.0`

**What config did you use?**
```yaml
receivers:
  prometheus:
    config:
```

**Environment**
Kubernetes, using OpenTelemetry operator.

**Additional context**
N/A

**Comment by Aneurysm9** [comment]
The configuration validation system has changed significantly since `v0.56.0`.  If this issue is reproducible with a current release please open a new issue with details on reproduction.
