### ISSUE TITLE
Transformprocessor: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by JensLederer** [open-telemetry/opentelemetry-collector-contrib#14140]
### What happened?

```Markdown
## Description
I'm trying to add a new resource attribute to a metric using the Transform Processor. This fails with an segmentation fault.

## Steps to Reproduce

## Expected Result
A new resource attribute 'azname' is added, containing the string value 'env1-mongodb'

## Actual Result
Collector crashes with segmentation fault.
```

### Collector version

0.59

### Environment information

```Markdown
## Environment
OS: Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-1019-azure x86_64)
```

### OpenTelemetry Collector configuration

```yaml
extensions:
  health_check:
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']
  mongodbatlas:
    collection_interval: 10s
    public_key: "XXXXXXXX"
    private_key: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
processors:
  batch:
  resource/mongodbatlas:
    attributes:
    - key: mongodb_atlas.project.name
      pattern: IoT\s-\sLayer(?P<azlayer_id>\d)
      action: extract
  filter/mongodb_atlas:
    metrics:
      include:
        match_type: regexp
        resource_attributes:
          - Key: mongodb_atlas.project.name
            Value: IoT\s-\sLayer(?P<azname>1)
        metric_names:
          - mongodbatlas\.process\.memory\.usage
  transform/mongodb_atlas:
    metrics:
      queries:
        - set(resource.attributes["azname"], "env1-mongodb") 
exporters:
  logging:
    logLevel: debug
service:
  pipelines:
    metrics:
      receivers: [mongodbatlas]
      processors: [filter/mongodb_atlas, resource/mongodbatlas, transform/mongodb_atlas, batch]
      exporters: [logging]
  extensions: [health_check]
```

### Log output

```shell
2022-09-15T13:56:49.556Z	info	service/service.go:129	Everything is ready. Begin running and processing data.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2ccf119]

goroutine 92 [running]:
go.opentelemetry.io/collector/pdata/pmetric.Sum.DataPoints(...)
	go.opentelemetry.io/collector/pdata@v0.59.0/pmetric/generated_metrics.go:843
github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor/internal/metrics.(*Processor).ProcessMetrics(0x40dce7?, {0x10?, 0x51ca1a0?}, {0xc000b48f01?})
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor@v0.59.0/internal/metrics/processor.go:57 +0x259
go.opentelemetry.io/collector/processor/processorhelper.NewMetricsProcessor.func1({0x6e97b88, 0xc001723c80}, {0x0?})
	go.opentelemetry.io/collector@v0.59.0/processor/processorhelper/metrics.go:75 +0xf8
go.opentelemetry.io/collector/consumer.ConsumeMetricsFunc.ConsumeMetrics(...)
	go.opentelemetry.io/collector@v0.59.0/consumer/metrics.go:36
go.opentelemetry.io/collector/processor/processorhelper.NewMetricsProcessor.func1({0x6e97b88, 0xc001723c80}, {0x0?})
	go.opentelemetry.io/collector@v0.59.0/processor/processorhelper/metrics.go:83 +0x1dd
go.opentelemetry.io/collector/consumer.ConsumeMetricsFunc.ConsumeMetrics(...)
	go.opentelemetry.io/collector@v0.59.0/consumer/metrics.go:36
go.opentelemetry.io/collector/processor/processorhelper.NewMetricsProcessor.func1({0x6e97b88, 0xc001723c80}, {0x0?})
	go.opentelemetry.io/collector@v0.59.0/processor/processorhelper/metrics.go:83 +0x1dd
go.opentelemetry.io/collector/consumer.ConsumeMetricsFunc.ConsumeMetrics(...)
	go.opentelemetry.io/collector@v0.59.0/consumer/metrics.go:36
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport(0xc00087ca80, {0x6e97b18, 0xc0000720c0})
	go.opentelemetry.io/collector@v0.59.0/receiver/scraperhelper/scrapercontroller.go:209 +0x12c
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1()
	go.opentelemetry.io/collector@v0.59.0/receiver/scraperhelper/scrapercontroller.go:172 +0xc7
created by go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping
	go.opentelemetry.io/collector@v0.59.0/receiver/scraperhelper/scrapercontroller.go:161 +0x56
```

### Additional context

```Markdown
Partial metric output, when I remove the Transform Processor from pipeline:

Metric #0
Descriptor:
     -> Name: mongodbatlas.process.memory.usage
     -> Description: Memory Usage
     -> Unit: By
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> memory_state: STRING(resident)
StartTimestamp: 2022-09-15 13:41:13.111619142 +0000 UTC
Timestamp: 2022-09-15 13:51:10 +0000 UTC
Value: 712.000000
NumberDataPoints #1
Data point attributes:
     -> memory_state: STRING(virtual)
StartTimestamp: 2022-09-15 13:41:13.111619142 +0000 UTC
Timestamp: 2022-09-15 13:51:10 +0000 UTC
Value: 3579.000000
ResourceMetrics #2
Resource SchemaURL: 
Resource attributes:
     -> mongodb_atlas.org_name: STRING(ACME)
     -> mongodb_atlas.project.name: STRING(IoT - Layer1)
     -> mongodb_atlas.project.id: STRING(xxxxxxxxxxxxxxxxxxxxxxxx)
     -> mongodb_atlas.host.name: STRING(atlas-xxxxxx-shard-xx-xx.xxxxx.mongodb.net)
     -> mongodb_atlas.process.port: STRING(27017)
     -> mongodb_atlas.process.type_name: STRING(REPLICA_SECONDARY)
     -> mongodb_atlas.process.id: STRING(atlas-xxxxxx-shard-xx-xx.xxxxx.mongodb.net:27017)
     -> mongodb_atlas.db.name: STRING(acme_db)
     -> azlayer_id: STRING(1)
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope otelcol/mongoatlasreceiver 0.59.0
Metric #0
Descriptor:
     -> Name: mongodbatlas.process.memory.usage
     -> Description: Memory Usage
     -> Unit: By
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> memory_state: STRING(resident)
StartTimestamp: 2022-09-15 13:41:13.111619142 +0000 UTC
Timestamp: 2022-09-15 13:51:00 +0000 UTC
Value: 703.000000
NumberDataPoints #1
Data point attributes:
     -> memory_state: STRING(virtual)
StartTimestamp: 2022-09-15 13:41:13.111619142 +0000 UTC
Timestamp: 2022-09-15 13:51:00 +0000 UTC
Value: 3002.000000
	{"kind": "exporter", "data_type": "metrics", "name": "logging"}
```

**Comment by JensLederer** [comment]
With release 0.60 the issue is gone
