### ISSUE TITLE
TestRemovedContainerRemovesRecordsIntegration intermittent failure

### ISSUE THREAD

**Issue by jchengsfx** [open-telemetry/opentelemetry-collector-contrib#1509]
**Describe the bug**
Circleci integration test failure: https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/5999/workflows/d8f8c3da-6f2e-4d50-a935-290f57421cbc/jobs/47073/steps

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
v0.14.0

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
Circleci

**Additional context**
```
WARNING: DATA RACE
Read at 0x00c0000cc5e3 by goroutine 12:
  testing.(*common).logDepth()
      /usr/local/go/src/testing/testing.go:675 +0x14b
  testing.(*common).log()
      /usr/local/go/src/testing/testing.go:662 +0x8f
  testing.(*common).Logf()
      /usr/local/go/src/testing/testing.go:701 +0x21
  testing.(*T).Logf()
      <autogenerated>:1 +0x75
  go.uber.org/zap/zaptest.testingWriter.Write()
      /home/circleci/go/pkg/mod/go.uber.org/zap@v1.16.0/zaptest/logger.go:130 +0x11f
  go.uber.org/zap/zaptest.(*testingWriter).Write()
      <autogenerated>:1 +0xa9
  go.uber.org/zap/zapcore.(*ioCore).Write()
      /home/circleci/go/pkg/mod/go.uber.org/zap@v1.16.0/zapcore/core.go:90 +0x1c3
  go.uber.org/zap/zapcore.(*CheckedEntry).Write()
      /home/circleci/go/pkg/mod/go.uber.org/zap@v1.16.0/zapcore/entry.go:220 +0x1e7
  go.uber.org/zap.(*Logger).Debug()
      /home/circleci/go/pkg/mod/go.uber.org/zap@v1.16.0/logger.go:180 +0x95
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver.(*dockerClient).removeContainer()
      /home/circleci/project/receiver/dockerstatsreceiver/docker.go:306 +0x297
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver.(*dockerClient).ContainerEventLoop()
      /home/circleci/project/receiver/dockerstatsreceiver/docker.go:226 +0x123d

Previous write at 0x00c0000cc5e3 by main goroutine:
  testing.tRunner.func1()
      /usr/local/go/src/testing/testing.go:977 +0x467
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:995 +0x20d
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1282 +0x527
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1199 +0x2ff
  main.main()
      _testmain.go:154 +0x337

Goroutine 12 (running) created at:
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver.(*Receiver).Setup()
      /home/circleci/project/receiver/dockerstatsreceiver/receiver.go:108 +0x173
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/redisreceiver/interval.(*Runner).setup()
      /home/circleci/project/receiver/redisreceiver/interval/interval_runner.go:63 +0x90
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/redisreceiver/interval.(*Runner).Start()
      /home/circleci/project/receiver/redisreceiver/interval/interval_runner.go:50 +0x3c
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver.(*Receiver).Start.func1()
      /home/circleci/project/receiver/dockerstatsreceiver/receiver.go:88 +0x6c
==================
panic: Log in goroutine after TestRemovedContainerRemovesRecordsIntegration has completed

goroutine 155 [running]:
testing.(*common).logDepth(0xc0006b1440, 0xc000063550, 0xaa, 0x3)
	/usr/local/go/src/testing/testing.go:680 +0x67c
testing.(*common).log(...)
	/usr/local/go/src/testing/testing.go:662
testing.(*common).Logf(0xc0006b1440, 0x3991647, 0x2, 0xc00078b960, 0x1, 0x1)
	/usr/local/go/src/testing/testing.go:701 +0x90
go.uber.org/zap/zaptest.testingWriter.Write(0x4063760, 0xc0006b1440, 0x3991500, 0xc000687c00, 0xab, 0x400, 0xbfe17a762af040c6, 0xc00078b950, 0xc0007a4d80)
	/home/circleci/go/pkg/mod/go.uber.org/zap@v1.16.0/zaptest/logger.go:130 +0x120
go.uber.org/zap/zapcore.(*ioCore).Write(0xc0006fcea0, 0xff, 0xbfe17a762af040c6, 0x60a9630c3, 0x5745f60, 0x0, 0x0, 0x39c696d, 0x1e, 0x1, ...)
	/home/circleci/go/pkg/mod/go.uber.org/zap@v1.16.0/zapcore/core.go:90 +0x1c4
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000d6540, 0xc0007a4dc0, 0x1, 0x1)
	/home/circleci/go/pkg/mod/go.uber.org/zap@v1.16.0/zapcore/entry.go:220 +0x1e8
go.uber.org/zap.(*Logger).Debug(0xc0006e2a80, 0x39c696d, 0x1e, 0xc0007a4dc0, 0x1, 0x1)
	/home/circleci/go/pkg/mod/go.uber.org/zap@v1.16.0/logger.go:180 +0x96
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver.(*dockerClient).removeContainer(0xc0006fcff0, 0xc0005baf80, 0x40)
	/home/circleci/project/receiver/dockerstatsreceiver/docker.go:306 +0x298
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver.(*dockerClient).ContainerEventLoop(0xc0006fcff0, 0x4048020, 0xc0007a4240)
	/home/circleci/project/receiver/dockerstatsreceiver/docker.go:226 +0x123e
created by github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver.(*Receiver).Setup
	/home/circleci/project/receiver/dockerstatsreceiver/receiver.go:108 +0x174
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver	25.964s
FAIL
```

**Comment by jpkrohling** [comment]
cc codeowner (@rmfitzpatrick)
