### ISSUE TITLE
[exporter/loki] Flaky test TestFactory_CreateLogsExporter

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#15365]
See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3294062311/jobs/5431429685

```
=== RUN   TestFactory_CreateLogsExporter
fatal error: checkptr: converted pointer straddles multiple allocations

goroutine 156 [running]:
runtime.throw({0x16e821b?, 0xf1001?})
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/runtime/panic.go:1047 +0x65 fp=0xc000559168 sp=0xc000559138 pc=0x47bce5
runtime.checkptrAlignment(0x30000?, 0x10?, 0x0?)
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/runtime/checkptr.go:26 +0x6c fp=0xc000559188 sp=0xc000559168 pc=0x444fac
syscall.Environ()
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/syscall/env_windows.go:77 +0xcd fp=0xc000559290 sp=0xc000559188 pc=0x4c6c2d
internal/syscall/execenv.Default(0x0)
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/internal/syscall/execenv/execenv_windows.go:26 +0x91 fp=0xc0005593b8 sp=0xc000559290 pc=0x52eff1
os/exec.(*Cmd).environ(0xc00018a160)
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/os/exec/exec.go:886 +0x76 fp=0xc000559428 sp=0xc0005593b8 pc=0x64a3b6
os/exec.(*Cmd).Start(0xc00018a160)
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/os/exec/exec.go:519 +0xa2d fp=0xc000559718 sp=0xc000559428 pc=0x64892d
os/exec.(*Cmd).Run(0x0?)
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/os/exec/exec.go:434 +0x31 fp=0xc000559758 sp=0xc000559718 pc=0x647af1
os/exec.(*Cmd).CombinedOutput(0xc00018a160)
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/os/exec/exec.go:707 +0x20a fp=0xc0005597d0 sp=0xc000559758 pc=0x64a26a
github.com/open-telemetry/opentelemetry-collector-contrib/internal/common/testutil.getExclusionsList({0x19122a8?, 0xc000184820})
	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/common/testutil/testutil.go:107 +0x11e fp=0xc0005598e0 sp=0xc0005597d0 pc=0x145d97e
github.com/open-telemetry/opentelemetry-collector-contrib/internal/common/testutil.GetAvailableLocalNetworkAddress({0x19122a8?, 0xc000184820}, {0x16a7b44, 0x3})
	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/common/testutil/testutil.go:56 +0x70 fp=0xc000559988 sp=0xc0005598e0 pc=0x145cf90
github.com/open-telemetry/opentelemetry-collector-contrib/internal/common/testutil.GetAvailableLocalAddress(...)
	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/common/testutil/testutil.go:39
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/lokiexporter.TestFactory_CreateLogsExporter(0x0?)
	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/lokiexporter/legacy_factory_test.go:63 +0x58 fp=0xc000559ea8 sp=0xc000559988 pc=0x147c078
testing.tRunner(0xc000184820, 0x1714d20)
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/testing/testing.go:1446 +0x217 fp=0xc000559fb0 sp=0xc000559ea8 pc=0x5e5617
testing.(*T).Run.func1()
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/testing/testing.go:1493 +0x48 fp=0xc000559fe0 sp=0xc000559fb0 pc=0x5e6e48
runtime.goexit()
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000559fe8 sp=0xc000559fe0 pc=0x4aff81
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/testing/testing.go:1493 +0x75e

...
```

**Comment by djaglowski** [comment]
Here again: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3314484447/jobs/5476073169#step:8:3353

**Comment by djaglowski** [comment]
And here: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3314484447/jobs/5476073169

**Comment by dmitryax** [comment]
Test is skipped so the issue is not resolved yet

**Comment by dmitryax** [comment]
Sure, it's in the issue description https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3294062311/jobs/5431429685

**Comment by jpkrohling** [comment]
@kovrus, are you handling this one?
