### ISSUE TITLE
exporter/honeycomb: Collector crashes if Node.ServiceInfo not set on TraceData.

### ISSUE THREAD

**Issue by paulosman** [open-telemetry/opentelemetry-collector-contrib#156]
Zipkin and Jaeger clients support sending trace data without populating `Node.ServiceInfo` on `TraceData` instances. This will currently cause the collector to crash if the honeycomb exporter is configured as part of a pipeline exporting those traces. We should check that the field is not nil before trying to set it as an attribute.

**Comment by seh** [comment]
[A copy of the panic and stack trace](https://honeycombpollinators.slack.com/archives/CNQ943Q75/p1585430836019800?thread_ts=1585342471.007700&cid=CNQ943Q75) is available in the "discuss-opentelemetry-beta" channel of the "Honeycomb Pollinators" Slack team, reproduced here:
<details>
   <summary>Go panic</summary>

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1e5f472]

goroutine 110 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/honeycombexporter.(*HoneycombExporter).pushTraceData(0xc000406468, 0x2c0fc60, 0xc0002c7920, 0x0, 0x0, 0xc0002c75f0, 0x6, 0x6, 0x27620e3, 0x6, ...)
	/home/circleci/project/exporter/honeycombexporter/honeycomb.go:63 +0x182
github.com/open-telemetry/opentelemetry-collector/exporter/exporterhelper.traceDataPusher.withObservability.func1(0x2c0fc60, 0xc0002c7920, 0x0, 0x0, 0xc0002c75f0, 0x6, 0x6, 0x27620e3, 0x6, 0x5e7fc033, ...)
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector@v0.2.8/exporter/exporterhelper/tracehelper.go:98 +0xc9
github.com/open-telemetry/opentelemetry-collector/exporter/exporterhelper.(*traceExporter).ConsumeTraceData(0xc0001a3f60, 0x2c0fc60, 0xc0002c76e0, 0x0, 0x0, 0xc0002c75f0, 0x6, 0x6, 0x27620e3, 0x6, ...)
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector@v0.2.8/exporter/exporterhelper/tracehelper.go:48 +0xa7
github.com/open-telemetry/opentelemetry-collector/processor/queuedprocessor.(*queuedSpanProcessor).processItemFromQueue(0xc00008bb00, 0xc0001ab560)
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector@v0.2.8/processor/queuedprocessor/queued_processor.go:159 +0xf8
github.com/open-telemetry/opentelemetry-collector/processor/queuedprocessor.(*queuedSpanProcessor).Start.func1(0x20d8300, 0xc0001ab560)
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector@v0.2.8/processor/queuedprocessor/queued_processor.go:92 +0x45
github.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1(0xc0004106e0, 0xc0000c43c0)
	/go/pkg/mod/github.com/jaegertracing/jaeger@v1.17.0/pkg/queue/bounded_queue.go:77 +0xb9
created by github.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers
	/go/pkg/mod/github.com/jaegertracing/jaeger@v1.17.0/pkg/queue/bounded_queue.go:68 +0xc0
```

</details>
