### ISSUE TITLE
[exporter/splunkhec] Flaky test - TestConsumeMetricsData/large_batch

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#16285]
### Component(s)

exporter/splunkhec

### What happened?

```
=== RUN   TestConsumeMetricsData/large_batch
panic: test timed out after 5m0s

goroutine 567 [running]:
testing.(*M).startAlarm.func1()
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/testing/testing.go:2036 +0xbb
created by time.goFunc
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive, 3 minutes]:
testing.(*T).Run(0xc0001c0d00, {0x121c225, 0x16}, 0x1262060)
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/testing/testing.go:1494 +0x789
testing.runTests.func1(0x0?)
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/testing/testing.go:1846 +0x9a
testing.tRunner(0xc0001c0d00, 0xc0002dfba0)
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/testing/testing.go:1446 +0x217
testing.runTests(0xc0001b3400?, {0x197cee0, 0x31, 0x31}, {0x40?, 0x266bc68?, 0x1988880?})
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/testing/testing.go:1844 +0x7ed
testing.(*M).Run(0xc0001b3400)
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/testing/testing.go:1726 +0xa85
main.main()
	_testmain.go:163 +0x2ea
```

Observed here: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3460029827/jobs/5776100283#step:8:5386

And here: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3450053627/jobs/5758404911#step:8:5395

### Collector version

main

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by atoulme** [comment]
I note this specifically happens on Windows unit tests. I recommend we disable this test on Windows for now, thoughts?

**Comment by djaglowski** [comment]
I think so - it appears to be happening frequently

**Comment by dmitryax** [comment]
@atoulme seems like it started after the recent refactoring to count correct gzip payload. It might worth taking a deeper look. Number of active goroutines is concerning

**Comment by Aneurysm9** [comment]
Another instance: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3442836564/jobs/5743782681#step:8:5383

**Comment by atoulme** [comment]
Understood. Sorry for this - I will get a PR out ASAP to disable on Windows and take a look.

**Comment by atoulme** [comment]
Reviewing the code - it's manifest it's not closing the HTTP servers used during testing. I think I can at least try that to see if that frees up resources, especially goroutines. https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16305 is the PR for this.

**Comment by dmitryax** [comment]
Thanks @atoulme!

**Comment by dmitryax** [comment]
@atoulme looks like the fix didn't help. I still see the error https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3473353302/jobs/5805283472

**Comment by atoulme** [comment]
Understood. Less goroutines, but still seeing it. I welcome any help - this is still only happening on Windows.

**Comment by atoulme** [comment]
On Linux:
```
2022-11-15T21:38:38.2068287Z === RUN   TestConsumeMetricsData/large_batch
2022-11-15T21:39:53.5185759Z --- PASS: TestConsumeMetricsData (75.45s)
2022-11-15T21:39:53.5186481Z     --- PASS: TestConsumeMetricsData/happy_path (0.00s)
2022-11-15T21:39:53.5229090Z     --- PASS: TestConsumeMetricsData/response_forbidden (0.00s)
2022-11-15T21:39:53.5229565Z     --- PASS: TestConsumeMetricsData/large_batch (75.31s)
```
On a Windows successful build:
```
2022-11-15T19:54:27.1836266Z === RUN   TestConsumeMetricsData/large_batch
2022-11-15T19:57:27.1446294Z --- PASS: TestConsumeMetricsData (180.13s)
2022-11-15T19:57:27.1447923Z     --- PASS: TestConsumeMetricsData/happy_path (0.02s)
2022-11-15T19:57:27.1448982Z     --- PASS: TestConsumeMetricsData/response_forbidden (0.02s)
2022-11-15T19:57:27.1450047Z     --- PASS: TestConsumeMetricsData/large_batch (179.96s)
```

We send 65000 metric events through.

I think this is a bit beyond the scope of the unit test and this test feels heavy, so I have another PR to try to make this test less flaky yet still testing things:
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16322

**Comment by atoulme** [comment]
Closing. Please reopen if you see more occurrences of this issue.

**Comment by dmitryax** [comment]
Still
