### ISSUE TITLE
[receiver/chronyreceiver] Flaky test TestGettingTrackingData

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#16304]
### Component(s)

receiver/chrony

### What happened?

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3466820571/jobs/5791461370

```
=== CONT  TestGettingTrackingData/Timeout_waiting_for_response
=== CONT  TestGettingTrackingData/invalid_status_command
=== PAUSE TestNew/valid_host
panic: Fail in goroutine after TestGettingTrackingData/Timeout_waiting_for_response has completed

goroutine 24 [running]:
testing.(*common).Fail(0xc00014f520)
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/testing/testing.go:824 +0x1a8
testing.(*common).Errorf(0xc00014f520, {0x743ebd, 0x3}, {0xc00002b670, 0x1, 0x1})
	C:/hostedtoolcache/windows/go/1.19.2/x64/src/testing/testing.go:941 +0xaf
github.com/stretchr/testify/assert.Fail({0x80f520, 0xc00014f520}, {0xc000010fc0, 0x38}, {0xc00004bfc0, 0x1, 0x1})
	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.8.1/assert/assertions.go:264 +0x438
github.com/stretchr/testify/assert.NoError({0x80f520, 0xc00014f520}, {0x80f180, 0xc00002a190}, {0xc00004bfc0, 0x1, 0x1})
	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.8.1/assert/assertions.go:1392 +0x127
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/chronyreceiver/internal/chrony.newMockConn.func2()
	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/chronyreceiver/internal/chrony/client_test.go:37 +0x147
created by github.com/open-telemetry/opentelemetry-collector-contrib/receiver/chronyreceiver/internal/chrony.newMockConn
	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/chronyreceiver/internal/chrony/client_test.go:36 +0x2c5
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/chronyreceiver/internal/chrony	0.102s
?   	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/chronyreceiver/internal/metadata	[no test files]
FAIL
mingw32-make[2]: *** [../../Makefile.Common:57: test] Error 1
mingw32-make[1]: *** [makefile:188: receiver/chronyreceiver] Error 2
mingw32-make[1]: *** Waiting for unfinished jobs....
mingw32-make[2]: Leaving directory 'D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/chronyreceiver'
```

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by MovieStoreGuy** [comment]
Pants.

I am currently travelling for work atm but I can see about resolving this flaky test.

**Comment by MovieStoreGuy** [comment]
@dmitryax , this should be fine to close now right?

**Comment by dmitryax** [comment]
Sure, we can close now, thanks!
