### ISSUE TITLE
[exporter/splunkhec] TestConsumeMetricsData/large_batch

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#17177]
### What happened?

Seen in https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3742947318/jobs/6354558680

```
=== RUN   TestConsumeMetricsData/large_batch
    exporter_test.go:211: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/splunkhecexporter/exporter_test.go:211
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/splunkhecexporter/exporter_test.go:234
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/splunkhecexporter/server.go:2084
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/splunkhecexporter/server.go:2916
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/splunkhecexporter/server.go:1966
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/splunkhecexporter/asm_amd64.s:1571
        	Error:      	Not equal: 
        	            	expected: "gzip"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-gzip
        	            	+
        	Test:       	TestConsumeMetricsData/large_batch
    exporter_test.go:213: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/splunkhecexporter/exporter_test.go:213
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/splunkhecexporter/exporter_test.go:234
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/splunkhecexporter/server.go:2084
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/splunkhecexporter/server.go:2916
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/splunkhecexporter/server.go:1966
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/splunkhecexporter/asm_amd64.s:1571
        	Error:      	Received unexpected error:
        	            	gzip: invalid header
        	Test:       	TestConsumeMetricsData/large_batch
2022/12/20 18:11:23 http: panic serving 127.0.0.1:36948: runtime error: invalid memory address or nil pointer dereference
goroutine 622 [running]:
net/http.(*conn).serve.func1()
	/opt/hostedtoolcache/go/1.18.9/x64/src/net/http/server.go:1825 +0x106
panic({0x10b6700, 0x18d52c0})
	/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/panic.go:844 +0x258
compress/gzip.(*Reader).Read(0x0, {0xc000118800, 0x200, 0x200})
	/opt/hostedtoolcache/go/1.18.9/x64/src/compress/gzip/gunzip.go:247 +0x5e
io.ReadAll({0x132dc00, 0x0})
	/opt/hostedtoolcache/go/1.18.9/x64/src/io/io.go:645 +0x103
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/splunkhecexporter.TestConsumeMetricsData.func2(0xc0002be340, 0xc0000e4300)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/splunkhecexporter/exporter_test.go:214 +0x3ed
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/splunkhecexporter.TestConsumeMetricsData.func3.1({0x1336078, 0xc00001a0e0}, 0x4a1c57?)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/splunkhecexporter/exporter_test.go:234 +0x89
net/http.HandlerFunc.ServeHTTP(0xc0004adf80, {0x1336078, 0xc00001a0e0}, 0x1?)
	/opt/hostedtoolcache/go/1.18.9/x64/src/net/http/server.go:2084 +0x4e
net/http.serverHandler.ServeHTTP({0x1332818?}, {0x1336078, 0xc00001a0e0}, 0xc0000e4300)
	/opt/hostedtoolcache/go/1.18.9/x64/src/net/http/server.go:2916 +0x897
net/http.(*conn).serve(0xc000200140, {0x13368d8, 0xc00010aa80})
	/opt/hostedtoolcache/go/1.18.9/x64/src/net/http/server.go:1966 +0xbab
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.18.9/x64/src/net/http/server.go:3071 +0x80d
    exporter_test.go:266: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/splunkhecexporter/exporter_test.go:266
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:44987/": EOF
        	Test:       	TestConsumeMetricsData/large_batch
```

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by atoulme** [comment]
@harshit-splunk FYI. I'll take a look asap too as this might be hiding a bigger problem.

**Comment by dmitryax** [comment]
Thanks, @atoulme!

**Comment by dmitryax** [comment]
Another instance, just for the record: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3743257748/jobs/6355277535
