### ISSUE TITLE
[receiver/riak] Flaky integration test: TestRiakIntegration

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#17556]
### Component(s)

receiver/riak

### What happened?

Flaky test: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3907699006/jobs/6677193729

```
=== RUN   TestRiakIntegration
2023/01/13 02:15:26 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 20.10.22+azure-1
  API Version: 1.41
  Operating System: Ubuntu 22.04.1 LTS
  Total Memory: 6943 MB
2023/01/13 02:15:26 Starting container id: 3ed94d340f42 image: docker.io/testcontainers/ryuk:0.3.4
2023/01/13 02:15:26 Waiting for container id 3ed94d340f42 image: docker.io/testcontainers/ryuk:0.3.4
2023/01/13 02:15:26 Container is ready id: 3ed94d340f42 image: docker.io/testcontainers/ryuk:0.3.4
    integration_test.go:56: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/riakreceiver/integration_test.go:56
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/riakreceiver/integration_test.go:62
        	Error:      	Received unexpected error:
        	            	Error response from daemon: No such image: a21c129d-83b2-4b1d-8263-f3ba560e76f9:cc5a9dce-dfaa-418e-8320-45d6d6f277dd: failed to create container
        	Test:       	TestRiakIntegration
--- FAIL: TestRiakIntegration (51.11s)
```

### Collector version

0.69.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by atoulme** [comment]
Seeing it here as well: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3907747002/jobs/6677299815

**Comment by codeboten** [comment]
Seeing a slightly different problem with this test:

```
=== RUN   TestRiakIntegration
2023/01/13 04:55:14 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 20.10.22+azure-1
  API Version: 1.41
  Operating System: Ubuntu 22.04.1 LTS
  Total Memory: 6943 MB
2023/01/13 04:55:14 Starting container id: d4b3277d785a image: docker.io/testcontainers/ryuk:0.3.4
2023/01/13 04:55:14 Waiting for container id d4b3277d785a image: docker.io/testcontainers/ryuk:0.3.4
2023/01/13 04:55:14 Container is ready id: d4b3277d785a image: docker.io/testcontainers/ryuk:0.3.4
coverage: 0.0% of statements
panic: test timed out after 6m0s

goroutine 33 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:2036 +0xbb
created by time.goFunc
	/opt/hostedtoolcache/go/1.19.4/x64/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive, 6 minutes]:
testing.(*T).Run(0xc0000da820, {0x1391e68, 0x13}, 0x13dd078)
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1494 +0x789
testing.runTests.func1(0x0?)
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1846 +0x9a
testing.tRunner(0xc0000da820, 0xc0005bfb68)
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1446 +0x217
testing.runTests(0xc0004ac0a0?, {0x42ec1c0, 0x7, 0x7}, {0x40?, 0x7f8035f9f018?, 0x42fed20?})
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1844 +0x7ed
testing.(*M).Run(0xc0004ac0a0)
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1726 +0xa85
main.main()
	_testmain.go:115 +0x3bd

goroutine 6 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000f0b80)
	/home/runner/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x185
created by go.opencensus.io/stats/view.init.0
	/home/runner/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0xf7

goroutine 19 [IO wait]:
internal/poll.runtime_pollWait(0x7f8035f955d8, 0x72)
	/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc00010e318, 0xc000161000?, 0x0)
	/opt/hostedtoolcache/go/1.19.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0xbd
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.19.4/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00010e300, {0xc000161000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.19.4/x64/src/internal/poll/fd_unix.go:167 +0x415
net.(*netFD).Read(0xc00010e300, {0xc000161000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.19.4/x64/src/net/fd_posix.go:55 +0x51
net.(*conn).Read(0xc000014048, {0xc000161000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.19.4/x64/src/net/net.go:183 +0xb1
net/http.(*persistConn).Read(0xc0003407e0, {0xc000161000, 0x1000, 0x1000})
	/opt/hostedtoolcache/go/1.19.4/x64/src/net/http/transport.go:1929 +0x105
bufio.(*Reader).fill(0xc00008cb40)
	/opt/hostedtoolcache/go/1.19.4/x64/src/bufio/bufio.go:106 +0x2ab
bufio.(*Reader).ReadSlice(0xc00008cb40, 0x33?)
	/opt/hostedtoolcache/go/1.19.4/x64/src/bufio/bufio.go:372 +0x89
net/http/internal.readChunkLine(0x4a8ef7?)
	/opt/hostedtoolcache/go/1.19.4/x64/src/net/http/internal/chunked.go:129 +0x36
net/http/internal.(*chunkedReader).beginChunk(0xc0001b48a0)
	/opt/hostedtoolcache/go/1.19.4/x64/src/net/http/internal/chunked.go:48 +0x45
net/http/internal.(*chunkedReader).Read(0xc0001b48a0, {0xc0002ab9ba, 0x646, 0x646})
	/opt/hostedtoolcache/go/1.19.4/x64/src/net/http/internal/chunked.go:98 +0x2b4
net/http.(*body).readLocked(0xc000425a00, {0xc0002ab9ba, 0x646, 0x646})
	/opt/hostedtoolcache/go/1.19.4/x64/src/net/http/transfer.go:846 +0xb8
net/http.(*body).Read(0xc000425a00, {0xc0002ab9ba, 0x646, 0x646})
	/opt/hostedtoolcache/go/1.19.4/x64/src/net/http/transfer.go:838 +0x17c
net/http.(*bodyEOFSignal).Read(0xc000425a40, {0xc0002ab9ba, 0x646, 0x646})
	/opt/hostedtoolcache/go/1.19.4/x64/src/net/http/transport.go:2774 +0x143
bytes.(*Buffer).ReadFrom(0xc0002371c0, {0x1543d80, 0xc000425a40})
	/opt/hostedtoolcache/go/1.19.4/x64/src/bytes/buffer.go:202 +0x113
github.com/testcontainers/testcontainers-go.(*DockerProvider).BuildImage(0xc0005141c0, {0x154bf38, 0xc000048138}, {0x154da40, 0xc0000aa000})
	/home/runner/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.17.0/docker.go:913 +0x4d6
github.com/testcontainers/testcontainers-go.(*DockerProvider).CreateContainer(_, {_, _}, {{{0xc000042240, 0x14}, {0x0, 0x0}, {0x138e3a7, 0xf}, 0x0, ...}, ...})
	/home/runner/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.17.0/docker.go:993 +0x105b
github.com/testcontainers/testcontainers-go.GenericContainer({_, _}, {{{{0xc000042240, 0x14}, {0x0, 0x0}, {0x138e3a7, 0xf}, 0x0, 0x0, ...}, ...}, ...})
	/home/runner/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.17.0/generic.go:68 +0x2d3
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/riakreceiver.riakContainer(0xc0000da9c0?)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/riakreceiver/integration_test.go:52 +0x38d
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/riakreceiver.TestRiakIntegration(0xc0000da9c0)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/riakreceiver/integration_test.go:62 +0x4b
testing.tRunner(0xc0000da9c0, 0x13dd078)
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1446 +0x217
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1493 +0x75e

goroutine 31 [chan receive, 6 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1({0x154fac8?, 0xc000014c28})
	/home/runner/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.17.0/reaper.go:151 +0x836
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/home/runner/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.17.0/reaper.go:116 +0x305

goroutine 21 [select, 6 minutes]:
net/http.(*persistConn).readLoop(0xc0003407e0)
	/opt/hostedtoolcache/go/1.19.4/x64/src/net/http/transport.go:2213 +0x14ef
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.19.4/x64/src/net/http/transport.go:1751 +0x2586

goroutine 22 [select, 6 minutes]:
net/http.(*persistConn).writeLoop(0xc0003407e0)
	/opt/hostedtoolcache/go/1.19.4/x64/src/net/http/transport.go:2392 +0x1a9
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.19.4/x64/src/net/http/transport.go:1752 +0x261a
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/riakreceiver	360.045s
```

**Comment by mdelapenya** [comment]
@djaglowski sorry for the late response, I was on paternity leave until past Tuesday. I'll take a deeper look ASAP

**Comment by mdelapenya** [comment]
A quick look at the stacktrace tells me that the BuildFromDockerfile is timing out:

```
github.com/testcontainers/testcontainers-go.(*DockerProvider).BuildImage(0xc0005141c0, {0x154bf38, 0xc000048138}, {0x154da40, 0xc0000aa000})
```

Do you see this error correlated with network issues? We probably detected a timeout not properly covered in the build code of testcontainers-go

**Comment by djaglowski** [comment]
Thanks for looking into this @mdelapenya! We've seen this just a few times in CI, so a timeout seems plausible as it would just require an occasional slow connection during a test run. Is the timeout configurable, or do you think this may require a patch upstream?

**Comment by mdelapenya** [comment]
MMM I've seen that the docker client call to Build in the library is not configured for retries, but OTOH the client call to Pull images (in another place) indeed does.

I think the upstream could be updated with that improvement 🤔

**Comment by mdelapenya** [comment]
Sent a patch. I'd appreciate a review before merging the upstream🤞

**Comment by djaglowski** [comment]
It looks good to me. Thanks so much @mdelapenya!

**Comment by mdelapenya** [comment]
Folks, we merged the upstream although not released yet. Because we are not following a very strict release plan, you could probably use the patched version consuming the last commit in the main branch as a dependency: https://github.com/testcontainers/testcontainers-go/commit/086187770b0973f7da0d42c1807e0467c745ca46

**Comment by djaglowski** [comment]
Thank you @mdelapenya!

We typically try to avoid going off-version with our dependencies, though we do on occasion. That said, this problem has been only intermittent, so I think we can likely give it some time before picking up the fix in an official release.

**Comment by mdelapenya** [comment]
As of 0.18.0 release was out and updated in this repo, we hypothetically shouldn't see this flakiness anymore 🤞

**Comment by djaglowski** [comment]
Thanks again @mdelapenya!

I'm closing this for now. We can reopen if it continues to occur.

**Comment by TylerHelmuth** [comment]
Flaky test is back: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4992911579/jobs/8941308976
