### ISSUE TITLE
flaky test: Test_runContents/validate_metadata

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#17576]
### Component(s)

cmd/mdatagen

### Describe the issue you're reporting

This test is flaky on windows: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3908076186/jobs/6677910807

```
--- FAIL: Test_runContents (0.02s)
    --- FAIL: Test_runContents/valid_metadata (0.02s)
panic: template: pattern matches no files: `templates\metrics.go.tmpl` [recovered]
	panic: template: pattern matches no files: `templates\metrics.go.tmpl`

goroutine 44 [running]:
testing.tRunner.func1.2({0xee8040, 0xc0003cbbd0})
	C:/hostedtoolcache/windows/go/1.19.4/x64/src/testing/testing.go:1396 +0x372
testing.tRunner.func1()
	C:/hostedtoolcache/windows/go/1.19.4/x64/src/testing/testing.go:1399 +0x5f0
panic({0xee8040, 0xc0003cbbd0})
	C:/hostedtoolcache/windows/go/1.19.4/x64/src/runtime/panic.go:890 +0x262
text/template.Must(...)
	C:/hostedtoolcache/windows/go/1.19.4/x64/src/text/template/helper.go:26
github.com/open-telemetry/opentelemetry-collector-contrib/cmd/mdatagen.generateFile({0xc00036f540, 0x19}, {0xc0000cf080, 0x78}, {{0xc000363fa2, 0xe}, {0x0, 0x0}, 0x0, 0x0, ...})
	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/mdatagen/main.go:72 +0xfa6
github.com/open-telemetry/opentelemetry-collector-contrib/cmd/mdatagen.run({0xc0000835c0, 0x5f})
	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/mdatagen/main.go:56 +0x570
github.com/open-telemetry/opentelemetry-collector-contrib/cmd/mdatagen.Test_runContents.func1(0xc000368b60)
	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/mdatagen/main_test.go:59 +0x12b
testing.tRunner(0xc000368b60, 0xc0003ca820)
	C:/hostedtoolcache/windows/go/1.19.4/x64/src/testing/testing.go:1446 +0x217
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.19.4/x64/src/testing/testing.go:1493 +0x75e
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/cmd/mdatagen	0.272s
mingw32-make[2]: *** [../../Makefile.Common:69: test] Error 1
mingw32-make[1]: *** [makefile:171: cmd/mdatagen] Error 2
```

**Comment by codeboten** [comment]
This test started failing on windows after this change: https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/7711ef492bbd60dab9cf5858a39e2fb2e3054b8d

**Comment by MovieStoreGuy** [comment]
Interesting, I would has assume embed / fs.FS would be OS agnostic.

**Comment by codeboten** [comment]
Yeah it wasn't immediately clear to me where the problem was, whether windows needs some prefix for the template path or what. it could be the combination of embed fs + filepath that causes issues on windows? I didn't get much time to dig into it.

**Comment by MovieStoreGuy** [comment]
I am out this weekend, but I am happy to take a look once I am back :)

**Comment by MovieStoreGuy** [comment]
Fixed with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17586
