### ISSUE TITLE
[receiver/sshcheck] Flaky test TestScraper/metrics_golden_sftp

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#18193]
### Component(s)

receiver/sshcheck

### What happened?

```
--- FAIL: TestScraper (4.80s)
    --- FAIL: TestScraper/metrics_golden (0.02s)
    --- FAIL: TestScraper/metrics_golden_sftp (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf58549]

goroutine 65 [running]:
testing.tRunner.func1.2({0x118dda0, 0x1a3cc70})
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1389 +0x366
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1392 +0x5d2
panic({0x118dda0, 0x1a3cc70})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:844 +0x258
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sshcheckreceiver/internal/configssh.(*Client).SFTPClient(0xc00010eb40)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/sshcheckreceiver/internal/configssh/configssh.go:68 +0x49
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sshcheckreceiver.(*sshcheckScraper).scrapeSFTP(0xc00043a0a0, 0x173f3ebb84946e6f?)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/sshcheckreceiver/scraper.go:69 +0x7b
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sshcheckreceiver.(*sshcheckScraper).scrape(0xc00043a0a0, {0x1441d60, 0xc00003c128})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/sshcheckreceiver/scraper.go:133 +0x5d8
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sshcheckreceiver.TestScraper.func2(0x0?)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/sshcheckreceiver/scraper_test.go:132 +0x925
testing.tRunner(0xc0000b0ea0, 0xc000339110)
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x214
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1486 +0x725
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sshcheckreceiver	4.860s
```

Seen here: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4049569807/jobs/6966104240

### Collector version

current main

**Comment by nslaughter** [comment]
Looking at this now.
