### ISSUE TITLE
 [receiver/awsecscontainermetricsreceiver] nil pointer dereference when run in a windows ECS environment

### ISSUE THREAD

**Issue by NixM0nk3y** [open-telemetry/opentelemetry-collector-contrib#19213]
### Component(s)

receiver/awsecscontainermetrics

## Description

Hosting a otel collector ( aws-otel-collector ) using the awsecscontainermetricsreceiver component in a windows ECS environment results in a crash of the collector.

This seems to be a result of the docker `stats` data produced by a windows metadata endpoint being slightly different to the data being produced by a linux container.  

The issue seems to stem from this code:

```
	if stats.Memory != nil {
		m.MemoryUsage = *stats.Memory.Usage
		m.MemoryMaxUsage = *stats.Memory.MaxUsage
		m.MemoryLimit = *stats.Memory.Limit

		if stats.Memory.Stats != nil {
			m.MemoryUtilized = (*stats.Memory.Usage - stats.Memory.Stats["cache"]) / bytesInMiB
		}
	} else {
```
 
This assumes the usage/maxusage/limit keys are available under the stats memory structure.  This isn't the case on the windows stats endpoint:

```
    "memory_stats": {
        "commitbytes": 114061312,
        "commitpeakbytes": 139227136,
        "privateworkingset": 85532672
    },
```
A example of separate Windows/Linux handling can be seen in the [ecs agent codebase](https://github.com/aws/amazon-ecs-agent/tree/master/agent/stats).

## Steps to Reproduce

Install the collector in a windows ECS container.

## Expected Result

The collector pulls metrics via the local metadata endpoint and available for processing within the otel collector.

## Actual Result

The collector crashes.

### Collector version

v0.72.0 (aws-otel-collector/0.27.0)

## Environment
OS: Windows Server Core 2022
Compiler(if manually compiled): go 1.19.5

### OpenTelemetry Collector configuration

```yaml
receivers:
  awsecscontainermetrics:
    collection_interval: 20s
  otlp/sidecar:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
processors:
  filter:
    metrics:
      include:
        match_type: strict
        metric_names:
          - ecs.task.memory.utilized
          - ecs.task.memory.reserved
          - ecs.task.cpu.utilized
          - ecs.task.cpu.reserved
          - ecs.task.network.rate.rx
          - ecs.task.network.rate.tx
          - ecs.task.storage.read_bytes
          - ecs.task.storage.write_bytes
exporters:
  otlp/central:
    endpoint: collector:4317
  logging:
    verbosity: normal
extensions:
  health_check:
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp/sidecar]
      exporters: [logging, otlp/central]
    metrics/otlp:
      receivers: [otlp/sidecar]
      exporters: [logging, otlp/central]
    metrics/ecs:
      receivers: [awsecscontainermetrics]
      processors: [filter]
      exporters: [logging, otlp/central]
```

### Log output

```shell
2023/03/04 17:24:39 ADOT Collector version: v0.27.0
2023/03/04 17:24:39 found no extra config, skip it, err: open C:\ProgramData\Amazon\AWSOTelCollector\Configs\extracfg.txt: The system cannot find the file specified.
2023-03-04T17:24:39.303Z        info    service/telemetry.go:90 Setting up own telemetry...
2023-03-04T17:24:39.303Z        info    service/telemetry.go:116        Serving Prometheus metrics      {"address": ":8888", "level": "Basic"}
2023-03-04T17:24:39.304Z        info    exporter/exporter.go:286        Development component. May change in the future.        {"kind": "exporter", "data_type": "traces", "name": "logging"}
2023-03-04T17:24:39.304Z        info    exporter/exporter.go:286        Development component. May change in the future.        {"kind": "exporter", "data_type": "metrics", "name": "logging"}
2023-03-04T17:24:39.307Z        info    filterprocessor@v0.72.0/metrics.go:97   Metric filter configured        {"kind": "processor", "name": "filter", "pipeline": "metrics/ecs", "include match_type": "strict", "include expre
ssions": [], "include metric names": ["ecs.task.memory.utilized", "ecs.task.memory.reserved", "ecs.task.cpu.utilized", "ecs.task.cpu.reserved", "ecs.task.network.rate.rx", "ecs.task.network.rate.tx", "ecs.task.storage.read_by
tes", "ecs.task.storage.write_bytes"], "include metrics with resource attributes": null, "exclude match_type": "", "exclude expressions": [], "exclude metric names": [], "exclude metrics with resource attributes": null}
2023-03-04T17:24:39.307Z        info    service/service.go:140  Starting aws-otel-collector...  {"Version": "v0.27.0", "NumCPU": 4}
2023-03-04T17:24:39.307Z        info    extensions/extensions.go:41     Starting extensions...
2023-03-04T17:24:39.308Z        info    extensions/extensions.go:44     Extension is starting...        {"kind": "extension", "name": "health_check"}
2023-03-04T17:24:39.308Z        info    healthcheckextension@v0.72.0/healthcheckextension.go:45 Starting health_check extension {"kind": "extension", "name": "health_check", "config": {"Endpoint":"0.0.0.0:13133","TLSSetting":
null,"CORS":null,"Auth":null,"MaxRequestBodySize":0,"IncludeMetadata":false,"Path":"/","CheckCollectorPipeline":{"Enabled":false,"Interval":"5m","ExporterFailureThreshold":5}}}
2023-03-04T17:24:39.308Z        warn    internal/warning.go:51  Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks        {"kind": "extension", "name": "he
alth_check", "documentation": "https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks"}
2023-03-04T17:24:39.308Z        info    extensions/extensions.go:48     Extension started.      {"kind": "extension", "name": "health_check"}
2023-03-04T17:24:39.308Z        warn    internal/warning.go:51  Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks        {"kind": "receiver", "name": "otl
p/sidecar", "data_type": "traces", "documentation": "https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks"}
2023-03-04T17:24:39.308Z        info    otlpreceiver@v0.72.0/otlp.go:94 Starting GRPC server    {"kind": "receiver", "name": "otlp/sidecar", "data_type": "traces", "endpoint": "0.0.0.0:4317"}
2023-03-04T17:24:39.310Z        info    healthcheck/handler.go:129      Health Check state change       {"kind": "extension", "name": "health_check", "status": "ready"}
2023-03-04T17:24:39.310Z        info    service/service.go:157  Everything is ready. Begin running and processing data.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x2e81cec]

goroutine 116 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver/internal/awsecscontainermetrics.getContainerMetrics(0xc000670280, 0x3f9c7e0?)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver@v0.72.0/internal/awsecscontainermetrics/metrics_helper.go:26 +0x8c
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver/internal/awsecscontainermetrics.convertContainerMetrics(_, _, {{0x0, 0x0}, {0xc000054c48, 0x13}, {0xc000051680, 0x1c}, {0xc0000
4cc00, 0x40}, ...})
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver@v0.72.0/internal/awsecscontainermetrics/accumulator.go:80 +0x58
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver/internal/awsecscontainermetrics.(*metricDataAccumulator).getMetricsData(0xc00092fc60, 0x0?, {{0xc00040b550, 0xa}, {0xc000050b80
, 0x19}, {0xc0003ba000, 0x2, 0x4}, {0xc000054690, ...}, ...}, ...)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver@v0.72.0/internal/awsecscontainermetrics/accumulator.go:51 +0x445
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver/internal/awsecscontainermetrics.MetricsData(...)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver@v0.72.0/internal/awsecscontainermetrics/metrics.go:27
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver.(*awsEcsContainerMetricsReceiver).collectDataFromEndpoint(0xc0003fdc00, {0x4c47fd0, 0xc0009f2740})
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver@v0.72.0/receiver.go:99 +0x429
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver.(*awsEcsContainerMetricsReceiver).Start.func1()
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver@v0.72.0/receiver.go:71 +0xa9
created by github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver.(*awsEcsContainerMetricsReceiver).Start
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver@v0.72.0/receiver.go:64 +0xca
```

**Comment by piequi** [comment]
We actually experience the same issue running the ECS agent on Debian 11.

Just like what's reported in the description, Docker stats are different even from Amazon Linux and Debian. Only talking about memory, here are the different stats samples taken out from the ECS agent endpoint :

Debian:
``` 
"memory_stats": {
    "usage": 585580544,
    "stats": {
      "active_anon": 540672,
      "active_file": 135168,
      "anon": 559710208,
      "anon_thp": 138412032,
      "file": 7569408,
      "file_dirty": 0,
      "file_mapped": 6352896,
      "file_writeback": 0,
      "inactive_anon": 565944320,
      "inactive_file": 946176,
      "kernel_stack": 2162688,
      "pgactivate": 6633,
      "pgdeactivate": 0,
      "pgfault": 5029167,
      "pglazyfree": 2838,
      "pglazyfreed": 0,
      "pgmajfault": 0,
      "pgrefill": 0,
      "pgscan": 0,
      "pgsteal": 0,
      "shmem": 7163904,
      "slab": 6477488,
      "slab_reclaimable": 3021256,
      "slab_unreclaimable": 3456232,
      "sock": 245760,
      "thp_collapse_alloc": 0,
      "thp_fault_alloc": 66,
      "unevictable": 0,
      "workingset_activate": 0,
      "workingset_nodereclaim": 0,
      "workingset_refault": 0
    },
    "limit": 32908488704
  }
```

Amazon Linux: 
```
  "memory_stats": {
    "usage": 561233920,
    "max_usage": 576638976,
    "stats": {
      "active_anon": 0,
      "active_file": 0,
      "cache": 7434240,
      "dirty": 0,
      "hierarchical_memory_limit": 8589934592,
      "hierarchical_memsw_limit": 9223372036854771712,
      "inactive_anon": 542023680,
      "inactive_file": 811008,
      "mapped_file": 5812224,
      "pgfault": 3806319,
      "pgmajfault": 0,
      "pgpgin": 3804669,
      "pgpgout": 3672083,
      "rss": 535805952,
      "rss_huge": 0,
      "total_active_anon": 0,
      "total_active_file": 0,
      "total_cache": 7434240,
      "total_dirty": 0,
      "total_inactive_anon": 542023680,
      "total_inactive_file": 811008,
      "total_mapped_file": 5812224,
      "total_pgfault": 3806319,
      "total_pgmajfault": 0,
      "total_pgpgin": 3804669,
      "total_pgpgout": 3672083,
      "total_rss": 535805952,
      "total_rss_huge": 0,
      "total_unevictable": 0,
      "total_writeback": 0,
      "unevictable": 0,
      "writeback": 0
    },
    "limit": 32890413056
  }
```
`max_usage` is obviously missing and `stats.cache` too from Debian output.

The error stack trace is the same (as the one reported) no matter the ECS agent (`1.68.2`, `1.69.0`, `1.70.0`) and Docker (`20.10.17`) versions are used.

**Comment by piequi** [comment]
Looking at [Docker API docs v1.41](https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerStats), this seems related to cgroup version:
```
On a cgroup v2 host, the following fields are not set

blkio_stats: all fields other than io_service_bytes_recursive
cpu_stats: cpu_usage.percpu_usage
memory_stats: max_usage and failcnt Also, memory_stats.stats fields are incompatible with cgroup v1.
```

**Comment by erichsueh3** [comment]
I don't think it's possible to change the docker stats data produced by the metadata endpoint (at least not here), so would the ask then be to fix the [code snippet](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/awsecscontainermetricsreceiver/internal/awsecscontainermetrics/metrics_helper.go#L25-L28) linked above, by adding in additional nil checks to see if usage/maxusage/limit is available from the Memory structure?
