### ISSUE TITLE
filelogreceiver panics when trace_flags is an empty string

### ISSUE THREAD

**Issue by bgranetzke** [open-telemetry/opentelemetry-collector-contrib#20924]
### Component(s)

pkg/stanza

## Description
collector panics when trace parse operator encounters empty string for trace_flags

## Steps to Reproduce
My use case is a regex operator which accounts for the log line optionally containing the trace/trace flags at the end.  
`      - type: regex_parser
        regex: '(?P<traceid>[0-9a-f]+)?[_]?(?P<traceflags>[0-9a-f]+)?$'
        trace:
          trace_id:
            parse_from: attributes.traceid
          trace_flags:
            parse_from: attributes.traceflags
`

## Expected Result
parser gracefully does not try to add trace flags

## Actual Result
Panic:
`
panic: runtime error: index out of range [0] with length 0
goroutine 177 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.convertInto(0xc047473140, {0x90?})
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.70.0/adapter/converter.go:338 +0x2b5
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.convert(0xc000baef90?)
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.70.0/adapter/converter.go:284 +0x37
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.(*Converter).workerLoop(0xc000617680)
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.70.0/adapter/converter.go:167 +0x27b
created by github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.(*Converter).Start
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.70.0/adapter/converter.go:118 +0xf5
`

panic line in current main: 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/adapter/converter.go#L271

The root cause might be further upstream (passing an empty []byte instead of a nil), but I think some simple defensive programming here makes sense (add a len() check in addition to the nil check)

### Collector version

0.70.0

**Comment by atoulme** [comment]
Thanks for the report @bgranetzke, would you be interested in contributing a test case reproducing the problem?

**Comment by bgranetzke** [comment]
@atoulme Not sure if this is what you meant, but I cut a PR with a unit test which exercised the specific condition and then I fixed the cause.

**Comment by bgranetzke** [comment]
FYI: I was also able to reproduce the problem when I upgraded the collector version to 0.75.0
```
panic: runtime error: index out of range [0] with length 0
goroutine 121 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.convertInto(0xc000000a80, {0xc000418d50?})
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.75.0/adapter/converter.go:271 +0x2b5
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.(*Converter).workerLoop(0xc000644a50)
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.75.0/adapter/converter.go:174 +0x6ac
created by github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.(*Converter).Start
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.75.0/adapter/converter.go:104 +0x112

```

**Comment by crobert-1** [comment]
@bgranetzke Thanks for fixing this! Feel free to close this issue if it's in fact resolved.
