### ISSUE TITLE
Fix rotate-milestone job

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#21255]
### What happened?

See [rotate-milestone](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4825487228/jobs/8596965110?pr=21240#logs)

```
with:
    script: const milestones = await github.rest.issues.listMilestones({
    owner: context.repo.owner,
    repo: context.repo.repo,
    state: "open"
  })
  for (const milestone of milestones.data) {
    if (milestone.title == "next release") {
      await github.rest.issues.updateMilestone({
        owner: context.repo.owner,
        repo: context.repo.repo,
        milestone_number: milestone.number,
        title: ""
      });
      await github.rest.issues.createMilestone({
        owner: context.repo.owner,
        repo: context.repo.repo,
        title: "next release"
      });
      return
    }
  }
  
    github-token: ***
    debug: false
    user-agent: actions/github-script
    result-encoding: json
    retries: 0
    retry-exempt-status-codes: 400,401,40[3](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4825487228/jobs/8596965110?pr=21240#step:2:3),[4](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4825487228/jobs/8596965110?pr=21240#step:2:4)04,422
  env:
    TEST_RESULTS: testbed/tests/results/junit/results.xml
    SEGMENT_DOWNLOAD_TIMEOUT_MINS: [5](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4825487228/jobs/8596965110?pr=21240#step:2:5)
RequestError [HttpError]: Validation Failed: {"resource":"Milestone","code":"missing_field","field":"title"}
```

```
Error: Unhandled error: HttpError: Validation Failed: {"resource":"Milestone","code":"missing_field","field":"title"}
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:6842:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15143:16), <anonymous>:10:5)
    at async main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:152[36](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4825487228/jobs/8596965110?pr=21240#step:2:37):20) {
  status: 422,
  response: {
    url: 'https://api.github.com/repos/open-telemetry/opentelemetry-collector-contrib/milestones/12',
    status: 422,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-length': '193',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Fri, 28 Apr 2023 00:[39](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4825487228/jobs/8596965110?pr=21240#step:2:40):53 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'B052:0CDA:1CD981:3BFD51:644B15D9',
      'x-ratelimit-limit': '15000',
      'x-ratelimit-remaining': '14997',
      'x-ratelimit-reset': '1682645982',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '3',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Validation Failed',
      errors: [Array],
      documentation_url: 'https://docs.github.com/rest/reference/issues#update-a-milestone'
    }
  },
  request: {
    method: 'PATCH',
    url: 'https://api.github.com/repos/open-telemetry/opentelemetry-collector-contrib/milestones/12',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'actions/github-script octokit-core.js/3.6.0 Node.js/16.16.0 (linux; x[64](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4825487228/jobs/8596965110?pr=21240#step:2:65))',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"title":""}',
    request: { agent: [Agent], hook: [Function: bound bound register] }
  }
}
```

### Collector version

0.76.3

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by atoulme** [comment]
It appears, naively reading the error, that we need to pass the right parameter in this script for it to succeed.
