### ISSUE TITLE
[exporter/dataset] TestConsumeLogsShouldSucceed fails on Windows

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#22039]
### Component(s)

exporter/dataset

### Describe the issue you're reporting

After merging #21815, unit tests on Windows for the dataset exporter have started failing on main, see https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5002859274/jobs/8963342956
```
--- FAIL: TestSuiteLogsExporter (0.03s)
    --- FAIL: TestSuiteLogsExporter/TestConsumeLogsShouldSucceed (0.01s)
        suite.go:87: test panicked: httptest: failed to listen on a port: listen tcp6 [::1]:0: socket: The requested service provider could not be loaded or initialized.
            goroutine 50 [running]:
            runtime/debug.Stack()
            	C:/hostedtoolcache/windows/go/1.19.9/x64/src/runtime/debug/stack.go:24 +0x72
            github.com/stretchr/testify/suite.failOnPanic(0xc000085ba0, {0x11c99c0, 0xc000321fc0})
            	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.8.2/suite/suite.go:87 +0x45
            github.com/stretchr/testify/suite.Run.func1.1()
            	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.8.2/suite/suite.go:183 +0x34c
            panic({0x11c99c0, 0xc000321fc0})
            	C:/hostedtoolcache/windows/go/1.19.9/x64/src/runtime/panic.go:890 +0x262
            net/http/httptest.newLocalListener()
            	C:/hostedtoolcache/windows/go/1.19.9/x64/src/net/http/httptest/server.go:71 +0x179
            net/http/httptest.NewUnstartedServer(...)
            	C:/hostedtoolcache/windows/go/1.19.9/x64/src/net/http/httptest/server.go:119
            net/http/httptest.NewServer({0x14b79e0?, 0xc0004f7860})
            	C:/hostedtoolcache/windows/go/1.19.9/x64/src/net/http/httptest/server.go:106 +0x37
            github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter.(*SuiteLogsExporter).TestConsumeLogsShouldSucceed(0xc0000dc480)
            	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/datasetexporter/logs_exporter_test.go:276 +0x2e5
            reflect.Value.call({0xc000486a80?, 0xc0000d9350?, 0x448bcd?}, {0x1314[637](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5002859274/jobs/8963342956#step:7:638), 0x4}, {0xc000069db8, 0x1, 0xc000069be8?})
            	C:/hostedtoolcache/windows/go/1.19.9/x64/src/reflect/value.go:584 +0xfdd
            reflect.Value.Call({0xc000486a80?, 0xc0000d9350?, 0xc0000dc480?}, {0xc000069db8, 0x1, 0x1})
            	C:/hostedtoolcache/windows/go/1.19.9/x64/src/reflect/value.go:368 +0xc8
            github.com/stretchr/testify/suite.Run.func1(0xc000085ba0)
            	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.8.2/suite/suite.go:197 +0x6e7
            testing.tRunner(0xc000085ba0, 0xc00015a5a0)
            	C:/hostedtoolcache/windows/go/1.19.9/x64/src/testing/testing.go:1446 +0x217
            created by testing.(*T).Run
            	C:/hostedtoolcache/windows/go/1.19.9/x64/src/testing/testing.go:1493 +0x75e
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter	1.204s
?   	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter/internal/metadata	[no test files]
FAIL
```

**Comment by mx-psi** [comment]
If we don't find a solution for this we can revert #21815 since it seems to be the culprit

**Comment by martin-majlis-s1** [comment]
This is fixed in this PR - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22041#discussion_r1197950877
