### ISSUE TITLE
prometheusremotewriteexporter logs spurious errors with WAL configured and no metrics to be sent

### ISSUE THREAD

**Issue by gburek-fastly** [open-telemetry/opentelemetry-collector-contrib#24399]
### Component(s)

exporter/prometheusremotewrite

## Description

When the prometheusremotewriteexporter is configured to use a WAL directory and is receiving no metrics to export, it will emit error logs that `error processing WAL entries` where there are, in fact, none to be processed. The exporter should fall back to using `fsnotify.NewWatcher()` but it does not. 

## Steps to Reproduce

run otelcol-contrib with included config

## Expected Result

no errors and no error logs

## Actual Result

error logs emitted every 5s

### Collector version

v0.81.0

## Environment
OS: osx, colima, docker
docker run --rm --mount type=bind,source=$(pwd),target=/etc/otelcol/   otel/opentelemetry-collector-contrib:latest --config /etc/otelcol/config.yaml

### OpenTelemetry Collector configuration

```yaml
exporters:
  prometheusremotewrite:
    endpoint: "http://host.docker.internal:9090/api/v1/push"
    wal:
      directory: /etc/otelcol/
extensions:
  health_check: {}
  memory_ballast:
    size_in_percentage: 40
processors:
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
service:
  extensions:
  - health_check
  - memory_ballast
  pipelines:
    metrics:
      exporters:
      - prometheusremotewrite
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp
```

### Log output

```shell
2023-07-19T23:00:48.424Z        info    service/service.go:158  Everything is ready. Begin running and processing data.
2023-07-19T23:00:52.535Z        error   prw.wal prometheusremotewriteexporter@v0.77.0/wal.go:182        error processing WAL entries    {"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite", "error": "not found"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter.(*prweWAL).run.func1
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter@v0.77.0/wal.go:182
2023-07-19T23:00:56.659Z        error   prw.wal prometheusremotewriteexporter@v0.77.0/wal.go:182        error processing WAL entries    {"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite", "error": "not found"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter.(*prweWAL).run.func1
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter@v0.77.0/wal.go:182
2023-07-19T23:01:00.792Z        error   prw.wal prometheusremotewriteexporter@v0.77.0/wal.go:182        error processing WAL entries    {"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite", "error": "not found"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter.(*prweWAL).run.func1
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter@v0.77.0/wal.go:182
```

### Additional context

It appears that the error check in `*prweWAL.readPrompbFromWAL` for `wal.ErrNotFound` is not correctly catching it, as the `"error": "not found"` text is rising up to the `"error processing WAL entries"` error logging. 

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusremotewriteexporter/wal.go#L358

**Comment by crobert-1** [comment]
I was able to reproduce and debug this locally with the shared config.

The error is actually being caught as expected, it's just that after [12 retries](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f927e31eda2165811a279026e54c0acdc1fd5495/exporter/prometheusremotewriteexporter/wal.go#L327) the read fails and [returns](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f927e31eda2165811a279026e54c0acdc1fd5495/exporter/prometheusremotewriteexporter/wal.go#L424) the `err` variable, which is simply the last err seen.

After every read attempt, there is a [sleep call that increases](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f927e31eda2165811a279026e54c0acdc1fd5495/exporter/prometheusremotewriteexporter/wal.go#L364) with each failure. This is where the ~4 second delay comes in, because after all of the delays are done it will [start over from the beginning](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f927e31eda2165811a279026e54c0acdc1fd5495/exporter/prometheusremotewriteexporter/wal.go#L173), disregarding the default (or set) [wal.TruncateFrequency](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f927e31eda2165811a279026e54c0acdc1fd5495/exporter/prometheusremotewriteexporter/wal.go#L45)

I agree this is annoying log spam, but I don't have enough expertise here to confidently say what to do about it. I think it's a good idea in most cases to log an error, since you'd theoretically expect to be getting data if you're running the collector. 4 seconds without data in a regular use case seems like a problem, so I think we do the right thing logging.

I'll defer to code owners but I think at most we may decrease log level to `WARN`, I don't think we would want to ignore this kind of error (unless I'm missing something).

**Comment by toughnoah** [comment]
@crobert-1 However, if I configure the wal,  **no metrics will be sent,** and I can just find this error log. I think it is not merely the problems of logs.

**Comment by blockloop** [comment]
> @crobert-1 However, if I configure the wal, **no metrics will be sent,** and I can just find this error log. I think it is not merely the problems of logs.

I can confirm the same problem. No metrics are sent and I see this "not found" log message.

**Comment by iblancasa** [comment]
@toughnoah @blockloop do you mean that, if you enable `wal`, the metrics are never sent?

**Comment by dashpole** [comment]
Might be related to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20875.  @ArthurSens will try to pick that back up

**Comment by ArthurSens** [comment]
I've taken some time to look at this today. One of my colleagues tried solving this on #20875, but it got stale, and he moved on to other things. I'm still wrapping my head around the problem, and from the previous PR I can see discussions around deadlocks.

After updating the WAL mutexes with [delock](https://github.com/ietxaniz/delock) and running the exporter, I got this:

```
./bin/otelcontribcol_darwin_arm64 --config config.yml 
2025-01-31T18:03:53.231-0300    info    service@v0.118.1-0.20250131104636-a737a48402e0/service.go:186   Setting up own telemetry...
2025-01-31T18:03:53.232-0300    info    service@v0.118.1-0.20250131104636-a737a48402e0/service.go:252   Starting otelcontribcol...      {"Version": "0.118.0-dev", "NumCPU": 12}
2025-01-31T18:03:53.232-0300    info    extensions/extensions.go:39     Starting extensions...
2025-01-31T18:03:53.233-0300    info    otlpreceiver@v0.118.1-0.20250131104636-a737a48402e0/otlp.go:112 Starting GRPC server    {"kind": "receiver", "name": "otlp", "data_type": "metrics", "endpoint": "localhost:4317"}
2025-01-31T18:03:53.233-0300    info    otlpreceiver@v0.118.1-0.20250131104636-a737a48402e0/otlp.go:169 Starting HTTP server    {"kind": "receiver", "name": "otlp", "data_type": "metrics", "endpoint": "localhost:4318"}
2025-01-31T18:03:53.234-0300    info    prometheusreceiver@v0.118.0/metrics_receiver.go:118     Starting discovery manager      {"kind": "receiver", "name": "prometheus", "data_type": "metrics"}
2025-01-31T18:03:53.236-0300    info    targetallocator/manager.go:184  Scrape job added        {"kind": "receiver", "name": "prometheus", "data_type": "metrics", "jobName": "otel-collector"}
2025-01-31T18:03:53.236-0300    info    service@v0.118.1-0.20250131104636-a737a48402e0/service.go:275   Everything is ready. Begin running and processing data.
2025-01-31T18:03:53.236-0300    info    prometheusreceiver@v0.118.0/metrics_receiver.go:187     Starting scrape manager {"kind": "receiver", "name": "prometheus", "data_type": "metrics"}
panic: 

        Deadlock detected




        * * * * * WRITE LOCK - 1 occurrences * * * * * * * * 
                github.com/ietxaniz/delock@v0.3.0/mutex.go:58 +0x3c
                github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter@v0.118.0/wal.go:336 +0x4c
                github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter@v0.118.0/wal.go:231 +0x15c
                github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter@v0.118.0/wal.go:174 +0xdc
                github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter@v0.118.0/wal.go:164 +0x1f4





goroutine 52 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter.(*prweWAL).persistToWAL(0x140015e0480, {0x1400115a460, 0x1, 0x0?})
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter@v0.118.0/wal.go:317 +0x270
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter.(*prwExporter).handleExport(0x140015c98c0, {0x10c3b4910, 0x140009e2e00}, 0x14001767890, {0x0, 0x0, 0x0})
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter@v0.118.0/exporter.go:257 +0xfc
```

This shows me that the code path `prwe.handleExport -> persistToWAL` is trying to acquire the lock, while it has already been acquired by another code path `prwe.Start -> turnOnWALIfEnabled -> run -> continuallyPopWALThenExport -> readPrompbFromWAL`

I'm working on the PR
