### ISSUE TITLE
Log: multiline concatnation

### ISSUE THREAD

**Issue by rockb1017** [open-telemetry/opentelemetry-collector-contrib#2655]
**Is your feature request related to a problem? Please describe.**
When a user is ingesting k8s container logs, user would need to specify multiline concat rules (either `startline_regex` or `endline_regex`) for each container differently. 
example of java stacktrace is here:
```
[2016-05-25 12:39:04,744][DEBUG][action.bulk              ] [Set] [***][3] failed to execute bulk item (index) index {[***][***][***], source[{***}}
MapperParsingException[Field name [events.created] cannot contain '.']
    at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:273)
    at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:218)
    at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parse(ObjectMapper.java:193)
    at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:305)
    at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:218)
    at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:139)
    at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:118)
    at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:99)
    at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:498)
    at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
    at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
    at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
    at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```
but in a container runtime, it would be something like this: (ie docker json log)
```
{"log":"[2016-05-25 12:39:04,744][DEBUG][action.bulk              ] [Set] [***][3] failed to execute bulk item (index) index {[***][***][***], source[{***}}\n","stream":"stdout","time":"2019-01-01T11:11:11.111111111Z"}
{"log":"MapperParsingException[Field name [events.created] cannot contain '.']\n","stream":"stdout","time":"2019-01-01T11:11:11.111111111Z"}
{"log":"    at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:273)\n","stream":"stdout","time":"2019-01-01T11:11:11.111111111Z"}
{"log":"    at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:218)
\n","stream":"stdout","time":"2019-01-01T11:11:11.111111111Z"}
{"log":"    at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parse(ObjectMapper.java:193)
\n","stream":"stdout","time":"2019-01-01T11:11:11.111111111Z"}
...
```
It is much easier for users to view this messages as one event instead of several separate events. 

**Describe the solution you'd like**
Add a processor for it. 
The way configure this processor would be like this:
```
processors:
  multiline_concat:
    split_by_attribute: container.uid
    rules: 
      - key: container.name
         match: *-java-backend
         startline_regex: "^DT:\s*\d{2,4}\-\d{2,4}\-\d{2,4} \d{2,4}\:\d{2,4}\:\d{2,4}\.\d{3,4}" 
      - key: pod.name
         match: *-my-app-*
         startline_regex: "^NEWLINE "
```

**Describe alternatives you've considered**
I thought of if it can be concatenated as it read from the source (if stanza file reader can handle it). 
but having this processor can be beneficial to apply this to other source of logs. 

**Additional context**
fluentd counter part plugin
https://github.com/fluent-plugins-nursery/fluent-plugin-concat

**Comment by rockb1017** [comment]
this `split_by_attribute` is what is missing in the `combine` operator from log library. https://github.com/open-telemetry/opentelemetry-log-collection/issues/276

**Comment by rockb1017** [comment]
Should i start with requirements and design doc first?

**Comment by radzikp** [comment]
Hi guys, is there any timeline to fix this issue? I am struggling with concatenation of java stacktraces and send them to splunk hec indexer to see a whole stack trace as a one event.

**Comment by atoulme** [comment]
We now support recombining logs with the recombine operator. Here is an example: https://github.com/signalfx/splunk-otel-collector/pull/2451
Please take a look at https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/logstransformprocessor and https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor to perform those recombinations.

**Comment by atoulme** [comment]
Closing - please reopen if more work is needed.
