### ISSUE TITLE
[receiver/sqlquery] Failing test TestOracleDBIntegrationMetrics

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#27577]
Suddenly started failing on Oct 9. Worth investigating why it started timing out.

Seen in https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6463050989/job/17545729982?pr=27572

```
2023/10/10 00:39:33 🚧 Waiting for container id 271c79dfc133 image: 5382324e-5a6b-47a4-965c-56a86fc2cdea:b05e0ab5-61fd-48e5-8e79-11b7a4e7dc4f. Waiting for: &{timeout:0xc000347738 PollInterval:100ms}
panic: test timed out after 6m0s
running tests:
	TestOracleDBIntegrationMetrics (5m29s)

goroutine 8336 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.20.8/x64/src/testing/testing.go:2241 +0x219
created by time.goFunc
	/opt/hostedtoolcache/go/1.20.8/x64/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive, 5 minutes]:
testing.(*T).Run(0xc000a56340, {0x2e0de73, 0x1e}, 0x2ea7510)
	/opt/hostedtoolcache/go/1.20.8/x64/src/testing/testing.go:1630 +0x82e
testing.runTests.func1(0x0?)
	/opt/hostedtoolcache/go/1.20.8/x64/src/testing/testing.go:2036 +0x8e
testing.tRunner(0xc000a56340, 0xc000b3fb48)
	/opt/hostedtoolcache/go/1.20.8/x64/src/testing/testing.go:1576 +0x217
testing.runTests(0xc0005a5220?, {0x46b64e0, 0x22, 0x22}, {0x1c?, 0x4a9c39?, 0x46ccea0?})
	/opt/hostedtoolcache/go/1.20.8/x64/src/testing/testing.go:2034 +0x87d
testing.(*M).Run(0xc0005a5220)
	/opt/hostedtoolcache/go/1.20.8/x64/src/testing/testing.go:1906 +0xb45
main.main()
	_testmain.go:113 +0x2ea

...
```

**Comment by dmitryax** [comment]
Looks like started constantly failing. Another case: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6463574003/job/17546960758?pr=27575

**Comment by crobert-1** [comment]
Related PR: #27578

**Comment by dmitryax** [comment]
> Related PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27578

That was an attempt to isolate the problem. Appeared to be not related

**Comment by crobert-1** [comment]
Related: #12332. Test setup requires pulling a pretty large docker image to run, which has been a frequent cause of timeouts.

**Comment by mx-psi** [comment]
This does not seem to have happened recently based on our automation for detecting broken tests. Closing.
