### ISSUE TITLE
[exporter/datasetexporter] DataSet exporter is crashing on NPE

### ISSUE THREAD

**Issue by martin-majlis-s1** [open-telemetry/opentelemetry-collector-contrib#27648]
### Component(s)

exporter/dataset

## Expected Result

DataSet exporter should not crash on NPE.

## Actual Result

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x1536c93]

goroutine 55 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter.updateWithPrefixedValues(0xc000661120?, {0xc010393b00, 0x36}, {0x2573be8, 0x1}, {0x0?, 0x0}, 0x7f271c3e6a10?)
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.85.0/datasetexporter.go:105 +0x73
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter.updateWithPrefixedValuesMap(0x1?, {0xc00ee887e0, 0x28}, {0x2573be8, 0x1}, 0xc000661208?, 0x3)
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.85.0/datasetexporter.go:92 +0xcc
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter.updateWithPrefixedValues(0xc000600000?, {0xc00ee887e0, 0x28}, {0x2573be8, 0x1}, {0x1bac520?, 0xc00e184420}, 0x0?)
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.85.0/datasetexporter.go:107 +0xf3
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter.updateWithPrefixedValuesArray(0x1?, {0xc00ee88780, 0x26}, {0x2573be8, 0x1}, {0xc0108085c0?, 0x1, 0x1bac520?}, 0x2)
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.85.0/datasetexporter.go:99 +0xa5
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter.updateWithPrefixedValues(0xc00e1a63e8?, {0xc00ee88780, 0x26}, {0x2573be8, 0x1}, {0x1abde20?, 0xc00e19e0d8}, 0x1bac520?)
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.85.0/datasetexporter.go:109 +0x148
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter.updateWithPrefixedValuesMap(0x1bac520?, {0xc00c9830c0, 0x19}, {0x2573be8, 0x1}, 0xc000661478?, 0x1)
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.85.0/datasetexporter.go:92 +0xcc
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter.updateWithPrefixedValues(0xc0006614f0?, {0xc00c9830c0, 0x19}, {0x2573be8, 0x1}, {0x1bac520?, 0xc00e1843f0}, 0xc00eebc101?)
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.85.0/datasetexporter.go:107 +0xf3
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter.updateWithPrefixedValuesMap(0x9f747b?, {0x0, 0x0}, {0x2573be8, 0x1}, 0x1c?, 0x0)
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.85.0/datasetexporter.go:92 +0xcc
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter.updateWithPrefixedValues(0x0?, {0x0, 0x0}, {0x2573be8, 0x1}, {0x1bac520?, 0xc00e184360}, 0x4?)
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.85.0/datasetexporter.go:107 +0xf3
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter.buildEventFromLog({0xc0108083c0?}, {0xc00d37a000?}, {0x3b35000?}, {0xc0007ec090, 0x28}, {0xe0?, 0x17?, 0x66?})
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.85.0/logs_exporter.go:225 +0x9d2
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter.(*DatasetExporter).consumeLogs(0xc0006c3440, {0x259e3b8?, 0xc00e184030?}, {0x3b35000?})
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.85.0/logs_exporter.go:252 +0x13b
```

### Collector version

v0.85.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by martin-majlis-s1** [comment]
I would say, that it's the correct format based on - https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-labels-via-comments

![Screenshot 2023-10-13 at 9 36 55](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/122797378/8d347387-514b-44c3-b4bd-6e67f761c915)

**Comment by martin-majlis-s1** [comment]
It's done by the job - https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/workflows/add-labels.yml - so it took some time. :)

**Comment by martin-majlis-s1** [comment]
This was closed in the PR - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27663
