### ISSUE TITLE
[receiver/windowsperfcounters] Failing unit test TestCreateMetricsReceiver on Windows

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#32524]
### Component(s)

receiver/windowsperfcounters

### Describe the issue you're reporting

[Failing CI/CD link](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8741566202/job/23987859102?pr=32518)

Failure output:
```
Running target 'test' in module 'receiver/windowsperfcountersreceiver' as part of group 'receiver-3'
C:/mingw64/bin/make --no-print-directory -C receiver/windowsperfcountersreceiver test
D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/gotestsum --rerun-fails=1 --packages="./..." -- -race -timeout 600s -parallel 4 --tags=""
∅  internal/metadata
✖  . (338ms)

=== Failed
ERROR rerun aborted because previous run had a suspected panic and some test may not have run
=== FAIL: . TestCreateMetricsReceiver (0.00s)
panic: invalid character(s) in type "nop/81187460-0dc4-426f-bfec-1201f4222a2b" [recovered]
	panic: invalid character(s) in type "nop/81187460-0dc4-426f-bfec-1201f4222a2b"

goroutine 36 [running]:
testing.tRunner.func1.2({0x140c60c00, 0xc00008e1c0})
	C:/hostedtoolcache/windows/go/1.21.9/x64/src/testing/testing.go:1545 +0x3f7
testing.tRunner.func1()
	C:/hostedtoolcache/windows/go/1.21.9/x64/src/testing/testing.go:1548 +0x716
panic({0x140c60c00?, 0xc00008e1c0?})
	C:/hostedtoolcache/windows/go/1.21.9/x64/src/runtime/panic.go:920 +0x270
go.opentelemetry.io/collector/component.MustNewType(...)
	C:/Users/runneradmin/go/pkg/mod/go.opentelemetry.io/collector/component@v0.98.1-0.20240416174005-d0f15e2463f8/config.go:156
go.opentelemetry.io/collector/receiver/scraperhelper.NewScraper({0xc000096090, 0x28}, 0xc00008e1a0, {0xc0000abb18, 0x2, 0xc000238210?})
	C:/Users/runneradmin/go/pkg/mod/go.opentelemetry.io/collector/receiver@v0.98.1-0.20240416174005-d0f15e2463f8/scraperhelper/scraper.go:70 +0x205
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/windowsperfcountersreceiver.createMetricsReceiver({0x18?, 0xc000070c00?}, {{{{0x140d5e445, 0x3}}, {0xc000238210, 0x24}}, {0xc000222400, {0x140eb6668, 0xc000218d20}, {0x140eb6690, ...}, ...}, ...}, ...)
	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/windowsperfcountersreceiver/factory_windows.go:27 +0x4e5
go.opentelemetry.io/collector/receiver.CreateMetricsFunc.CreateMetricsReceiver(...)
	C:/Users/runneradmin/go/pkg/mod/go.opentelemetry.io/collector/receiver@v0.98.1-0.20240416174005-d0f15e2463f8/receiver.go:134
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/windowsperfcountersreceiver.TestCreateMetricsReceiver(0x0?)
	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/windowsperfcountersreceiver/factory_windows_test.go:34 +0x529
testing.tRunner(0xc0000844e0, 0x140db29d8)
	C:/hostedtoolcache/windows/go/1.21.9/x64/src/testing/testing.go:1595 +0x262
created by testing.(*T).Run in goroutine 1
	C:/hostedtoolcache/windows/go/1.21.9/x64/src/testing/testing.go:1648 +0x846

=== FAIL: . TestLoadConfig (unknown)

DONE 6 tests, 2 failures in 3.823s
make[2]: *** [../../Makefile.Common:126: test] Error 3
make[1]: *** [Makefile:165: receiver/windowsperfcountersreceiver] Error 2
make[1]: *** Waiting for unfinished jobs....
✓  . (12.112s)

DONE 42 tests in 45.665s
make[1]: Leaving directory 'D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib'
make: *** [Makefile:113: gotest] Error 2
```

**Comment by dashpole** [comment]
cc @braydonk

**Comment by crobert-1** [comment]
I believe this is fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32518.

_We can reopen if we see more frequencies_
