### ISSUE TITLE
[receiver/mongodb] Failing integration test due to timeout

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#32658]
### Component(s)

receiver/mongodb

### Describe the issue you're reporting

[Failing CI/CD link](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8805449826/job/24168079553)

Failure output:
```
Running target 'mod-integration-test' in module 'receiver/mongodbreceiver' as part of group 'receiver-1'
make --no-print-directory -C receiver/mongodbreceiver mod-integration-test
go: downloading github.com/montanaflynn/stats v0.0.0-20171201202039-1bf9dbcd8cbe
running go integration test ./... in /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mongodbreceiver
/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/gotestsum --rerun-fails=1 --packages="./..." -- -race -timeout 360s -parallel 4 -tags=integration,"" -run=Integration
∅  internal/metadata (1.026s)
✖  . (6m0.065s)

=== Failed
=== FAIL: .  (0.00s)
panic: test timed out after 6m0s
running tests:
	TestIntegration (6m0s)
	TestIntegration/5.0 (5m41s)

goroutine 242 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:2259 +0x259
created by time.goFunc
	/opt/hostedtoolcache/go/1.21.9/x64/src/time/sleep.go:176 +0x45

goroutine 1 [chan receive, 6 minutes]:
testing.(*T).Run(0xc000007ba0, {0x17ca2c5, 0xf}, 0x182a4e0)
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:1649 +0x871
testing.runTests.func1(0x0?)
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:2054 +0x85
testing.tRunner(0xc000007ba0, 0xc00061f998)
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:1595 +0x262
testing.runTests(0xc00012eaa0?, {0x2355080, 0x14, 0x14}, {0xc00061fa68?, 0x448805?, 0x2362ea0?})
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:2052 +0x8ae
testing.(*M).Run(0xc00012eaa0)
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:1925 +0xcd8
go.uber.org/goleak.VerifyTestMain({0x1b1b460, 0xc00012eaa0}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/go.uber.org/goleak@v1.3.0/testmain.go:53 +0x65
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbreceiver.TestMain(...)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mongodbreceiver/generated_package_test.go:12
main.main()
	_testmain.go:87 +0x317

goroutine 22 [chan receive, 5 minutes]:
testing.(*T).Run(0xc000007d40, {0x17be7f2, 0x3}, 0xc0005d6160)
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:1649 +0x871
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbreceiver.TestIntegration(0x0?)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mongodbreceiver/integration_test.go:27 +0x11e
testing.tRunner(0xc000007d40, 0x182a4e0)
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:1595 +0x262
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:1648 +0x846

goroutine 185 [semacquire, 5 minutes]:
sync.runtime_Semacquire(0xc000370578?)
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc000370570)
	/opt/hostedtoolcache/go/1.21.9/x64/src/sync/waitgroup.go:116 +0xa5
github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal/scraperinttest.(*IntegrationTest).createContainers(0xc000540280, 0xc000222b60)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/coreinternal/scraperinttest/scraperint.go:162 +0x40f
github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal/scraperinttest.(*IntegrationTest).Run(0xc000540280, 0xc000222b60)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/coreinternal/scraperinttest/scraperint.go:67 +0x65
testing.tRunner(0xc000222b60, 0xc0005d6160)
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:1595 +0x262
created by testing.(*T).Run in goroutine 22
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:1648 +0x846

goroutine 161 [chan receive, 5 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1({0x1b2bbb8?, 0xc0000b61a8})
	/home/runner/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.30.0/reaper.go:358 +0xa0e
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect in goroutine 187
	/home/runner/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.30.0/reaper.go:323 +0x2ec
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbreceiver	360.065s

=== FAIL: . TestIntegration (unknown)
2024/04/23 18:38:24 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 24.0.9
  API Version: 1.43
  Operating System: Ubuntu 22.04.4 LTS
  Total Memory: 15981 MB
  Resolved Docker Host: unix:///var/run/docker.sock
  Resolved Docker Socket Path: /var/run/docker.sock
  Test SessionID: 59cdb2ed39bd6702c70012beb5d926d41a57dd885df78fff3af0662b23ba6317
  Test ProcessID: 32c33641-526a-47df-919e-3817885[293](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8805449826/job/24168079553#step:5:294)cf
2024/04/23 18:38:24 🐳 Creating container for image testcontainers/ryuk:0.7.0
2024/04/23 18:38:24 ✅ Container created: bb827d110db8
2024/04/23 18:38:24 🐳 Starting container: bb827d110db8
2024/04/23 18:38:24 ✅ Container started: bb827d110db8
2024/04/23 18:38:24 🚧 Waiting for container id bb827d110db8 image: testcontainers/ryuk:0.7.0. Waiting for: &{Port:8080/tcp timeout:<nil> PollInterval:100ms}
2024/04/23 18:38:25 🔔 Container is ready: bb827d110db8
time="2024-04-23T18:38:25Z" level=error msg="Tar: Can't stat file /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mongodbreceiver/testdata/integration to tar: lstat /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mongodbreceiver/testdata/integration//home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mongodbreceiver/testdata/integration/.dockerignore: no such file or directory"
2024/04/23 18:38:34 🐳 Creating container for image 
2024/04/23 18:38:34 ✅ Container created: 8eae464e0ce8
2024/04/23 18:38:34 🐳 Starting container: 8eae464e0ce8
2024/04/23 18:38:39 ✅ Container started: 8eae464e0ce8
2024/04/23 18:38:39 🚧 Waiting for container id 8eae464e0ce8 image: e334d9c0-8641-4b43-b2ec-14d12217f5a7:e88c[303](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8805449826/job/24168079553#step:5:304)e-09de-487c-a2ba-23e575fe6dbd. Waiting for: &{Port:27017 timeout:0xc000323748 PollInterval:100ms}
2024/04/23 18:38:39 🔔 Container is ready: 8eae464e0ce8
2024/04/23 18:38:42 🐳 Terminating container: 8eae464e0ce8
2024/04/23 18:38:42 🚫 Container terminated: 8eae464e0ce8
--- PASS: TestIntegration/4.0 (19.16s)
time="2024-04-23T18:38:43Z" level=error msg="Tar: Can't stat file /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mongodbreceiver/testdata/integration to tar: lstat /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mongodbreceiver/testdata/integration//home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mongodbreceiver/testdata/integration/.dockerignore: no such file or directory"
    scraperint.go:145: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/coreinternal/scraperinttest/scraperint.go:145
        	            				/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/asm_amd64.s:1650
        	Error:      	Condition never satisfied
        	Test:       	TestIntegration/5.0
        	Messages:   	create container timeout: <nil>
2024/04/23 18:43:50 🐳 Creating container for image 
2024/04/23 18:43:50 ✅ Container created: 26449defcc6c
2024/04/23 18:43:50 🐳 Starting container: 26449defcc6c
2024/04/23 18:43:55 ✅ Container started: 26449defcc6c
2024/04/23 18:43:55 🚧 Waiting for container id 26449defcc6c image: da4c017a-8e2d-4e99-8a48-f61ab7a216d1:4a5c9481-4f58-438e-923e-17d5f7efd398. Waiting for: &{Port:27017 timeout:0xc000370438 PollInterval:100ms}
2024/04/23 18:43:55 🔔 Container is ready: 26449defcc6c

=== FAIL: . TestIntegration/5.0 (unknown)
time="2024-04-23T18:38:43Z" level=error msg="Tar: Can't stat file /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mongodbreceiver/testdata/integration to tar: lstat /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mongodbreceiver/testdata/integration//home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mongodbreceiver/testdata/integration/.dockerignore: no such file or directory"
    scraperint.go:145: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/coreinternal/scraperinttest/scraperint.go:145
        	            				/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/asm_amd64.s:1650
        	Error:      	Condition never satisfied
        	Test:       	TestIntegration/5.0
        	Messages:   	create container timeout: <nil>
2024/04/23 18:43:50 🐳 Creating container for image 
2024/04/23 18:43:50 ✅ Container created: 26449defcc6c
2024/04/23 18:43:50 🐳 Starting container: 26449defcc6c
2024/04/23 18:43:55 ✅ Container started: 26449defcc6c
2024/04/23 18:43:55 🚧 Waiting for container id 26449defcc6c image: da4c017a-8e2d-4e99-8a48-f61ab7a216d1:4a5c9481-4f58-438e-923e-17d5f7efd398. Waiting for: &{Port:27017 timeout:0xc000370438 PollInterval:100ms}
2024/04/23 18:43:55 🔔 Container is ready: 26449defcc6c

DONE 3 tests, 3 failures in 367.192s
ERROR rerun aborted because previous run had a suspected panic and some test may not have run
make[2]: *** [../../Makefile.Common:142: mod-integration-test] Error 3
make[1]: *** [Makefile:169: receiver/mongodbreceiver] Error 2
make: *** [Makefile:126: gointegration-test] Error 2
make[1]: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib'
```

**Comment by crobert-1** [comment]
This looks similar to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32656 as one of the stack traces is showing that the test is looking for a `.dockerignore` file but can't find it.
