### ISSUE TITLE
[Weekly report] Action failed due to message body being too long

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#32655]
### Describe the issue you're reporting

[Failed CI/CD link](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8793329871)

Failure output:
```
Run actions/github-script@v7
{
  "msg": "running..."
}
{
  "msg": "fetching issues",
  "queryParams": {
    "owner": "open-telemetry",
    "repo": "opentelemetry-collector-contrib",
    "state": "open",
    "per_page": 100,
    "page": 1,
    "labels": "needs triage"
  }
}
{
  "msg": "fetching issues",
  "queryParams": {
    "owner": "open-telemetry",
    "repo": "opentelemetry-collector-contrib",
    "state": "open",
    "per_page": 100,
    "page": 1,
    "labels": "ready to merge"
  }
}
{
  "msg": "fetching issues",
  "queryParams": {
    "owner": "open-telemetry",
    "repo": "opentelemetry-collector-contrib",
    "state": "open",
    "per_page": 100,
    "page": 1,
    "labels": "Sponsor Needed"
  }
}
{
  "msg": "previous issue",
  "created_at": "2024-03-26T01:21:23Z",
  "id": 2207044797,
  "url": "https://api.github.com/repos/open-telemetry/opentelemetry-collector-contrib/issues/31947",
  "title": "Weekly Report: 2024-03-19 - 2024-03-26"
}
RequestError [HttpError]: Validation Failed: {"resource":"Issue","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}
    at /home/runner/work/_actions/actions/github-script/v7/dist/index.js:9537:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestWithGraphqlErrorHandling (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:9276:20)
    at async Job.doExecute (/home/runner/work/_actions/actions/github-script/v7/dist/index.js:10275:18) {
  status: 422,
  response: {
    url: 'https://api.github.com/repos/open-telemetry/opentelemetry-collector-contrib/issues',
    status: 422,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-length': '234',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Tue, 23 Apr 2024 01:23:24 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-github-permissions': 'issues=write',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '7C82:E35A3:FAAEAD:1755A20:66270D8B',
      'x-ratelimit-limit': '15000',
      'x-ratelimit-remaining': '14948',
      'x-ratelimit-reset': '17[13](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8793329871/job/24131018470#step:4:14)838513',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '52',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Validation Failed',
      errors: [Array],
      documentation_url: 'https://docs.github.com/rest/issues/issues#create-an-issue'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/open-telemetry/opentelemetry-collector-contrib/issues',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'actions/github-script octokit-core.js/5.0.1 Node.js/20.8.1 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"title":"Weekly Report: 2024-04-16 - 2024-04-23","body":"## Format\\n- `{CATEGORY}: {COUNT} ({CHANGE_FROM_PREVIOUS_WEEK})`\\n## Issues Report\\n<ul>\\n\\n<li> New issues: 71 (35)\\n<details>\\n    <summary> Issues </summary>\\n\\n- [ ] [extension/oauth2clientauth] Enable dynamically reading ClientID and ClientSecret from command ([#32602](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32602))\\n- [ ] [receiver/cloudflare] TestReceiverTLSIntegration integration test failing ([#32600](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32600))\\n- [ ] Support a configurable default agent configuration to be implemented by OpAMP supervisor ([#32598](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32598))\\n- [ ] [k8sattributesprocessor]  The sources.from types add enum metric_attribute ([#32596](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32596))\\n- [ ] [pkg/ottl] Support for grok patterns ([#32593](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32593))\\n- [ ] received message after decompression larger than max (4331797 vs. 4194304) ([#32590](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32590))\\n- [ ] [exporter/elasticsearch] Make retry statuses configurable and default to 429 only ([#32584](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32584))\\n- [ ] [processor/groupbytrace] Leaked goroutine in doWithTimeout ([#32572](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32572))\\n- [ ] Add integration test for haproxyreceiver ([#32569](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32569))\\n- [ ] otlpjsonfilereceiver: support compressed files from fileexporter ([#32565](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32565))\\n- [ ] Updating the Mongodb configuration on Readme ([#32561](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32561))\\n- [ ] [receiver/vcenter] No Inventory Path Resource Attribute for VM Resources with vApp Parent ([#32557](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32557))\\n- [ ] Some data couldn\'t be associated with k8s metadata when the agent was just started. ([#32556](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32556))\\n- [ ] Prometheus receiver fails on federate endpoint when job and instance labels are missing ([#32555](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32555))\\n- [ ] [awss3exporter] Use dynamic values ​​such as resource.attributes for file prefix, s3 prefix, etc. ([#32553](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32553))\\n- [ ] [exporter/prometheus] does not show metrics from otlp receiver ([#32552](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32552))\\n- [ ] Memory leak problem with Opentelemetry Collector and tailsampling ([#32551](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32551))\\n- [ ] [receiver/vcenter] Host Resource Should Not Have `vcenter.cluster.name` Attribute if Standalone (Not Clustered) ([#32548](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32548))\\n- [ ] sqlqueryreceiver - create one metric per row returned ([#32546](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32546))\\n- [ ] splunkhec exporter: Allows users to enable exporter batching via config ([#32545](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32545))\\n- [ ] [receiver/mongodbatlas] Integration tests failing ([#32543](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32543))\\n- [ ] Supervisor: exporters.debug.* not valid cfg  ([#32541](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32541))\\n- [ ] Updating builder causes make genotelcontribcol failure ([#32539](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32539))\\n- [ ] [receiver/hostmetrics] Process scrape integration test failing ([#32536](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32536))\\n- [ ] [receiver/vcenter] No Cluster Attribute on Clustered Resource Pool Resources ([#32535](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32535))\\n- [ ] [exporter/splunkhec] Integration tests failing ([#32534](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32534))\\n- [ ] [exporter/dataset] Integration stress tests failing ([#32533](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32533))\\n- [ ] [receiver/cloudflare] Integration tests failing to find expected files ([#32532](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32532))\\n- [ ] [receiver/vcenterreceiver] No attributes to define datacenter ([#32531](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32531))\\n- [ ] [exporter/clickhouse] Integration test hits a panic ([#32530](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32530))\\n- [ ] [receiver/windowsperfcounters] Failing unit test TestCreateMetricsReceiver on Windows ([#32524](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32524))\\n- [ ] [exporter/prometheus] Support Prometheus Created Timestamp feature ([#32521](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32521))\\n- [ ] [receiver/sqlserver] Failing query unit tests on Windows ([#32519](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32519))\\n- [ ] Hangfire: Span and Trace Id should be added to hangfire job parameters. ([#32517](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32517))\\n- [ ] read multiple resource attributes from a single k8s attribute or label ([#32515](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32515))\\n- [ ] prometheus exporter precision error with histogram bucket  ([#325[14](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8793329871/job/24131018470#step:4:15)](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32514))\\n- [ ] [exporter/loadbalancing] Add the ability to load balance by Metric stream ID ([#32513](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32513))\\n- [ ] [exporter/prometheusremotewrite] Permanent error: Permanent error: context deadline exceeded ([#32511](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32511))\\n- [ ] [receiver/windowsperfcounters] Unit tests are not running on CI ([#32508](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32508))\\n- [ ] [receiver/syslog] syslog receiver is missing \\"time/tzdata\\" ([#32506](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32506))\\n- [ ] New component: GitHub Actions Logs Receiver ([#32505](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32505))\\n- [ ] [exporter/elasticsearch] Add micro/macro benchmarks to reason about improvement PRs ([#32504](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32504))\\n- [ ] [exporter/loki] Loki v3.0\'s generated `service_name` is invalid when `service.namespace` is defined ([#32497](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32497))\\n- [ ] [pkg/ottl] Decode function for decoding []byte based on a configured text encoding ([#32493](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32493))\\n- [ ] Update weekly report to include waiting-for-code-owners ([#32490](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32490))\\n- [ ] Update PR template to ensure issues are closed automatically ([#32489](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32489))\\n- [ ] Update module github.com/prometheus/prometheus to v0.51.2 causes CI failures ([#32488](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32488))\\n- [ ] [receiver/chronyreceiver] Receiver is not scraping dial unixgram /var/run/chrony/chronyd.sock ([#32487](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32487))\\n- [ ] Add template for unmaintained component issues ([#32485](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32485))\\n- [ ] Resource attribute \\"service.instance.id\\" is converted to label \\"instance\\", conflicting with auto-generated prometheus label ([#32484](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32484))\\n- [ ] loadbalancingexporter makes the collector accept data to produce a reject otelcol_receiver_refused_spans ([#32482](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32482))\\n- [ ] [azuremonitorexporter] Duplicate logs on Kubernetes ([#32480](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32480))\\n- [ ] [processor/k8sattributes] Metrics sent by a very short-lived CronJob get labels from another CronJob started at the same time, or no labels at all ([#32476](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32476))\\n- [ ] [pkg/stanza/fileconsumer] TestExcludeOlderThanFilter/file_not_present test failing on Windows ([#32464](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32464))\\n- [ ] [pkg/ottl] Ability to discard/sample exemplars ([#32460](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32460))\\n- [ ] [k8scluster] add k8s.container.status_waiting_reason metric ([#32457](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32457))\\n- [ ] Collector fails to restart with persistent queue and health check enabled ([#32456](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32456))\\n- [ ] [cmd/opampsupervisor] use nop components during bootstrapping ([#32455](https://github.c'... 765[22](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8793329871/job/24131018470#step:4:23) more characters,
    request: {
      agent: [Agent],
      fetch: [Function: proxyFetch],
      retries: 3,
      hook: [Function: bound bound register],
      retryCount: 3
    }
  }
}
Error: Unhandled error: HttpError: Validation Failed: {"resource":"Issue","code":"custom","field":"body","message":"body is too long (maximum is 655[36](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8793329871/job/24131018470#step:4:37) characters)"}
```

**Comment by crobert-1** [comment]
I also see in the failure that the previous issue is set incorrectly. The previous weekly report should be https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32407, but it's showing https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31947 instead.

**Comment by crobert-1** [comment]
I'm not sure if there's anything we can do here other than removing some of the contents from the created issue. I assume the best option is to remove the issue titles in the issues needing triage and new issues in the description. This is where most characters are coming from. We'd lose some helpful information there but I don't think it's a deal breaker.

**Comment by crobert-1** [comment]
+1 freq: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8887820197

**Comment by crobert-1** [comment]
+1 freq: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8978193947
