### ISSUE TITLE
sapmexporter crashing the otel-collector when passing the signalfx access token

### ISSUE THREAD

**Issue by andreas-ahman** [open-telemetry/opentelemetry-collector-contrib#3279]
**Describe the bug**

When passing the `com.splunk.signalfx.access_token` using either the splunk-otel-java or official agent the sapm exporter crashes the collector.

**Steps to reproduce**

I built this package https://github.com/spring-projects/spring-petclinic and use the splunk-otel-java and also https://github.com/open-telemetry/opentelemetry-java-instrumentation both produces the same result

**What did you expect to see?**

Traces successfully sent to signalfx.

**What did you see instead?**

```
panic: runtime error: index out of range [13] with length 13

goroutine 131 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/sapmexporter.filterTokenFromProcess(0xc033f3e820)
	/home/circleci/project/exporter/sapmexporter/exporter.go:157 +0x294
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/sapmexporter.filterToken(0xc0005ea560, 0x1, 0x1)
	/home/circleci/project/exporter/sapmexporter/exporter.go:148 +0x3c
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/sapmexporter.(*sapmExporter).pushTraceData(0xc00076aae0, 0x42ab700, 0xc00011b680, 0xc000114600, 0x3bb0ae0, 0xc0000ad6b8, 0x49978b)
	/home/circleci/project/exporter/sapmexporter/exporter.go:119 +0xcd
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesRequest).export(0xc033f1c220, 0x42ab700, 0xc00011b680, 0x42ab700, 0xc00011b680, 0xc000830ad0)
	/home/circleci/go/pkg/mod/go.opentelemetry.io/collector@v0.22.0/exporter/exporterhelper/tracehelper.go:53 +0x47
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0xc0007448b0, 0x42c3140, 0xc033f1c220, 0x0, 0x0, 0x0)
	/home/circleci/go/pkg/mod/go.opentelemetry.io/collector@v0.22.0/exporter/exporterhelper/common.go:217 +0x92
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send(0xc0006d7da0, 0x42c3140, 0xc033f1c220, 0x3a5d357, 0x7, 0x42ab740)
	/home/circleci/go/pkg/mod/go.opentelemetry.io/collector@v0.22.0/exporter/exporterhelper/queued_retry.go:232 +0x281
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send(0xc00076ae00, 0x42c3140, 0xc033f1c220, 0x42c3140, 0xc033f1c220, 0x0)
	/home/circleci/go/pkg/mod/go.opentelemetry.io/collector@v0.22.0/exporter/exporterhelper/tracehelper.go:114 +0xcd
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1(0x3584860, 0xc033f1c220)
	/home/circleci/go/pkg/mod/go.opentelemetry.io/collector@v0.22.0/exporter/exporterhelper/queued_retry.go:133 +0x75
github.com/jaegertracing/jaeger/pkg/queue.ConsumerFunc.Consume(0xc0007802f0, 0x3584860, 0xc033f1c220)
	/home/circleci/go/pkg/mod/github.com/jaegertracing/jaeger@v1.22.0/pkg/queue/bounded_queue.go:104 +0x3a
github.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumersWithFactory.func1(0xc000744920, 0xc0007840f0)
	/home/circleci/go/pkg/mod/github.com/jaegertracing/jaeger@v1.22.0/pkg/queue/bounded_queue.go:83 +0xe9
created by github.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumersWithFactory
	/home/circleci/go/pkg/mod/github.com/jaegertracing/jaeger@v1.22.0/pkg/queue/bounded_queue.go:73 +0xc0
```

**What version did you use?**

Collector 0.22.0
Java agent both 0.10.0 and 0.9.0

**Comment by bogdandrutu** [comment]
@andreas-ahman thanks for reporting this issue, the PR to fix this is up for review, and will be included in v0.26.0
