### ISSUE TITLE
[receiver/haproxy] Unit test timing out

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#32877]
### Component(s)

receiver/haproxy

### Describe the issue you're reporting

[Failing CI/CD link](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8974357721/job/24646616822)

Failure output:
```
Running target 'test-with-cover' in module 'receiver/haproxyreceiver' as part of group 'receiver-1'
make --no-print-directory -C receiver/haproxyreceiver test-with-cover
mkdir -p /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/coverage/unit
/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/gotestsum --rerun-fails=1 --packages="./..." -- -race -timeout 600s -parallel 4 --tags="" -cover -covermode=atomic -args -test.gocoverdir="/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/coverage/unit"
✓  internal/metadata (1.111s) (coverage: 94.2% of statements)
✖  . (10m0.072s)

=== Failed
=== FAIL: .  (0.00s)
panic: test timed out after 10m0s
running tests:
	Test_scraper_readStatsWithIncompleteValues (9m58s)

goroutine 50 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:2259 +0x259
created by time.goFunc
	/opt/hostedtoolcache/go/1.21.9/x64/src/time/sleep.go:176 +0x45

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000ef6c0, {0x1342c4c, 0x2a}, 0x1377d18)
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:1649 +0x871
testing.runTests.func1(0x0?)
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:2054 +0x85
testing.tRunner(0xc0000ef6c0, 0xc00029f998)
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:1595 +0x262
testing.runTests(0xc0001f90e0?, {0x1b22d40, 0x6, 0x6}, {0xc00029fa68?, 0x448ac5?, 0x1b31b00?})
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:2052 +0x8ae
testing.(*M).Run(0xc0001f90e0)
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:1925 +0xcd8
go.uber.org/goleak.VerifyTestMain({0x14a8de0, 0xc0001f90e0}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/go.uber.org/goleak@v1.3.0/testmain.go:53 +0x65
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/haproxyreceiver.TestMain(...)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/haproxyreceiver/generated_package_test.go:12
main.main()
	_testmain.go:93 +0x337

goroutine 16 [runnable]:
gopkg.in/yaml%2ev3.skip(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/scannerc.go:513 +0x2fc
gopkg.in/yaml%2ev3.yaml_parser_scan_plain_scalar(0xc000100400, 0xc00019ff98)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/scannerc.go:2791 +0x1f65
gopkg.in/yaml%2ev3.yaml_parser_fetch_plain_scalar(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/scannerc.go:1527 +0x9d
gopkg.in/yaml%2ev3.yaml_parser_fetch_next_token(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/scannerc.go:874 +0x246c
gopkg.in/yaml%2ev3.yaml_parser_fetch_more_tokens(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/scannerc.go:[67](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8974357721/job/24646616822#step:9:68)7 +0x45c
gopkg.in/yaml%2ev3.peek_token(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/parserc.go:69 +0x4e
gopkg.in/yaml%2ev3.yaml_parser_parse_block_mapping_key(0xc000100400, 0xc0001006b0, 0x1)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/parserc.go:847 +0x745
gopkg.in/yaml%2ev3.yaml_parser_state_machine(0xc000100400, 0x4afb31?)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/parserc.go:188 +0x1d5
gopkg.in/yaml%2ev3.yaml_parser_parse(0xc000100400, 0xc0001006b0)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/parserc.go:129 +0xee
gopkg.in/yaml%2ev3.(*parser).peek(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:106 +0x65
gopkg.in/yaml%2ev3.(*parser).mapping(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:279 +0x274
gopkg.in/yaml%2ev3.(*parser).parse(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:155 +0x188
gopkg.in/yaml%2ev3.(*parser).parseChild(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:197
gopkg.in/yaml%2ev3.(*parser).mapping(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:288 +0x56c
gopkg.in/yaml%2ev3.(*parser).parse(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:155 +0x188
gopkg.in/yaml%2ev3.(*parser).parseChild(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:197
gopkg.in/yaml%2ev3.(*parser).sequence(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:262 +0x296
gopkg.in/yaml%2ev3.(*parser).parse(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:157 +0x165
gopkg.in/yaml%2ev3.(*parser).parseChild(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:197
gopkg.in/yaml%2ev3.(*parser).mapping(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:288 +0x56c
gopkg.in/yaml%2ev3.(*parser).parse(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:155 +0x188
gopkg.in/yaml%2ev3.(*parser).parseChild(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:197
gopkg.in/yaml%2ev3.(*parser).sequence(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:262 +0x296
gopkg.in/yaml%2ev3.(*parser).parse(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:157 +0x165
gopkg.in/yaml%2ev3.(*parser).parseChild(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:197
gopkg.in/yaml%2ev3.(*parser).mapping(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:288 +0x56c
gopkg.in/yaml%2ev3.(*parser).parse(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:155 +0x188
gopkg.in/yaml%2ev3.(*parser).parseChild(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:197
gopkg.in/yaml%2ev3.(*parser).sequence(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:262 +0x296
gopkg.in/yaml%2ev3.(*parser).parse(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:157 +0x165
gopkg.in/yaml%2ev3.(*parser).parseChild(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:197
gopkg.in/yaml%2ev3.(*parser).mapping(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:288 +0x56c
gopkg.in/yaml%2ev3.(*parser).parse(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:155 +0x188
gopkg.in/yaml%2ev3.(*parser).parseChild(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:197
gopkg.in/yaml%2ev3.(*parser).document(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:206 +0xc6
gopkg.in/yaml%2ev3.(*parser).parse(0xc000100400)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:159 +0x111
gopkg.in/yaml%2ev3.unmarshal({0xc000150000, 0x84e3, 0x84e4}, {0x11b1180, 0xc000306400}, 0x28?)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:161 +0x5d5
gopkg.in/yaml%2ev3.Unmarshal(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:89
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/golden.ReadMetrics({0xc0003c6030, 0x24})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/pkg/golden/golden.go:27 +0x159
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/haproxyreceiver.Test_scraper_readStatsWithIncompleteValues(0xc0002a7040)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/haproxyreceiver/scraper_test.go:101 +0x765
testing.tRunner(0xc0002a7040, 0x1377d18)
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:1595 +0x262
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.21.9/x64/src/testing/testing.go:1648 +0x846
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/haproxyreceiver	600.072s

=== FAIL: . Test_scraper_readStatsWithIncompleteValues (unknown)
coverage: [69](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8974357721/job/24646616822#step:9:70).0% of statements

DONE 26 tests, 2 failures in 601.587s
ERROR rerun aborted because previous run had a suspected panic and some test may not have run
make[2]: *** [../../Makefile.Common:131: test-with-cover] Error 3
make[1]: *** [Makefile:1[76](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8974357721/job/24646616822#step:9:77): receiver/haproxyreceiver] Error 2
make: *** [Makefile:128: gotest-with-cover] Error 2
make[1]: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib'
Error: Process completed with exit code 2.
```

**Comment by crobert-1** [comment]
+1 freq: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8971538835/job/24637585044

**Comment by crobert-1** [comment]
+1 freq: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8970851164/job/24635708550

**Comment by crobert-1** [comment]
This failure has been happening pretty frequently (not every time though) for at least the 24 hours.

+1 freq: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8944741227/job/24572359344

**Comment by crobert-1** [comment]
+1 freq: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8945845939/job/24575544679

**Comment by crobert-1** [comment]
+1 freq: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8944359609/job/24571142115
