### ISSUE TITLE
deltatocumulativeprocessor segfaults at stream limit

### ISSUE THREAD

**Issue by sh0rez** [open-telemetry/opentelemetry-collector-contrib#33285]
### Component(s)

processor/deltatocumulative

## Description

When hitting its stream limit, the deltatocumulativeprocessor segfaults

## Steps to Reproduce

- Set a stream limit (e.g. 10000)
- Have more non-stale streams than limit, so nothing evicts
- Panic

## Expected Result

Excess samples are dropped and recorded as metric

## Actual Result

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xac75c4]

goroutine 7 [running]:
go.opentelemetry.io/collector/pdata/pmetric.NumberDataPoint.Attributes(...)
	/go/pkg/mod/go.opentelemetry.io/collector/pdata@v1.8.0/pmetric/generated_numberdatapoint.go:51
go.opentelemetry.io/collector/pdata/pmetric.NumberDataPoint.CopyTo({0x0?, 0x0?}, {0xc004a74360?, 0xc004618bd8?})
	/go/pkg/mod/go.opentelemetry.io/collector/pdata@v1.8.0/pmetric/generated_numberdatapoint.go:133 +0x44
github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor/internal/data.Number.CopyTo({{0x0?, 0x0?}}, {{0xc004a74360?, 0xc004618bd8?}})
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor@v0.101.0/internal/data/data.go:37 +0x27
github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor/internal/streams.Aggregate[...].func1({{0xc004a74360?, 0xc004618bd8?}})
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor@v0.101.0/internal/streams/data.go:41 +0x198
github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor/internal/streams.Samples[...].func1()
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor@v0.101.0/internal/streams/data.go:22 +0x16e
github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor/internal/streams.Aggregate[...]({0x1436f00, 0xc003bad110}, {0x142cae0, 0xc000392a90})
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor@v0.101.0/internal/streams/data.go:35 +0xce
github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor.(*Processor).ConsumeMetrics.func1({{0xc000d8abb8, 0xc004618bd8}, {0xc000190070, 0xc004618bd8}, {0xc004a74300, 0xc004618bd8}})
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor@v0.101.0/processor.go:141 +0x205
github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor.(*Processor).ConsumeMetrics.Each.func2({{0xc000d8abb8, 0xc004618bd8}, {0xc000190070, 0xc004618bd8}, {0xc004a74300, 0xc004618bd8}})
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor@v0.101.0/internal/metrics/util.go:22 +0x43
github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor/internal/metrics.Filter.func1.1.1({0xc004a74300?, 0xc004618bd8?})
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor@v0.101.0/internal/metrics/util.go:12 +0x85
go.opentelemetry.io/collector/pdata/pmetric.MetricSlice.RemoveIf({0xc0001900b0?, 0xc004618bd8?}, 0xc0019e5ba8)
	/go/pkg/mod/go.opentelemetry.io/collector/pdata@v1.8.0/pmetric/generated_metricslice.go:111 +0x75
github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor/internal/metrics.Filter.func1.1({0xc000190070?, 0xc004618bd8?})
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor@v0.101.0/internal/metrics/util.go:11 +0x6e
go.opentelemetry.io/collector/pdata/pmetric.ScopeMetricsSlice.RemoveIf({0xc000d8abd8?, 0xc004618bd8?}, 0xc0019e5c40)
	/go/pkg/mod/go.opentelemetry.io/collector/pdata@v1.8.0/pmetric/generated_scopemetricsslice.go:111 +0x75
github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor/internal/metrics.Filter.func1({0xc000d8aba0?, 0xc004618bd8?})
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor@v0.101.0/internal/metrics/util.go:10 +0x56
go.opentelemetry.io/collector/pdata/pmetric.ResourceMetricsSlice.RemoveIf({0xc0035018f0?, 0xc004618bd8?}, 0xc0019e5cc8)
	/go/pkg/mod/go.opentelemetry.io/collector/pdata@v1.8.0/pmetric/generated_resourcemetricsslice.go:111 +0x75
github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor/internal/metrics.Filter({0xc0035018f0?, 0xc004618bd8?}, 0x5?)
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor@v0.101.0/internal/metrics/util.go:9 +0x3b
github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor/internal/metrics.Each(...)
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor@v0.101.0/internal/metrics/util.go:21
github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor.(*Processor).ConsumeMetrics(0xc0003ae700, {0x143bf10, 0xc000387ef0}, {0xc0035018f0?, 0xc004618bd8?})
	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor@v0.101.0/processor.go:136 +0x159
go.opentelemetry.io/collector/processor/batchprocessor.(*batchMetrics).export(0xc00039e8c0, {0x143bf10, 0xc000387ef0}, 0x2?, 0x0)
	/go/pkg/mod/go.opentelemetry.io/collector/processor/batchprocessor@v0.101.0/batch_processor.go:449 +0x175
go.opentelemetry.io/collector/processor/batchprocessor.(*shard).sendItems(0xc00039e900, 0x2)
	/go/pkg/mod/go.opentelemetry.io/collector/processor/batchprocessor@v0.101.0/batch_processor.go:261 +0x56
go.opentelemetry.io/collector/processor/batchprocessor.(*shard).processItem(0xc00039e900, {0x121b2e0?, 0xc00105fa50?})
	/go/pkg/mod/go.opentelemetry.io/collector/processor/batchprocessor@v0.101.0/batch_processor.go:235 +0x45
go.opentelemetry.io/collector/processor/batchprocessor.(*shard).startLoop(0xc00039e900)
	/go/pkg/mod/go.opentelemetry.io/collector/processor/batchprocessor@v0.101.0/batch_processor.go:220 +0x16d
created by go.opentelemetry.io/collector/processor/batchprocessor.(*shard).start in goroutine 1
	/go/pkg/mod/go.opentelemetry.io/collector/processor/batchprocessor@v0.101.0/batch_processor.go:184 +0x65
```

### Collector version

821c864db937ab7170e6c61bc096ead9cf405311

**Comment by crobert-1** [comment]
_Removing `needs triage` as it was filed by a code owner with a PR to fix._
