### ISSUE TITLE
[connector/servicegraph] Broken test: TestConnectorConsume/incomplete_traces_with_virtual_server_span

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector-contrib#34792]
### Component(s)

connector/servicegraph

### Describe the issue you're reporting

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/10493207856/job/29066610265?pr=34791#step:6:377

```
=== FAIL: . TestConnectorConsume/incomplete_traces_with_virtual_server_span (0.00s)
    logger.go:146: 2024-08-21T16:00:30.028Z	INFO	Started servicegraphconnector

=== FAIL: . TestConnectorConsume (0.02s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 20 [running]:
testing.tRunner.func1.2({0x14143aa00, 0xc0002542a0})
	C:/hostedtoolcache/windows/go/1.22.6/x64/src/testing/testing.go:1631 +0x3f7
testing.tRunner.func1()
	C:/hostedtoolcache/windows/go/1.22.6/x64/src/testing/testing.go:1634 +0x6b6
panic({0x14143aa00?, 0xc0002542a0?})
	C:/hostedtoolcache/windows/go/1.22.6/x64/src/runtime/panic.go:770 +0x132
go.opentelemetry.io/collector/pdata/pmetric.MetricSlice.At(...)
	C:/Users/runneradmin/go/pkg/mod/go.opentelemetry.io/collector/pdata@v1.13.1-0.20240816132030-9fd84668bb02/pmetric/generated_metricslice.go:56
github.com/open-telemetry/opentelemetry-collector-contrib/connector/servicegraphconnector.TestConnectorConsume.func2(0xc000154340, {0xc000009050?, 0xc00016a15c?})
	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/connector/servicegraphconnector/connector_test.go:120 +0x2a7
github.com/open-telemetry/opentelemetry-collector-contrib/connector/servicegraphconnector.TestConnectorConsume.func5(0xc000154340)
	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/connector/servicegraphconnector/connector_test.go:189 +0x482
testing.tRunner(0xc000154340, 0xc000124dc0)
	C:/hostedtoolcache/windows/go/1.22.6/x64/src/testing/testing.go:1689 +0x21f
created by testing.(*T).Run in goroutine 14
	C:/hostedtoolcache/windows/go/1.22.6/x64/src/testing/testing.go:1742 +0x826

DONE 13 tests, 2 failures in 27.027s
```

**Comment by crobert-1** [comment]
> /label os:windows

I've filed https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34796 to fix the bug that caused no label to be added here.

**Comment by pjanotti** [comment]
Although it is another timing issue when running on Windows it fails consistently on my box, changed the title to reflect that. I will see if I can get a fix quickly.

**Comment by crobert-1** [comment]
+1 freq: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/10496873414/job/29078467107?pr=34794
