### ISSUE TITLE
[dotnetdiagnosticsreceiver] Errors and shuts down after running for a few seconds

### ISSUE THREAD

**Issue by alanwest** [open-telemetry/opentelemetry-collector-contrib#3535]
**Describe the bug**

The [dotnetdiagnosticsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/dotnetdiagnosticsreceiver) errors and shuts down after running for a few seconds.

I've seen a couple different errors occur:

```
2021-05-25T16:23:01.150-0700	error	dotnetdiagnosticsreceiver/receiver.go:98	parseAll error	{"kind": "receiver", "name": "dotnet_diagnostics", "error": "next byte assertion failed, expected 6, got 5"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver.(*receiver).Start.func1
	/Users/awest/github/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver/receiver.go:98
```

```
2021-05-25T16:25:11.323-0700	error	dotnetdiagnosticsreceiver/receiver.go:98	parseAll error	{"kind": "receiver", "name": "dotnet_diagnostics", "error": "CompressedInt32 is too long"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver.(*receiver).Start.func1
	/Users/awest/github/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver/receiver.go:98
```

**Steps to reproduce**

1. Create and run a .NET app

```shell
mkdir testapp
cd testapp
dotnet new webapi
dotnet run
```

2. Start the collector using the following config - replacing the pid with the dotnet process started:

```yaml
receivers:
  dotnet_diagnostics:
    pid: <pid of dotnet process>

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [dotnet_diagnostics]
      exporters: [logging]
```

**What version did you use?**
Version: `2cb31f4`

**Environment**
`dotnet --info` output:

```
NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.103/

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a
```

@pjanotti

**Comment by alanwest** [comment]
The receiver's readme states:

> This receiver is beta. It has been tested on macOS and Linux with .NET v3.1.

I haven't had a chance to try different versions of .NET, but one theory is that it could be that I'm running a .NET 5 app on macOS.

**Comment by pmcollins** [comment]
Thanks for the submission. I'll see if I can reproduce the issue on Mac w/ .NET 5.

**Comment by pmcollins** [comment]
So I tried getting System.Runtime metrics from a long-running, simple application on macOS using .NET 5 and that works.

Any tips on how to reproduce?

Also, can you add the following to your dotnetdiagnostics receiver config and re-run?

    local_debug_dir: /tmp/dotnetdebug
    max_local_debug_files: 100

(Actual directory and max files at your discretion :-)

That should write the raw messages to the indicated directory. Hopefully some messages will be written before the receiver fails and they could be zipped up and attached to this thread. Thanks!

**Comment by pjanotti** [comment]
FWIW, I couldn't repro it on either in a macOS with SDK `5.0.203` not `5.0.103` not sure if that could be the difference.

**Comment by alanwest** [comment]
Hmm, good thought on upgrading the SDK, though I'm still hitting the issue after installing the latest `5.0.300`. I'm not sure what other factors may be at play here... when I have a moment, I can try and debug the receiver myself and see if anything else jumps out to me.

Here's the debug output [dotnetdebug.tar.gz](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/6548727/dotnetdebug.tar.gz)

**Comment by pjanotti** [comment]
I tried a repro on Ubuntu 20.04 and no luck but noticed two issues:

If I attach the receiver to the ASP.NET process and send CTRL+C to the ASP.NET process I get an error logged that perhaps should be logged with a different message and as info:

```terminal
2021-05-26T17:37:14.661-0700    error   dotnetdiagnosticsreceiver@v0.0.0-00010101000000-000000000000/receiver.go:98     parseAll error  {"kind": "receiver", "name": "dotnet_diagnostics", "error": "unexpected EOF"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver.(*receiver).Start.func1
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver@v0.0.0-00010101000000-000000000000/receiver.go:98
```

In the case above the collector is still working and didn't crash only logged the error message.

If instead, I attach the receiver to the dotnet process launching the ASP.NET process the collector crashes when I send CTRL+C to the ASP.NET project:

```terminal
panic: interface conversion: interface {} is nil, not string

goroutine 64 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver/dotnet.Metric.Name(...)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver@v0.0.0-00010101000000-000000000000/dotnet/metric.go:79
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver/metrics.rawMetricToPdata(0xc000eca000, 0xc0008f7200, 0xc023d8150715221c, 0xc6155e0c1, 0x60ae8e0, 0xc023d81540917774, 0xc966cff51, 0x60ae8e0, 0x9177740002f9e6)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver@v0.0.0-00010101000000-000000000000/metrics/converter.go:42 +0x7a5
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver/metrics.rawMetricsToPdata(0xc0005d5b58, 0x1, 0x1, 0xc023d8150715221c, 0xc6155e0c1, 0x60ae8e0, 0xc023d81540917774, 0xc966cff51, 0x60ae8e0, 0xffffffff)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver@v0.0.0-00010101000000-000000000000/metrics/converter.go:35 +0x1cd
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver/metrics.(*Sender).Send(0xc00060f380, 0xc0005d5b58, 0x1, 0x1)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver@v0.0.0-00010101000000-000000000000/metrics/sender.go:43 +0x9d
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver/dotnet.(*Parser).parseBlock(0xc00009c240, 0xc00034fb68, 0x0, 0x0)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver@v0.0.0-00010101000000-000000000000/dotnet/parser.go:112 +0x572
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver/dotnet.(*Parser).ParseAll(0xc00009c240, 0x44bed78, 0xc000312040, 0xc000312040, 0xc00039a010)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver@v0.0.0-00010101000000-000000000000/dotnet/parser.go:65 +0xd9
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver.(*receiver).Start.func1(0xc0002a72f0, 0xc00060de00, 0xc00009c240, 0xc0002a7300)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver@v0.0.0-00010101000000-000000000000/receiver.go:96 +0xb3
created by github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver.(*receiver).Start
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver@v0.0.0-00010101000000-000000000000/receiver.go:94 +0x505
```

**Comment by alanwest** [comment]
Ok so, bear with my silliness here... not sure this'll provide any clues, but I've been futzing around in nonsensical ways.

I changed:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f8c550fe19262199463401ac5c3fdce44130a31b/receiver/dotnetdiagnosticsreceiver/network/reader.go#L77-L83

to print out each byte being read, like so:
```csharp
func (r *mReader) ReadByte() (byte, error) {
	err := r.Read(singleByte)
	if err != nil {
		return 0, err
	}
	fmt.Print(string(singleByte[0]))
	return singleByte[0], nil
}
```

Of course, this is kinda silly since duh... printing out the string representation of the byte should result in complete nonsense.

The usual nonsense I see as metrics are being collected successfully:
```
ÏÒëPÿÿÿÿëP Ä¡Ô|
®cçD§,)Þ1²½=¾1²ü»Ò¤+~ª-¨õ,÷,õ+ +'ð%ë'xÜ&¢)¨)ß&®>´(©'%
```

But then right before stuff blows up on my machine, I get:
```
4
ëP¨ðèÔ|cpu-usageCPU Usage°?Interval=1000Mean%Ç­working-setWorking SetD@D@D@°?Interval=1000MeanMBíkgc-heap-sizeGC Heap Size4@4@4@°?Interval=1000MeanMBÔYgenun0nterSumÍ9gen-1-Gen 1 GC Count00:01:00°?Interval=1000Sum¡7gcou 0nterSum>²thcountThreadPool Thread Count°?Interval=1000Mean¿L¾monitconcouor Lennt0°?Interval=1000Sumá?²thengthThreadPool Queue Length°?Interval=1000Mean¨AÒthrcompleted-items-countThreadPool Completed Work Item Count00:00:01°?Interval=1000Sum9~allon R0valctive-timer-countNumber of Active Timers°?Interval=1000Meanã;gntatragmentation§@^ËjG@@§@^ËjG@°?I1000Mean%÷5exception Count00:00:01°?Interval=1000Sum8 tiin GC since last GC°?Interval=1000Mean%³5gen-0-sizeGen 0 Size°H7Aerval=1000MeanBó6geizep«@InteBô4gSiz('5Arva5xLOH Sizeø@ø@erval=1000MeanBò5¢poOH (PjecSiz@ä
Aterval=1000MeanB<¨acour odedÀ^@À^@À^@°?Interval=1000Mean°6ijitythAhA°?Interval=1000MeanBë5®mettef Methods Jitted¢@@¢@°eanHreqr-ste00:00:01Ý?Interval=1000Sum8toal Requests,@,@,@Ý?Interval=1000Mean¹4cuquestsCurrent RequestsÝ?Interval=1000MeanÕfauestsÝ?I1000Mean
```

Less nonsense - there's actual words in there. Seems to indicate some streams are getting crossed or something, no?

I haven't had much of a chance to really dive into the code to understand how this thing is working - hence the nonsensical futzing about, but thought I'd share my silliness in case it sparks any thoughts.

Also, to clarify, the collector does not crash - it's just the receiver that seems to stop - the collector process keeps chugging along fine.

**Comment by Doron-Bargo** [comment]
Hi any update on this issue?
