### ISSUE TITLE
Recombine: Multiline golang stack trace example

### ISSUE THREAD

**Issue by Fresa** [open-telemetry/opentelemetry-collector-contrib#36275]
### Component(s)

pkg/stanza

### Is your feature request related to a problem? Please describe.

I would like to recombine golang stack traces.

### Describe the solution you'd like

The documentation for recombine has [an example](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/recombine.md#recombine-stack-traces-into-multiline-logs) for how to recombine a java stack trace. Would be great to have something similar for a golang stack trace.

**Comment by VihasMakwana** [comment]
Hi.

Can you attach a golang stack trace example? I can help with this.

**Comment by Fresa** [comment]
@VihasMakwana here are two examples, one using zap:
https://go.dev/play/p/fRdYSlGjtUZ
```
1.257894e+09	error	sandbox3052195497/prog.go:28	stacktrace from panic
main.main.func1
	/tmp/sandbox3052195497/prog.go:28
runtime.gopanic
	/usr/local/go-faketime/src/runtime/panic.go:785
runtime.goPanicIndex
	/usr/local/go-faketime/src/runtime/panic.go:115
main.main
	/tmp/sandbox3052195497/prog.go:34
runtime.main
	/usr/local/go-faketime/src/runtime/proc.go:272
```
and second one using runtime/debug:
https://go.dev/play/p/krPo2EYA9Iz
```
stacktrace from panic: goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go-faketime/src/runtime/debug/stack.go:26 +0x5e
main.main.func1()
	/tmp/sandbox38606549/prog.go:11 +0x25
panic({0x4a74a0?, 0xc00001a018?})
	/usr/local/go-faketime/src/runtime/panic.go:785 +0x132
main.main()
	/tmp/sandbox38606549/prog.go:16 +0x35
```

**Comment by Fresa** [comment]
Still relevant
