### ISSUE TITLE
[Failed test][cmd/opampsupervisor] TestSupervisorPersistsNewInstanceID randomly failed

### ISSUE THREAD

**Issue by bacherfl** [open-telemetry/opentelemetry-collector-contrib#36850]
### Component(s)

cmd/opampsupervisor

### Describe the issue you're reporting

E.g.: [TestSupervisorPersistsNewInstanceID](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/12350739300/job/34464544343?pr=36844#step:8:647)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x9441b4]

goroutine 682 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor.(*Supervisor).reportConfigStatus(0xc0001938c8, 0x3, {0xa86e55, 0x1d})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor/supervisor.go:1246 +0x54
github.com/open-telemetry/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor.(*Supervisor).runAgentProcess(0xc0001938c8)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor/supervisor.go:1153 +0x85d
github.com/open-telemetry/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor.(*Supervisor).Start.func1()
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor/supervisor.go:240 +0x52
created by github.com/open-telemetry/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor.(*Supervisor).Start in goroutine 651
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor/supervisor.go:238 +0x767
exit status 2
```

**Comment by songy23** [comment]
+1 https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/12356389562/job/34482710393

this is TestSupervisorStartsCollectorWithRemoteConfig but with the same failure
