### ISSUE TITLE
AWS CloudWatch logs exporter is not yet functional

### ISSUE THREAD

**Issue by errordeveloper** [open-telemetry/opentelemetry-collector-contrib#4683]
There appears to be two issues right now.

Firstly, due to that `QueueSize` is unset, the queue is being blocked.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/64a13751e3a1702c25569b436ff8e283d4579a16/exporter/awscloudwatchlogsexporter/factory.go#L54-L57

So any attempt to use the exporter results in messages like:

```
2021-08-17T15:38:42.244+0100	ERROR	exporterhelper/queued_retry.go:190	Dropping data because sending_queue is full. Try increasing queue_size.	{"kind": "exporter", "name": "awscloudwatchlogs", "dropped_items": 1}
```

Secondly, `Start` and `Shutdown` method are not wired in.

**Comment by errordeveloper** [comment]
Having test #4698, I realised there is at one more issue:

```
2021-08-18T15:19:23.479+0100	debug	awscloudwatchlogsexporter@v0.32.0/exporter.go:62	Retrieving Cloud Watch sequence token	{"kind": "exporter", "name": "awscloudwatchlogs"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x640ef4e]

goroutine 1 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awscloudwatchlogsexporter.(*exporter).Start.func1()
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awscloudwatchlogsexporter@v0.32.0/exporter.go:76 +0x2ce
sync.(*Once).doSlow(0xc000b27750, 0xc0008bf590)
	sync/once.go:68 +0xec
sync.(*Once).Do(...)
	sync/once.go:59
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awscloudwatchlogsexporter.(*exporter).Start(0xc000b27740, 0x74391a8, 0xc0001a2000, 0x743a7c0, 0xc0001b7bd8, 0x0, 0x0)
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awscloudwatchlogsexporter@v0.32.0/exporter.go:46 +0x99
go.opentelemetry.io/collector/component/componenthelper.StartFunc.Start(0xc000b35930, 0x74391a8, 0xc0001a2000, 0x743a7c0, 0xc0001b7bd8, 0x0, 0x0)
	go.opentelemetry.io/collector@v0.32.1-0.20210817223921-dd190c568f83/component/componenthelper/component.go:28 +0x4e
go.opentelemetry.io/collector/exporter/exporterhelper.(*baseExporter).Start(0xc000b31e30, 0x74391a8, 0xc0001a2000, 0x743a7c0, 0xc0001b7bd8, 0x0, 0x0)
	go.opentelemetry.io/collector@v0.32.1-0.20210817223921-dd190c568f83/exporter/exporterhelper/common.go:197 +0x5f
go.opentelemetry.io/collector/service/internal/builder.(*builtExporter).Start(0xc000b35920, 0x74391a8, 0xc0001a2000, 0x743a7c0, 0xc0001b7bd8, 0x0, 0x645ea98)
	go.opentelemetry.io/collector@v0.32.1-0.20210817223921-dd190c568f83/service/internal/builder/exporters_builder.go:41 +0x113
go.opentelemetry.io/collector/service/internal/builder.Exporters.StartAll(0xc000b31d70, 0x74391a8, 0xc0001a2000, 0x743a788, 0xc0007afea0, 0x0, 0x0)
	go.opentelemetry.io/collector@v0.32.1-0.20210817223921-dd190c568f83/service/internal/builder/exporters_builder.go:95 +0x198
go.opentelemetry.io/collector/service.(*service).startPipelines(0xc0007afea0, 0x74391a8, 0xc0001a2000, 0x0, 0x0)
	go.opentelemetry.io/collector@v0.32.1-0.20210817223921-dd190c568f83/service/service.go:189 +0x93
go.opentelemetry.io/collector/service.(*service).Start(0xc0007afea0, 0x74391a8, 0xc0001a2000, 0x0, 0x0)
	go.opentelemetry.io/collector@v0.32.1-0.20210817223921-dd190c568f83/service/service.go:78 +0xe8
go.opentelemetry.io/collector/service.(*Collector).setupConfigurationComponents(0xc000269ee0, 0x74391a8, 0xc0001a2000, 0xc00005f100, 0x2)
	go.opentelemetry.io/collector@v0.32.1-0.20210817223921-dd190c568f83/service/collector.go:273 +0x3ee
go.opentelemetry.io/collector/service.(*Collector).execute(0xc000269ee0, 0x74391a8, 0xc0001a2000, 0xc00067cfc0, 0x0)
	go.opentelemetry.io/collector@v0.32.1-0.20210817223921-dd190c568f83/service/collector.go:317 +0x325
go.opentelemetry.io/collector/service.New.func1(0xc000658a00, 0xc0002a5400, 0x0, 0x4, 0x0, 0x0)
	go.opentelemetry.io/collector@v0.32.1-0.20210817223921-dd190c568f83/service/collector.go:144 +0x237
github.com/spf13/cobra.(*Command).execute(0xc000658a00, 0xc00018e060, 0x4, 0x4, 0xc000658a00, 0xc00018e060)
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000658a00, 0xc0003492f0, 0xc0003492c0, 0xc000349230)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
go.opentelemetry.io/collector/service.(*Collector).Run(...)
	go.opentelemetry.io/collector@v0.32.1-0.20210817223921-dd190c568f83/service/collector.go:174
main.main()
	github.com/open-telemetry/opentelemetry-collector-builder/main.go:45 +0x2c5
```

It appears that `steam.UploadSequenceToke` is actually `nil`.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/32eebfe5bf68bd66d0d481900a65d9ca190e9ed2/exporter/awscloudwatchlogsexporter/exporter.go#L76

I'll have a look at the docs and see how a token can be obtained... Could this be because my log stream is empty?

**Comment by errordeveloper** [comment]
From the SDK docs:

```Go
// PutLogEvents API operation for Amazon CloudWatch Logs.
//
// Uploads a batch of log events to the specified log stream.
//
// You must include the sequence token obtained from the response of the previous
// call. An upload in a newly created log stream does not require a sequence
// token. You can also get the sequence token in the expectedSequenceToken field
// from InvalidSequenceTokenException. If you call PutLogEvents twice within
// a narrow time period using the same value for sequenceToken, both calls might
// be successful or one might be rejected.
```
So it looks this logic needs to reworked... I'll aim to open another PR to address this.

**Comment by errordeveloper** [comment]
Closing since quite few fixed had been merged, and remaining improvements are tracked in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4721.
