### ISSUE TITLE
Windows Docker Desktop collector demo problem

### ISSUE THREAD

**Issue by tnevolin** [open-telemetry/opentelemetry-collector-contrib#5475]
Following steps here: https://opentelemetry.io/docs/collector/getting-started/#demo

All containers in docker-compose starts but then demo_demo-server_1 exits with following error in console output:
```
panic: runtime error: hash of unhashable type []string

goroutine 38 [running]:
type..hash.go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/tracetransform.ilsKey·1(0xc000643a18, 0x0, 0xc0000b0e30)
<autogenerated>:1 +0x35
go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/tracetransform.Spans(0xc000462000, 0x3, 0x200, 0x829646899, 0xf323a0, 0xb929e8)
/go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlptrace@v1.0.0-!r!c3/internal/tracetransform/span.go:57 +0x433
go.opentelemetry.io/otel/exporters/otlp/otlptrace.(*Exporter).ExportSpans(0xc00009cb90, 0xb929e8, 0xc000092360, 0xc000462000, 0x3, 0x200, 0x3, 0x3)
/go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlptrace@v1.0.0-!r!c3/exporter.go:44 +0x45
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).exportSpans(0xc00044e090, 0xb92978, 0xc000504000, 0x0, 0x0)
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/batch_span_processor.go:219 +0x145
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).processQueue(0xc00044e090)
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/batch_span_processor.go:247 +0x3c5
go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor.func1(0xc00044e090)
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/batch_span_processor.go:111 +0x58
created by go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/batch_span_processor.go:109 +0x211

panic: runtime error: hash of unhashable type []string

goroutine 38 [running]:
type..hash.go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/tracetransform.ilsKey·1(0xc0003efa18, 0x0, 0xc00011ce30)
<autogenerated>:1 +0x35
go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/tracetransform.Spans(0xc0000ee000, 0x3, 0x200, 0x827b613c1, 0xf323a0, 0xb929e8)
/go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlptrace@v1.0.0-!r!c3/internal/tracetransform/span.go:57 +0x433
go.opentelemetry.io/otel/exporters/otlp/otlptrace.(*Exporter).ExportSpans(0xc000100b90, 0xb929e8, 0xc0000a2780, 0xc0000ee000, 0x3, 0x200, 0x3, 0x3)
/go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlptrace@v1.0.0-!r!c3/exporter.go:44 +0x45
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).exportSpans(0xc0000da090, 0xb92978, 0xc0000ca8c0, 0x0, 0x0)
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/batch_span_processor.go:219 +0x145
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).processQueue(0xc0000da090)
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/batch_span_processor.go:247 +0x3c5
go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor.func1(0xc0000da090)
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/batch_span_processor.go:111 +0x58
created by go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/batch_span_processor.go:109 +0x211
```

Then demo_demo-client_1 exits with this output:
```
#0: LineLength: 185By
Latency: 1006.009ms
#0: LineLength: 707By
#1: LineLength: 689By
#2: LineLength: 983By
#3: LineLength: 342By
#4: LineLength: 386By
Latency: 14.890ms
#0: LineLength: 305By
#1: LineLength: 882By
#2: LineLength: 162By
Latency: 38.321ms

panic: runtime error: hash of unhashable type []string

goroutine 51 [running]:
type..hash.go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/tracetransform.ilsKey·1(0xc000437a08, 0x3d)
<autogenerated>:1 +0x1e
go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/tracetransform.Spans({0xc000422000, 0x6, 0xe3bfe0})
/go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlptrace@v1.0.0-!r!c3/internal/tracetransform/span.go:57 +0x305
go.opentelemetry.io/otel/exporters/otlp/otlptrace.(*Exporter).ExportSpans(0xc0000b4b40, {0xa719c8, 0xc000382240}, {0xc000422000, 0xc0000b3bc0, 0xc00050c060})
/go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlptrace@v1.0.0-!r!c3/exporter.go:44 +0x36
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).exportSpans(0xc0002e6bd0, {0xa71958, 0xc000500000})
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/batch_span_processor.go:219 +0x134
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).processQueue(0xc0002e6bd0)
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/batch_span_processor.go:247 +0x32c
go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor.func1()
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/batch_span_processor.go:111 +0x65
created by go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/batch_span_processor.go:109 +0x247

panic: runtime error: hash of unhashable type []string

goroutine 54 [running]:
type..hash.go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/tracetransform.ilsKey·1(0xc0000dda08, 0x3d)
<autogenerated>:1 +0x1e
go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/tracetransform.Spans({0xc0004e0000, 0x6, 0xe3bfe0})
/go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlptrace@v1.0.0-!r!c3/internal/tracetransform/span.go:57 +0x305
go.opentelemetry.io/otel/exporters/otlp/otlptrace.(*Exporter).ExportSpans(0xc00007eb90, {0xa719c8, 0xc000093080}, {0xc0004e0000, 0xc000494360, 0xc0004809c0})
/go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlptrace@v1.0.0-!r!c3/exporter.go:44 +0x36
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).exportSpans(0xc0004c6090, {0xa71958, 0xc0004bebc0})
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/batch_span_processor.go:219 +0x134
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).processQueue(0xc0004c6090)
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/batch_span_processor.go:247 +0x32c
go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor.func1()
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/batch_span_processor.go:111 +0x65
created by go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/batch_span_processor.go:109 +0x247

#0: LineLength: 481By
Latency: 667.060ms
#0: LineLength: 670By
#1: LineLength: 635By
#2: LineLength: 720By
#3: LineLength: 607By
#4: LineLength: 847By
Latency: 69.394ms
#0: LineLength: 796By
#1: LineLength: 911By
#2: LineLength: 115By
Latency: 978.262ms
```

**Comment by atoulme** [comment]
These panic calls refer to code that is no longer in the case (tracetransform processor). Closing this issue, please reopen if you see issues again.
