### ISSUE TITLE
awsxrayproxy: TestFactory_CreateExtension failed

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#5726]
Test failed here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5694/checks?check_run_id=3881454973

```
make[2]: Entering directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/awsxrayproxy'
go test -race -timeout 300s --tags="" ./...
--- FAIL: TestFactory_CreateExtension (0.00s)
    factory_test.go:71: 
        	Error Trace:	factory_test.go:71
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:41973/GetSamplingRules": dial tcp 127.0.0.1:41973: connect: connection refused
        	Test:       	TestFactory_CreateExtension
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfed37e]

goroutine 6 [running]:
testing.tRunner.func1.2({0x1094840, 0x213d380})
	/opt/hostedtoolcache/go/1.17.1/x64/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.17.1/x64/src/testing/testing.go:1212 +0x3b6
panic({0x1094840, 0x213d380})
	/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/panic.go:1047 +0x266
github.com/open-telemetry/opentelemetry-collector-contrib/extension/awsxrayproxy.TestFactory_CreateExtension(0x0)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/awsxrayproxy/factory_test.go:74 +0x79e
testing.tRunner(0xc000001a00, 0x11b6ad8)
	/opt/hostedtoolcache/go/1.17.1/x64/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.17.1/x64/src/testing/testing.go:1306 +0x727
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/extension/awsxrayproxy	0.044s
FAIL
make[2]: *** [../../Makefile.Common:45: test] Error 1
make[2]: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/awsxrayproxy'
make[1]: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib'
make[1]: *** [Makefile:148: for-all-target-./extension/awsxrayproxy] Error 2
make: *** [Makefile:68: gotest] Error 2
Error: Process completed with exit code 2.
```

**Comment by tigrannajaryan** [comment]
Happened again: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5694#issuecomment-942700349

**Comment by codeboten** [comment]
The same problem seems to be happening again https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4073583210?check_suite_focus=true#step:8:5057
