### ISSUE TITLE
Flaky test: TestJMXReceiverHappyPath from jmxreceiver

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#5874]
Seen on https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/3974469960?check_suite_focus=true

```
panic: test timed out after 1m0s

goroutine 549 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1788 +0xbb
created by time.goFunc
	/opt/hostedtoolcache/go/1.17.2/x64/src/time/sleep.go:180 +0x4a

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000158d00, {0x12131d6, 0x12}, 0x1245028)
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1307 +0x752
testing.runTests.func1(0x0)
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1598 +0x9a
testing.tRunner(0xc000158d00, 0xc0002dfbc0)
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1259 +0x230
testing.runTests(0xc000488280, {0x19f2280, 0x9, 0x9}, {0x0, 0xc0003c3ec0, 0x1a03420})
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1596 +0x7cb
testing.(*M).Run(0xc000488280)
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1504 +0x9d2
main.main()
	_testmain.go:111 +0x325

goroutine 19 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000fc180)
	/home/runner/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0x185
created by go.opencensus.io/stats/view.init.0
	/home/runner/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0xf9

goroutine 20 [chan receive]:
testing.(*T).Run(0xc000158ea0, {0x106b378, 0x18}, 0xc000172000)
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1307 +0x752
github.com/stretchr/testify/suite.runTests({0x13966e0, 0xc000158ea0}, {0xc00048a750, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:203 +0x190
github.com/stretchr/testify/suite.Run(0xc000158ea0, {0x1373568, 0xc000078040})
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:176 +0x995
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver.TestJMXIntegration(0x0)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/jmxreceiver/integration_test.go:54 +0x45
testing.tRunner(0xc000158ea0, 0x1245028)
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1306 +0x727

goroutine 7 [chan receive]:
testing.(*T).Run(0xc000158b60, {0x120d7e5, 0xb}, 0xc0003e8e00)
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1307 +0x752
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver.(*JMXIntegrationSuite).TestJMXReceiverHappyPath(0xc000078040)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/jmxreceiver/integration_test.go:141 +0xbb
reflect.Value.call({0xc0000b82a0, 0xc0000b6ae8, 0x43d653}, {0x1206dd0, 0x4}, {0xc00006ada8, 0x1, 0xc00006abc8})
	/opt/hostedtoolcache/go/1.17.2/x64/src/reflect/value.go:543 +0xe54
reflect.Value.Call({0xc0000b82a0, 0xc0000b6ae8, 0xc000078040}, {0xc00006ada8, 0x1, 0x1})
	/opt/hostedtoolcache/go/1.17.2/x64/src/reflect/value.go:339 +0xd8
github.com/stretchr/testify/suite.Run.func1(0xc000158b60)
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:158 +0x71d
testing.tRunner(0xc000158b60, 0xc000172000)
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1306 +0x727

goroutine 376 [select]:
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver/internal/subprocess.(*Subprocess).Shutdown(0xc0004f4de0, {0x137dc08, 0xc0000ce008})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/jmxreceiver/internal/subprocess/subprocess.go:146 +0x229
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver.(*jmxMetricReceiver).Shutdown(0xc00007ec60, {0x137dc08, 0xc0000ce008})
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/jmxreceiver/receiver.go:95 +0x97
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver.(*JMXIntegrationSuite).TestJMXReceiverHappyPath.func1.1()
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/jmxreceiver/integration_test.go:185 +0x5d
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver.(*JMXIntegrationSuite).TestJMXReceiverHappyPath.func1(0xc000384b60)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/jmxreceiver/integration_test.go:249 +0x122d
testing.tRunner(0xc000384b60, 0xc0003e8e00)
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1306 +0x727

goroutine 27 [IO wait]:
internal/poll.runtime_pollWait(0x7f46431a1030, 0x72)
	/opt/hostedtoolcache/go/1.17.2/x64/src/runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc00050f698, 0xc0004d6000, 0x0)
	/opt/hostedtoolcache/go/1.17.2/x64/src/internal/poll/fd_poll_runtime.go:84 +0xbd
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.17.2/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00050f680, {0xc0004d6000, 0xdcd5, 0xdcd5})
	/opt/hostedtoolcache/go/1.17.2/x64/src/internal/poll/fd_unix.go:167 +0x419
net.(*netFD).Read(0xc00050f680, {0xc0004d6000, 0xdcd5, 0xdcd5})
	/opt/hostedtoolcache/go/1.17.2/x64/src/net/fd_posix.go:56 +0x51
bufio.(*Reader).Read(0xc0004f5380, {0xc000494118, 0x9, 0x9})
	/opt/hostedtoolcache/go/1.17.2/x64/src/bufio/bufio.go:227 +0x4db
io.ReadAtLeast({0x1364300, 0xc0004f5380}, {0xc000494118, 0x9, 0x9}, 0x9)
	/opt/hostedtoolcache/go/1.17.2/x64/src/io/io.go:328 +0xde
io.ReadFull(...)
	/opt/hostedtoolcache/go/1.17.2/x64/src/io/io.go:347
golang.org/x/net/http2.readFrameHeader({0xc000494118, 0x9, 0x9}, {0x1364300, 0xc0004f5380})
	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20210614182718-04defd469f4e/http2/frame.go:237 +0x96
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0004940e0)
	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20210614182718-04defd469f4e/http2/frame.go:492 +0x108
google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams(0xc000134780, 0x0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.41.0/internal/transport/http2_server.go:558 +0x14c
google.golang.org/grpc.(*Server).serveStreams(0xc0000f8000, {0x138d740, 0xc000134780})
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:907 +0x28a
google.golang.org/grpc.(*Server).handleRawConn.func1()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:847 +0x65
created by google.golang.org/grpc.(*Server).handleRawConn
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:846 +0x265
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver	60.060s
```

**Comment by jpkrohling** [comment]
Failed again: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4111456360?check_suite_focus=true as part of #6143.

@rmfitzpatrick, are you able to take a look at this one?

**Comment by rmfitzpatrick** [comment]
@jpkrohling I missed the initial notification on this and will be sure to look into it.

**Comment by jpkrohling** [comment]
Another failure here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4162606020?check_suite_focus=true

**Comment by tigrannajaryan** [comment]
Failed again: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4256134172?check_suite_focus=true

**Comment by jpkrohling** [comment]
@rmfitzpatrick, should we just disable this test while you figure it out?

**Comment by rmfitzpatrick** [comment]
That seems reasonable until I have a chance to finish https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5429.

**Comment by jpkrohling** [comment]
Do you have any news about this, @rmfitzpatrick?

**Comment by rmfitzpatrick** [comment]
> Do you have any news about this, @rmfitzpatrick?

I've not had a chance to switch back to this in some time and closed the improvement PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5429. I've been asked to work on unrelated projects in the interim. It's my hope that I or potentially someone in my place will be able to devote more attention to it in the next couple weeks.

**Comment by jpkrohling** [comment]
Sounds good, thanks for the update!

**Comment by jpkrohling** [comment]
I don't remember seeing this failing lately, but it would be good to have a positive confirmation that something was done/fixed before letting this be closed due to inactivity.

**Comment by djaglowski** [comment]
I tried running this locally just now and received the following error:

```
--- FAIL: TestJMXIntegration (106.36s)
    --- FAIL: TestJMXIntegration/TestJMXReceiverHappyPath (82.25s)
        --- FAIL: TestJMXIntegration/TestJMXReceiverHappyPath/1.4.0-alpha (78.48s)
            /Users/djaglowski/go/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver/integration_test.go:167: 
                	Error Trace:	/Users/djaglowski/go/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver/integration_test.go:167
                	Error:      	Received unexpected error:
                	            	invalid `jar_path`: jar hash does not match known versions
                	Test:       	TestJMXIntegration/TestJMXReceiverHappyPath/1.4.0-alpha
        --- FAIL: TestJMXIntegration/TestJMXReceiverHappyPath/1.0.0-alpha (3.77s)
            /Users/djaglowski/go/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver/integration_test.go:167: 
                	Error Trace:	/Users/djaglowski/go/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver/integration_test.go:167
                	Error:      	Received unexpected error:
                	            	invalid `jar_path`: jar hash does not match known versions
                	Test:       	TestJMXIntegration/TestJMXReceiverHappyPath/1.0.0-alpha
FAIL
exit status 1
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver	106.851s
```

It does appear that the receiver no longer supports these versions, so this is apparently now an issue of updating the test as well.

**Comment by mrsillydog** [comment]
I am looking into this issue.
