### ISSUE TITLE
Make testbed does not work MacOS 

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector-contrib#6144]
**Describe the bug**
Trying to replicate issues the load test to see what needs to be fixed within the CI however, running it on my local machine, it contains a few nil pointer exception.

**Steps to reproduce**
Using an MacOS machine:
```shell
make -c testbed run-tests
```

**What did you expect to see?**
An output that matches what is run inside the CI 

**What did you see instead?**
```text
--- FAIL: TestIdleMode (0.01s)
=== RUN   TestBallastMemory
2021/11/05 09:28:42 Starting Agent (/Users/smarciniak/Development/OpenSource/opentelemetry-collector-contrib/bin/otelcontribcol_darwin_amd64)
2021/11/05 09:28:42 Writing Agent log to /Users/smarciniak/Development/OpenSource/opentelemetry-collector-contrib/testbed/tests/results/TestBallastMemory/agent.log
2021/11/05 09:28:42 cannot start executable at /Users/smarciniak/Development/OpenSource/opentelemetry-collector-contrib/bin/otelcontribcol_darwin_amd64: fork/exec /Users/smarciniak/Development/OpenSource/opentelemetry-collector-contrib/bin/otelcontribcol_darwin_amd64: no such file or directory
    test_case.go:305: cannot start executable at /Users/smarciniak/Development/OpenSource/opentelemetry-collector-contrib/bin/otelcontribcol_darwin_amd64: fork/exec /Users/smarciniak/Development/OpenSource/opentelemetry-collector-contrib/bin/otelcontribcol_darwin_amd64: no such file or directory
--- FAIL: TestBallastMemory (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x43b38c2]

goroutine 123 [running]:
testing.tRunner.func1.2({0x6292080, 0x83946a0})
	/usr/local/Cellar/go/1.17.2/libexec/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/local/Cellar/go/1.17.2/libexec/src/testing/testing.go:1212 +0x218
panic({0x6292080, 0x83946a0})
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/panic.go:1038 +0x215
github.com/shirou/gopsutil/v3/process.(*Process).MemoryInfoWithContext(0x100000001, {0x6c53ed0, 0xc000190008})
	/Users/smarciniak/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.10/process/process_darwin.go:331 +0x22
github.com/shirou/gopsutil/v3/process.(*Process).MemoryInfo(...)
	/Users/smarciniak/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.10/process/process.go:476
github.com/open-telemetry/opentelemetry-collector-contrib/testbed/testbed.(*TestCase).AgentMemoryInfo(0xde3c1700000001c)
	/Users/smarciniak/Development/OpenSource/opentelemetry-collector-contrib/testbed/testbed/test_case.go:215 +0x35
github.com/open-telemetry/opentelemetry-collector-contrib/testbed/tests.TestBallastMemory.func1()
	/Users/smarciniak/Development/OpenSource/opentelemetry-collector-contrib/testbed/tests/e2e_test.go:114 +0x38
github.com/open-telemetry/opentelemetry-collector-contrib/testbed/testbed.(*TestCase).WaitForN(0xc000647e10, 0xc000657df8, 0x77359400, {0x6051b20, 0xc000649000})
	/Users/smarciniak/Development/OpenSource/opentelemetry-collector-contrib/testbed/testbed/test_case.go:272 +0x82
github.com/open-telemetry/opentelemetry-collector-contrib/testbed/tests.TestBallastMemory(0xc0006c3520)
	/Users/smarciniak/Development/OpenSource/opentelemetry-collector-contrib/testbed/tests/e2e_test.go:113 +0x449
testing.tRunner(0xc0006c3520, 0x68c14d0)
	/usr/local/Cellar/go/1.17.2/libexec/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/usr/local/Cellar/go/1.17.2/libexec/src/testing/testing.go:1306 +0x35a
exit status 2
```

**What version did you use?**
Version: git hash: 1e9005e6fa42a5514bac6f4f4c725f10d64c16f8

**Environment**
OS: MacOS 11.6.1
Compiler(if manually compiled): go version go1.17.2 darwin/amd64

**Comment by cuichenli** [comment]
hey @MovieStoreGuy , you need to run `make otelcontribcol` before running the load tests so it can build the agent to be executed. 

but the error message is indeed confusing, guess we can add some pre-check on if the binary exists.

**Comment by MovieStoreGuy** [comment]
@cuichenli , I would have hoped that would have been done as part of the makefile. Anyway that we can include that in the make target's dependencies ?

**Comment by MovieStoreGuy** [comment]
It looks like this issue has been resolved.
