### ISSUE TITLE
Flaky test - awsproxy - TestFactory_CreateExtension 

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#6147]
Seen here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4107918114?check_suite_focus=true (#5999)

cc @anuraaga @Aneurysm9 @mxiamxia (as code owners)

```
=== RUN   TestFactory_CreateExtension
    factory_test.go:89: 
        	Error Trace:	factory_test.go:89
        	Error:      	Received unexpected error:
        	            	Post "http://127.0.0.1:43487/GetSamplingRules": dial tcp 127.0.0.1:43487: connect: connection refused
        	Test:       	TestFactory_CreateExtension
--- FAIL: TestFactory_CreateExtension (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xda648d]

goroutine 22 [running]:
testing.tRunner.func1.2({0xe24340, 0x1d93240})
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1212 +0x3b6
panic({0xe24340, 0x1d93240})
	/opt/hostedtoolcache/go/1.17.2/x64/src/runtime/panic.go:1047 +0x266
github.com/open-telemetry/opentelemetry-collector-contrib/extension/awsproxy.TestFactory_CreateExtension(0xc0003ce000)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/awsproxy/factory_test.go:91 +0x98d
testing.tRunner(0xc0003ce000, 0xefdd78)
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.17.2/x64/src/testing/testing.go:1306 +0x727
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/extension/awsproxy	0.046s
FAIL
make[2]: *** [../../Makefile.Common:45: test] Error 1
make[2]: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/awsproxy'
make[1]: *** [Makefile:149: for-all-target-./extension/awsproxy] Error 2
make: *** [Makefile:69: gotest] Error 2
make[1]: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib'
```

**Comment by anuraaga** [comment]
I think there was a similar issue but can't find it.

I don't have any ideas for improving the test, other than using a polling assertion since it may just take some time for the endpoint to start up. I couldn't find a similar pattern in other tests but also don't profess to being a golang expert - can anyone give me a pointer?

**Comment by jpkrohling** [comment]
[`assert.Eventually`](https://pkg.go.dev/github.com/stretchr/testify/assert#Eventually) could be used here then?

**Comment by anuraaga** [comment]
Don't think we've seen this flake in a while but let's reopen if it does
