### ISSUE TITLE
Attempt to use unknown class when running make test on Mac

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-collector-contrib#6505]
Running `make test`, I get this dump (different from the old #5425 problem).

```
objc[22482]: Attempt to use unknown class 0x7ff84767d360.
SIGABRT: abort
PC=0x7ff805e49dfe m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x83bc310, 0xc0002df278)
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/cgocall.go:156 +0x6e fp=0xc0002df250 sp=0xc0002df218 pc=0x400744e
os/user._Cfunc_mygetpwuid_r(0x4b523a35, 0xc00004ee60, 0xe809200, 0x1000, 0xc000126a68)
	_cgo_gotypes.go:181 +0x85 fp=0xc0002df278 sp=0xc0002df250 pc=0x524f245
os/user.lookupUnixUid.func1.1(0x4b523a35, 0xe0a8108, 0xc00011d550, 0xc70d560)
	/usr/local/Cellar/go/1.17.2/libexec/src/os/user/cgo_lookup_unix.go:105 +0xdc fp=0xc0002df2e0 sp=0xc0002df278 pc=0x524fd5c
os/user.lookupUnixUid.func1()
	/usr/local/Cellar/go/1.17.2/libexec/src/os/user/cgo_lookup_unix.go:105 +0x5e fp=0xc0002df338 sp=0xc0002df2e0 pc=0x524fc5e
os/user.retryWithBuffer(0xc00011d550, 0xc0002df490)
	/usr/local/Cellar/go/1.17.2/libexec/src/os/user/cgo_lookup_unix.go:249 +0x42 fp=0xc0002df398 sp=0xc0002df338 pc=0x5250e82
os/user.lookupUnixUid(0x4b523a35)
	/usr/local/Cellar/go/1.17.2/libexec/src/os/user/cgo_lookup_unix.go:98 +0x1de fp=0xc0002df4c8 sp=0xc0002df398 pc=0x524f97e
os/user.current()
	/usr/local/Cellar/go/1.17.2/libexec/src/os/user/cgo_lookup_unix.go:51 +0x2a fp=0xc0002df4f8 sp=0xc0002df4c8 pc=0x524f6aa
os/user.Current.func1()
	/usr/local/Cellar/go/1.17.2/libexec/src/os/user/lookup.go:15 +0x2a fp=0xc0002df528 sp=0xc0002df4f8 pc=0x5250faa
sync.(*Once).doSlow(0xc707b60, 0x9230ab8)
	/usr/local/Cellar/go/1.17.2/libexec/src/sync/once.go:68 +0x128 fp=0xc0002df610 sp=0xc0002df528 pc=0x407fe68
sync.(*Once).Do(0xc707b60, 0xd)
	/usr/local/Cellar/go/1.17.2/libexec/src/sync/once.go:59 +0x47 fp=0xc0002df638 sp=0xc0002df610 pc=0x407fd07
os/user.Current()
	/usr/local/Cellar/go/1.17.2/libexec/src/os/user/lookup.go:15 +0x38 fp=0xc0002df680 sp=0xc0002df638 pc=0x524ebd8
github.com/golang/glog.init.1()
	/Users/aanuraag/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog_file.go:63 +0xae fp=0xc0002df6f8 sp=0xc0002df680 pc=0x52d3eae
runtime.doInit(0xc575a60)
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/proc.go:6498 +0x123 fp=0xc0002df830 sp=0xc0002df6f8 pc=0x404a4e3
runtime.doInit(0xc57eee0)
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc0002df968 sp=0xc0002df830 pc=0x404a431
runtime.doInit(0xc5602c0)
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc0002dfaa0 sp=0xc0002df968 pc=0x404a431
runtime.doInit(0xc570340)
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc0002dfbd8 sp=0xc0002dfaa0 pc=0x404a431
runtime.doInit(0xc585060)
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc0002dfd10 sp=0xc0002dfbd8 pc=0x404a431
runtime.doInit(0xc59d380)
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc0002dfe48 sp=0xc0002dfd10 pc=0x404a431
runtime.doInit(0xc5595a0)
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc0002dff80 sp=0xc0002dfe48 pc=0x404a431
runtime.main()
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/proc.go:238 +0x1e6 fp=0xc0002dffe0 sp=0xc0002dff80 pc=0x403cee6
runtime.goexit()
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0002dffe8 sp=0xc0002dffe0 pc=0x406ff81

goroutine 21 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000178180)
	/Users/aanuraag/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0x185
created by go.opencensus.io/stats/view.init.0
	/Users/aanuraag/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0xf9

goroutine 22 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000352c30)
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:212 +0xec
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:118 +0x1b1

goroutine 23 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000352d00)
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:212 +0xec
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:118 +0x1b1

goroutine 24 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000352dd0)
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:212 +0xec
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:118 +0x1b1

goroutine 25 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000352ea0)
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:212 +0xec
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:118 +0x1b1

goroutine 26 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000352f70)
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:212 +0xec
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:118 +0x1b1

goroutine 27 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000353040)
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:212 +0xec
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:118 +0x1b1

goroutine 28 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000353110)
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:212 +0xec
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:118 +0x1b1

goroutine 29 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc0003531e0)
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:212 +0xec
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:118 +0x1b1

goroutine 30 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc0003532b0)
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:212 +0xec
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:118 +0x1b1

goroutine 31 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000353380)
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:212 +0xec
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:118 +0x1b1

goroutine 32 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000353450)
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:212 +0xec
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:118 +0x1b1

goroutine 33 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc000353520)
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:212 +0xec
created by github.com/klauspost/compress/zstd.newBlockDec
	/Users/aanuraag/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:118 +0x1b1

goroutine 6 [select]:
github.com/patrickmn/go-cache.(*janitor).Run(0xc00011cef0, 0x47bc2da)
	/Users/aanuraag/go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0x111
created by github.com/patrickmn/go-cache.runJanitor
	/Users/aanuraag/go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0x17d

goroutine 7 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc0000d99d0, 0x0)
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/sema.go:513 +0x13d
sync.(*Cond).Wait(0xc0000d99c0)
	/usr/local/Cellar/go/1.17.2/libexec/src/sync/cond.go:56 +0xa5
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc00015a510)
	/Users/aanuraag/go/pkg/mod/github.com/cihub/seelog@v0.0.0-20170130134532-f561c5e57575/behavior_asynclooplogger.go:50 +0x152
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc00015a510)
	/Users/aanuraag/go/pkg/mod/github.com/cihub/seelog@v0.0.0-20170130134532-f561c5e57575/behavior_asynclooplogger.go:63 +0x3f
created by github.com/cihub/seelog.NewAsyncLoopLogger
	/Users/aanuraag/go/pkg/mod/github.com/cihub/seelog@v0.0.0-20170130134532-f561c5e57575/behavior_asynclooplogger.go:40 +0x119

goroutine 8 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc0000d9b50, 0x0)
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/sema.go:513 +0x13d
sync.(*Cond).Wait(0xc0000d9b40)
	/usr/local/Cellar/go/1.17.2/libexec/src/sync/cond.go:56 +0xa5
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc00015a630)
	/Users/aanuraag/go/pkg/mod/github.com/cihub/seelog@v0.0.0-20170130134532-f561c5e57575/behavior_asynclooplogger.go:50 +0x152
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc00015a630)
	/Users/aanuraag/go/pkg/mod/github.com/cihub/seelog@v0.0.0-20170130134532-f561c5e57575/behavior_asynclooplogger.go:63 +0x3f
created by github.com/cihub/seelog.NewAsyncLoopLogger
	/Users/aanuraag/go/pkg/mod/github.com/cihub/seelog@v0.0.0-20170130134532-f561c5e57575/behavior_asynclooplogger.go:40 +0x119

goroutine 9 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x0)
	/Users/aanuraag/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/Users/aanuraag/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x265

rax    0x2000209
rbx    0x80
rcx    0x7ff7bfefe438
rdx    0x0
rdi    0x8
rsi    0x1
rbp    0x7ff7bfefe480
rsp    0x7ff7bfefe438
r8     0x600002c00000
r9     0x80
r10    0x0
r11    0x246
r12    0x0
r13    0x0
r14    0x1
r15    0x8
rip    0x7ff805e49dfe
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/internal/components	2.730s
testing: warning: no tests to run
PASS
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/internal/version	1.101s [no tests to run]
FAIL
make: *** [test] Error 1
```

**Environment**
OS: Mac OS X 12.0.1
Compiler(if manually compiled):1.17.2

**Comment by gandhipr** [comment]
https://github.com/golang/go/issues/49138 check if they're related.

**Comment by anuraaga** [comment]
Seems to be fine for me too, thanks
