### ISSUE TITLE
Flaky test - `prometheusreceiver` - TestExternalLabels

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#6532]
Seen here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4430141105?check_suite_focus=true#logs

Logs:

```
--- FAIL: TestExternalLabels (6.82s)
    --- FAIL: TestExternalLabels/target1 (0.00s)
        --- FAIL: TestExternalLabels/target1/scrape-externalLabels (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2dcd603]

goroutine 88 [running]:
testing.tRunner.func1.2({0x338ebc0, 0x5be89d0})
	/opt/hostedtoolcache/go/1.17.3/x64/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.17.3/x64/src/testing/testing.go:1212 +0x3b6
panic({0x338ebc0, 0x5be89d0})
	/opt/hostedtoolcache/go/1.17.3/x64/src/runtime/panic.go:1047 +0x266
go.opentelemetry.io/collector/model/pdata.AttributeValue.Type(...)
	/home/runner/go/pkg/mod/go.opentelemetry.io/collector/model@v0.40.1-0.20211202221455-42566a660aac/pdata/common.go:137
go.opentelemetry.io/collector/model/pdata.AttributeValue.AsString({0xc0009ede28})
	/home/runner/go/pkg/mod/go.opentelemetry.io/collector/model@v0.40.1-0.20211202221455-42566a660aac/pdata/common.go:371 +0x43
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver.doCompare.func1(0x0)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/prometheusreceiver/metrics_receiver_helper_test.go:289 +0x255
testing.tRunner(0xc0002e9d40, 0xc00053a240)
	/opt/hostedtoolcache/go/1.17.3/x64/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.17.3/x64/src/testing/testing.go:1306 +0x727
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver	7.100s
```

**Comment by jpkrohling** [comment]
Any news about this flaky test?

**Comment by dashpole** [comment]
I'll take a look today

**Comment by dashpole** [comment]
Panic fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6476.  This can be closed.
