### ISSUE TITLE
Flaky test - k8sclusterreceiver - TestFactory

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#6986]
Seen here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4689582202?check_suite_focus=true

```
=== RUN   TestFactory
E0103 09:50:52.233080   45629 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 47 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x23bbc40, 0x3840740})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/runtime/runtime.go:74 +0xe6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000017898})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/runtime/runtime.go:48 +0xb0
panic({0x23bbc40, 0x3840740})
	/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/panic.go:1047 +0x266
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0001c41c0, 0xc0001722d0, 0xc00047e060, 0xc000017b00)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:319 +0x127a
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0001c41c0, 0xc00047e060)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:361 +0x2d6
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:221 +0x45
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0002d66d8)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:155 +0x82
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000253580, {0x2912940, 0xc00010eeb0}, 0x1, 0xc00047e060)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:156 +0xcf
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0001c41c0, 0xc00047e060)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:220 +0x296
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:56 +0x3f
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:73 +0x7f
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:71 +0xdf
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference

goroutine 47 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000017898})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/runtime/runtime.go:55 +0x145
panic({0x23bbc40, 0x3840740})
	/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/panic.go:1047 +0x266
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0001c41c0, 0xc0001722d0, 0xc00047e060, 0xc000017b00)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:319 +0x127a
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0001c41c0, 0xc00047e060)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:361 +0x2d6
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:221 +0x45
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0002d66d8)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:155 +0x82
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000253580, {0x2912940, 0xc00010eeb0}, 0x1, 0xc00047e060)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:156 +0xcf
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0001c41c0, 0xc00047e060)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:220 +0x296
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:56 +0x3f
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:73 +0x7f
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:71 +0xdf
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sclusterreceiver	0.111s
```

This was seen right in a commit that touched this component: https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/d202af20407be117499b86939924a85fb957d6db

@secustor, as the author of that PR (#6436), would you be able to take a look and see if that caused this failure?

**Comment by secustor** [comment]
Yes, I will look into this.

**Comment by jpkrohling** [comment]
Another failure:

```
=== RUN   TestFactory
E0104 16:33:26.125806   45654 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 46 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x23bbc40, 0x3840740})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/runtime/runtime.go:74 +0xe6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00015b898})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/runtime/runtime.go:48 +0xb0
panic({0x23bbc40, 0x3840740})
	/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/panic.go:1047 +0x266
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0001c22a0, 0xc0000f0480, 0xc00012e000, 0xc00015bb00)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:319 +0x127a
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0001c22a0, 0xc00012e000)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:361 +0x2d6
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:221 +0x45
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0001536d8)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:155 +0x82
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00014a100, {0x2912940, 0xc000112370}, 0x1, 0xc00012e000)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:156 +0xcf
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0001c22a0, 0xc00012e000)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:220 +0x296
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:56 +0x3f
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:73 +0x7f
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:71 +0xdf
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference

goroutine 46 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00015b898})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/runtime/runtime.go:55 +0x145
panic({0x23bbc40, 0x3840740})
	/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/panic.go:1047 +0x266
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0001c22a0, 0xc0000f0480, 0xc00012e000, 0xc00015bb00)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:319 +0x127a
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0001c22a0, 0xc00012e000)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:361 +0x2d6
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:221 +0x45
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0001536d8)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:155 +0x82
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00014a100, {0x2912940, 0xc000112370}, 0x1, 0xc00012e000)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:156 +0xcf
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0001c22a0, 0xc00012e000)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:220 +0x296
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:56 +0x3f
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:73 +0x7f
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:71 +0xdf
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sclusterreceiver	0.113s
```

Seen here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4704428527?check_suite_focus=true

**Comment by secustor** [comment]
I can not reproduce the issue neither on my fork, locally or on my draft PR.  Do you still this issue?

**Comment by jpkrohling** [comment]
Let's keep this open and see if it happens again.

**Comment by djaglowski** [comment]
Another occurrence here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5275916920?check_suite_focus=true#step:8:15765

**Comment by jpkrohling** [comment]
Once more here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5888404798?check_suite_focus=true

```
2022-04-08T16:46:16.0722274Z === RUN   TestFactory
2022-04-08T16:46:16.0722888Z E0408 16:46:16.053930   55457 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
2022-04-08T16:46:16.0723415Z goroutine 48 [running]:
2022-04-08T16:46:16.0723836Z k8s.io/apimachinery/pkg/util/runtime.logPanic({0x24e42e0?, 0x386a280?})
2022-04-08T16:46:16.0724393Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/runtime/runtime.go:74 +0xe6
2022-04-08T16:46:16.0725221Z k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0005ef8e8?})
2022-04-08T16:46:16.0725803Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/runtime/runtime.go:48 +0xb0
2022-04-08T16:46:16.0726231Z panic({0x24e42e0, 0x386a280})
2022-04-08T16:46:16.0726671Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/runtime/panic.go:844 +0x258
2022-04-08T16:46:16.0727391Z k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0001be2a0, 0xc000242240, 0xc0000ce000, 0xc0005efb40)
2022-04-08T16:46:16.0728114Z 	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:319 +0x126e
2022-04-08T16:46:16.0728753Z k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0001be2a0, 0xc0000ce000)
2022-04-08T16:46:16.0729414Z 	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:361 +0x2f6
2022-04-08T16:46:16.0730044Z k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
2022-04-08T16:46:16.0730678Z 	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:221 +0x45
2022-04-08T16:46:16.0731190Z k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0000e76e0)
2022-04-08T16:46:16.0731729Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:155 +0x49
2022-04-08T16:46:16.0732260Z k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00037a200?, {0x2ab0200, 0xc00004e410}, 0x1, 0xc0000ce000)
2022-04-08T16:46:16.0732826Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:156 +0xcf
2022-04-08T16:46:16.0733427Z k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0001be2a0, 0xc0000ce000)
2022-04-08T16:46:16.0734070Z 	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:220 +0x29f
2022-04-08T16:46:16.0734602Z k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
2022-04-08T16:46:16.0735144Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:56 +0x3f
2022-04-08T16:46:16.0735612Z k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
2022-04-08T16:46:16.0736123Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:73 +0x74
2022-04-08T16:46:16.0736915Z created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
2022-04-08T16:46:16.0737426Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:71 +0xdd
2022-04-08T16:46:16.0737944Z panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2022-04-08T16:46:16.0738777Z 	panic: runtime error: invalid memory address or nil pointer dereference
2022-04-08T16:46:16.0739109Z 
2022-04-08T16:46:16.0739294Z goroutine 48 [running]:
2022-04-08T16:46:16.0739719Z k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0005ef8e8?})
2022-04-08T16:46:16.0740272Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/runtime/runtime.go:55 +0x145
2022-04-08T16:46:16.0740696Z panic({0x24e42e0, 0x386a280})
2022-04-08T16:46:16.0741136Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/runtime/panic.go:844 +0x258
2022-04-08T16:46:16.0742025Z k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0001be2a0, 0xc000242240, 0xc0000ce000, 0xc0005efb40)
2022-04-08T16:46:16.0742799Z 	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:319 +0x126e
2022-04-08T16:46:16.0743453Z k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0001be2a0, 0xc0000ce000)
2022-04-08T16:46:16.0744116Z 	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:361 +0x2f6
2022-04-08T16:46:16.0744665Z k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
2022-04-08T16:46:16.0745279Z 	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:221 +0x45
2022-04-08T16:46:16.0746612Z k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0000e76e0)
2022-04-08T16:46:16.0747080Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:155 +0x49
2022-04-08T16:46:16.0747536Z k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00037a200?, {0x2ab0200, 0xc00004e410}, 0x1, 0xc0000ce000)
2022-04-08T16:46:16.0748019Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:156 +0xcf
2022-04-08T16:46:16.0748579Z k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0001be2a0, 0xc0000ce000)
2022-04-08T16:46:16.0749131Z 	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:220 +0x29f
2022-04-08T16:46:16.0749556Z k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
2022-04-08T16:46:16.0750015Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:56 +0x3f
2022-04-08T16:46:16.0750408Z k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
2022-04-08T16:46:16.0750838Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:73 +0x74
2022-04-08T16:46:16.0751238Z created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
2022-04-08T16:46:16.0751667Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:71 +0xdd
2022-04-08T16:46:16.0752280Z FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sclusterreceiver	0.114s
```
