### ISSUE TITLE
[elasticsearchexporter] Crash when using elasticsearch exporter with batch processor

### ISSUE THREAD

**Issue by lancerdima** [open-telemetry/opentelemetry-collector-contrib#7934]
**Describe the bug**
ElasticSearch exporter crash, when combined with the batch processor.

**Steps to reproduce**
* Collect logs with OTEL receiver;
* Apply batch processor to reduce the amount of outbound calls
* Push log records to elasticsearch.

**What did you expect to see?**
Logs are delivered to elasticsearch.

**What did you see instead?**
Error message:
```
2022-02-15T11:56:46.542Z            INFO      loggingexporter/logging_exporter.go:69              LogsExporter     {"#logs": 160}
panic: runtime error: index out of range [1] with length 1

goroutine 174 [running]:
go.opentelemetry.io/collector/model/pdata.InstrumentationLibraryLogsSlice.At(...)
                go.opentelemetry.io/collector/model@v0.42.0/pdata/generated_log.go:260
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*elasticsearchExporter).pushLogsData(0xc0360db310, {0x4b933a8, 0xc0360bf860}, {0x4b933e0})
                github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.42.0/exporter.go:104 +0x245
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsRequest).export(0x4b933e0, {0x4b933a8, 0xc0360bf860})
                go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/logs.go:67 +0x34
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0xc000b6e090, {0x4bfb5b8, 0xc036509ef0})
                go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/common.go:232 +0x96
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send(0xc000668a20, {0x4bfb5b8, 0xc036509ef0})
                go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/queued_retry.go:147 +0x156
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send(0xc000c92468, {0x4bfb5b8, 0xc036509ef0})
                go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/logs.go:133 +0x88
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).send(0xc000168150, {0x4bfb5b8, 0xc036509ef0})
                go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/queued_retry.go:83 +0x372
go.opentelemetry.io/collector/exporter/exporterhelper.NewLogsExporter.func2({0x4b933e0, 0xc000861b90}, {0x18})
                go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/logs.go:113 +0xca
go.opentelemetry.io/collector/consumer/consumerhelper.ConsumeLogsFunc.ConsumeLogs(0x2, {0x4b933e0, 0xc000861b90}, {0x73334e0})
                go.opentelemetry.io/collector@v0.42.0/consumer/consumerhelper/logs.go:29 +0x2f
go.opentelemetry.io/collector/service/internal/fanoutconsumer.(*logsConsumer).ConsumeLogs(0xc000981de8, {0x4b933e0, 0xc000861b90}, {0x2})
                go.opentelemetry.io/collector@v0.42.0/service/internal/fanoutconsumer/logs.go:77 +0xcd
go.opentelemetry.io/collector/processor/batchprocessor.(*batchLogs).export(0xc000861b30, {0x4b933e0, 0xc000861b90}, 0xffffffffffffffff)
                go.opentelemetry.io/collector@v0.42.0/processor/batchprocessor/batch_processor.go:331 +0xbd
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).sendItems(0xc000168690, 0xc00042b4d0)
                go.opentelemetry.io/collector@v0.42.0/processor/batchprocessor/batch_processor.go:184 +0x21f
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).startProcessingCycle(0xc000168690)
                go.opentelemetry.io/collector@v0.42.0/processor/batchprocessor/batch_processor.go:145 +0x18a
created by go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).Start
                go.opentelemetry.io/collector@v0.42.0/processor/batchprocessor/batch_processor.go:103 +0x6f
```

**What version did you use?**
Version: 0.42 -> 0.44

**What config did you use?**
Config: (e.g. the yaml config file)
(stripped down version of the config)
```
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch
exporters:
  elasticsearch:
    endpoints:
      - '{excluded}'
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]
```

**Environment**
Container: otel/opentelemetry-collector-contrib (from hub.docker.com)

**Additional context**

**Comment by jpkrohling** [comment]
cc @urso @faec @blakerouse

**Comment by thmshmm** [comment]
i think this could be the problem. The loop var should be j not i from the outer loop.
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/667626c636f4150f0a1010c22473004613652f1e/exporter/elasticsearchexporter/exporter.go#L106
