### ISSUE TITLE
Flakey test: Test_PushMetrics/WAL/staleNaNDoubleGauge_case

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#8360]
As seen here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5484352499?check_suite_focus=true

```
=== CONT  Test_PushMetrics/WAL/staleNaNDoubleGauge_case
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd1fd6c]

goroutine 115 [running]:
github.com/tidwall/wal.(*Log).Read(0x0, 0x1)
	/home/runner/go/pkg/mod/github.com/tidwall/wal@v1.1.7/wal.go:621 +0x6c
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter.(*prweWAL).readPrompbFromWAL(0xc0001274a0, {0x1080f58, 0xc0003f7c00}, 0x0)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter/wal.go:348 +0x1ae
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter.(*prweWAL).continuallyPopWALThenExport(0xc0001274a0, {0x1080f58, 0xc0003f7c00}, 0xf7fc00)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter/wal.go:233 +0x3bf
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter.(*prweWAL).run.func1()
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter/wal.go:176 +0x185
created by github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter.(*prweWAL).run
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter/wal.go:166 +0x3e5
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter	45.234s
```

**Comment by jpkrohling** [comment]
cc @Aneurysm9

**Comment by dmitryax** [comment]
Seen here as well https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5486181565?check_suite_focus=true

**Comment by codeboten** [comment]
I couldn't repro locally, but happened again here https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5487568583?check_suite_focus=true

**Comment by Aneurysm9** [comment]
I was able to repro locally by running the tests in a debugger with `-test.count=100` and a breakpoint looking for `prwe.wal == nil` just before reading from it.  The changes in #8368 to check the stop channel in addition to the context prevented recurrence, but I added an explicit error on a `nil` WAL pointer just to be safe.
