### ISSUE TITLE
Various panics when running filelogreceiver in container

### ISSUE THREAD

**Issue by damemi** [open-telemetry/opentelemetry-collector-contrib#8517]
**Describe the bug**
When trying to run a collector configured to use the filelogreceiver, it fails with varying panics that all seem centered around calls to [`connectNodes()`](https://github.com/open-telemetry/opentelemetry-log-collection/blob/cf3f22b0248816f694a2b6d99ea875ba1b63f6f9/pipeline/directed.go#L124-L143) from https://github.com/open-telemetry/opentelemetry-log-collection.

I know this is still in alpha, so this isn't an urgent bug. I'm just reporting it to bring it to someone's attention or see if I'm missing something obvious :)

**Steps to reproduce**
1. Create a config file `simpleconfig.yaml` (both the config and log are based on the [testdata files for filelogreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/bb36c08bd895df4cc1f1e45ffde51c72aaabcad5/receiver/filelogreceiver/testdata)):
```
receivers:
  filelog:
    include: [ /var/log/test/test.log ]
    start_at: beginning
    operators:
      - type: regex_parser
        regex: '^(?P<time>\d{4}-\d{2}-\d{2}) (?P<sev>[A-Z]*) (?P<msg>.*)$'
        timestamp:
          parse_from: time
          layout: '%Y-%m-%d'
        severity:
          parse_from: sev
    converter:
      max_flush_count: 100
      flush_interval: 100ms
    
processors:
  batch:
    send_batch_max_size: 200
    send_batch_size: 200

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: []
      exporters: [logging]
```

2. Create a log file `simple.log` (both the config and log are based on the [testdata files for filelogreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/bb36c08bd895df4cc1f1e45ffde51c72aaabcad5/receiver/filelogreceiver/testdata))
```
2020-08-25 INFO Something routine
2020-08-25 ERROR Something bad happened!
2020-08-25 DEBUG Some details...
```

3. Build `otelcontribcol` image with `make docker-otelcontribcol`
4. Run `otelcontribcol` image:
```
docker run    --volume $(pwd)/simpleconfig.yaml:/etc/otel/config.yaml    --volume $(pwd)/simple.log:/var/log/test/test.log --rm   otelcontribcol
```

**What did you expect to see?**
Successful run

**What did you see instead?**
Various different panics:
```
$ docker run    --volume $(pwd)/simpleconfig.yaml:/etc/otel/config.yaml    --volume $(pwd)/simple.log:/var/log/test/test.log --rm   otelcontribcol
2022/03/16 18:24:19 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/03/16 18:24:19 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
2022-03-16T18:24:19.227Z	info	builder/exporters_builder.go:255	Exporter was built.	{"kind": "exporter", "name": "logging"}
2022-03-16T18:24:19.228Z	info	builder/pipelines_builder.go:223	Pipeline was built.	{"name": "pipeline", "name": "logs"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2 pc=0x41110a]

goroutine 1 [running]:
reflect.mapiterinit(0x3ee7f40?, 0x3791201?, 0xc000d3e848?)
	runtime/map.go:1373 +0x19
gonum.org/v1/gonum/graph/iterator.(*mapIter).next(0xc00090c950)
	gonum.org/v1/gonum@v0.9.3/graph/iterator/map.go:89 +0x5e
gonum.org/v1/gonum/graph/iterator.(*Nodes).NodeSlice(0xc0009afc80)
	gonum.org/v1/gonum@v0.9.3/graph/iterator/nodes_map.go:69 +0x8b
gonum.org/v1/gonum/graph.NodesOf({0x4f20eb8, 0xc0009afc80})
	gonum.org/v1/gonum@v0.9.3/graph/nodes_edges.go:72 +0xb7
gonum.org/v1/gonum/graph/topo.tarjanSCCstabilized({0x4f2a4a8, 0xc0009e4280}, 0x0)
	gonum.org/v1/gonum@v0.9.3/graph/topo/tarjan.go:97 +0x4c
gonum.org/v1/gonum/graph/topo.TarjanSCC(...)
	gonum.org/v1/gonum@v0.9.3/graph/topo/tarjan.go:93
gonum.org/v1/gonum/graph/topo.Sort({0x4f2a4a8?, 0xc0009e4280?})
	gonum.org/v1/gonum@v0.9.3/graph/topo/tarjan.go:41 +0x25
github.com/open-telemetry/opentelemetry-log-collection/pipeline.connectNodes(0xc0009e4280)
	github.com/open-telemetry/opentelemetry-log-collection@v0.26.0/pipeline/directed.go:134 +0x1ba
github.com/open-telemetry/opentelemetry-log-collection/pipeline.NewDirectedPipeline({0xc0009c8780, 0x3, 0x4})
	github.com/open-telemetry/opentelemetry-log-collection@v0.26.0/pipeline/directed.go:208 +0x15b
github.com/open-telemetry/opentelemetry-log-collection/pipeline.Config.Build({{0x4f34228, 0xc000bd65a0}, {0xc0009e4120, 0x2, 0x2}}, 0x1?)
	github.com/open-telemetry/opentelemetry-log-collection@v0.26.0/pipeline/config.go:83 +0x4c5
github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza.createLogsReceiver.func1({0x0?, 0x0?}, {{0xc00090bbc0, {0x4eedda0, 0xc0005344d0}, {0x4ef8180, 0x75e0450}, 0x0}, {{0x46ebe00, 0xe}, ...}}, ...)
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza@v0.46.0/factory.go:81 +0x57d

... <truncated>
```

```
$ docker run    --volume $(pwd)/simpleconfig.yaml:/etc/otel/config.yaml    --volume $(pwd)/simple.log:/var/log/test/test.log --rm   otelcontribcol
2022/03/16 18:28:50 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/03/16 18:28:50 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
2022-03-16T18:28:50.838Z	info	builder/exporters_builder.go:255	Exporter was built.	{"kind": "exporter", "name": "logging"}
2022-03-16T18:28:50.838Z	info	builder/pipelines_builder.go:223	Pipeline was built.	{"name": "pipeline", "name": "logs"}
fatal error: concurrent map iteration and map write

goroutine 1 [running]:
runtime.throw({0x475b8e6?, 0x400014f?})
	runtime/panic.go:998 +0x71 fp=0xc000c3e730 sp=0xc000c3e700 pc=0x43a311
runtime.mapiternext(0xc000c3e7c8?)
	runtime/map.go:871 +0x4eb fp=0xc000c3e7a0 sp=0xc000c3e730 pc=0x41146b
reflect.mapiternext(0x3ee7f40?)
	runtime/map.go:1378 +0x19 fp=0xc000c3e7b8 sp=0xc000c3e7a0 pc=0x467119
gonum.org/v1/gonum/graph/iterator.(*mapIter).next(0xc000d3f920)
	gonum.org/v1/gonum@v0.9.3/graph/iterator/map.go:94 +0x45 fp=0xc000c3e7d8 sp=0xc000c3e7b8 pc=0x2b887c5
gonum.org/v1/gonum/graph/iterator.(*Nodes).NodeSlice(0xc000d44fc0)
	gonum.org/v1/gonum@v0.9.3/graph/iterator/nodes_map.go:69 +0x8b fp=0xc000c3e858 sp=0xc000c3e7d8 pc=0x2b88a6b
gonum.org/v1/gonum/graph.NodesOf({0x4f20eb8, 0xc000d44fc0})
	gonum.org/v1/gonum@v0.9.3/graph/nodes_edges.go:72 +0xb7 fp=0xc000c3e8d8 sp=0xc000c3e858 pc=0x2b850b7
gonum.org/v1/gonum/graph/topo.tarjanSCCstabilized({0x4f2a4a8, 0xc000d3b5c0}, 0x0)
	gonum.org/v1/gonum@v0.9.3/graph/topo/tarjan.go:97 +0x4c fp=0xc000c3e9a0 sp=0xc000c3e8d8 pc=0x2cdc90c
gonum.org/v1/gonum/graph/topo.TarjanSCC(...)
	gonum.org/v1/gonum@v0.9.3/graph/topo/tarjan.go:93
gonum.org/v1/gonum/graph/topo.Sort({0x4f2a4a8?, 0xc000d3b5c0?})
	gonum.org/v1/gonum@v0.9.3/graph/topo/tarjan.go:41 +0x25 fp=0xc000c3e9d0 sp=0xc000c3e9a0 pc=0x2cdc2c5
github.com/open-telemetry/opentelemetry-log-collection/pipeline.connectNodes(0xc000d3b5c0)
	github.com/open-telemetry/opentelemetry-log-collection@v0.26.0/pipeline/directed.go:134 +0x1ba fp=0xc000c3eac0 sp=0xc000c3e9d0 pc=0x2cdf01a
github.com/open-telemetry/opentelemetry-log-collection/pipeline.NewDirectedPipeline({0xc000d27fc0, 0x3, 0x4})
	github.com/open-telemetry/opentelemetry-log-collection@v0.26.0/pipeline/directed.go:208 +0x15b fp=0xc000c3eb28 sp=0xc000c3eac0 pc=0x2cdffbb
github.com/open-telemetry/opentelemetry-log-collection/pipeline.Config.Build({{0x4f34228, 0xc0006e9cb0}, {0xc000d3b460, 0x2, 0x2}}, 0x1?)
```

```
$ docker run    --volume $(pwd)/simpleconfig.yaml:/etc/otel/config.yaml    --volume $(pwd)/simple.log:/var/log/test/test.log --rm   otelcontribcol
2022/03/16 18:34:55 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/03/16 18:34:55 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
2022-03-16T18:34:55.184Z	info	builder/exporters_builder.go:255	Exporter was built.	{"kind": "exporter", "name": "logging"}
2022-03-16T18:34:55.184Z	info	builder/pipelines_builder.go:223	Pipeline was built.	{"name": "pipeline", "name": "logs"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3e pc=0x40bf6b]

goroutine 1 [running]:
github.com/open-telemetry/opentelemetry-log-collection/pipeline.connectNodes(0xc0000e6440)
	github.com/open-telemetry/opentelemetry-log-collection@v0.26.0/pipeline/directed.go:128 +0x3c6
github.com/open-telemetry/opentelemetry-log-collection/pipeline.NewDirectedPipeline({0xc000b5ad80, 0x3, 0x4})
	github.com/open-telemetry/opentelemetry-log-collection@v0.26.0/pipeline/directed.go:208 +0x15b
github.com/open-telemetry/opentelemetry-log-collection/pipeline.Config.Build({{0x4f34228, 0xc000bc6510}, {0xc000c99560, 0x2, 0x2}}, 0x1?)
	github.com/open-telemetry/opentelemetry-log-collection@v0.26.0/pipeline/config.go:83 +0x4c5
github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza.createLogsReceiver.func1({0x0?, 0x0?}, {{0xc000628ba0, {0x4eedda0, 0xc000b910a0}, {0x4ef8180, 0x75e0450}, 0x0}, {{0x46ebe00, 0xe}, ...}}, ...)
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/stanza@v0.46.0/factory.go:81 +0x57d
```

**What version did you use?**
Latest built from `main`

**What config did you use?**
Config: (see above)

**Environment**
Linux/Docker

**Additional context**
When I tried enough times, sometimes it *does* actually run, but does not seem to be processing any of the logs from the file (which I assumed the `start_at: beginning` field would do):
```
$ docker run    --volume $(pwd)/simpleconfig.yaml:/etc/otel/config.yaml    --volume $(pwd)/simple.log:/var/log/test/test.log --rm   otelcontribcol
2022/03/16 18:36:31 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/03/16 18:36:31 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
2022-03-16T18:36:31.370Z	info	builder/exporters_builder.go:255	Exporter was built.	{"kind": "exporter", "name": "logging"}
2022-03-16T18:36:31.370Z	info	builder/pipelines_builder.go:223	Pipeline was built.	{"name": "pipeline", "name": "logs"}
2022-03-16T18:36:31.370Z	info	builder/receivers_builder.go:226	Receiver was built.	{"kind": "receiver", "name": "filelog", "datatype": "logs"}
2022-03-16T18:36:31.370Z	info	service/service.go:82	Starting extensions...
2022-03-16T18:36:31.370Z	info	service/service.go:87	Starting exporters...
2022-03-16T18:36:31.370Z	info	builder/exporters_builder.go:40	Exporter is starting...	{"kind": "exporter", "name": "logging"}
2022-03-16T18:36:31.370Z	info	builder/exporters_builder.go:48	Exporter started.	{"kind": "exporter", "name": "logging"}
2022-03-16T18:36:31.370Z	info	service/service.go:92	Starting processors...
2022-03-16T18:36:31.370Z	info	builder/pipelines_builder.go:54	Pipeline is starting...	{"name": "pipeline", "name": "logs"}
2022-03-16T18:36:31.370Z	info	builder/pipelines_builder.go:65	Pipeline is started.	{"name": "pipeline", "name": "logs"}
2022-03-16T18:36:31.370Z	info	service/service.go:97	Starting receivers...
2022-03-16T18:36:31.370Z	info	builder/receivers_builder.go:68	Receiver is starting...	{"kind": "receiver", "name": "filelog"}
2022-03-16T18:36:31.370Z	info	stanza@v0.46.0/receiver.go:53	Starting stanza receiver	{"kind": "receiver", "name": "filelog"}
2022-03-16T18:36:31.371Z	info	builder/receivers_builder.go:73	Receiver started.	{"kind": "receiver", "name": "filelog"}
2022-03-16T18:36:31.371Z	info	service/telemetry.go:109	Setting up own telemetry...
2022-03-16T18:36:31.372Z	info	service/telemetry.go:129	Serving Prometheus metrics	{"address": ":8888", "level": "basic", "service.instance.id": "9f012577-f59b-4966-ab7c-26715a322254", "service.version": "latest"}
2022-03-16T18:36:31.372Z	info	service/collector.go:248	Starting otelcontribcol...	{"Version": "v0.46.0-1-gbb36c08bd", "NumCPU": 16}
2022-03-16T18:36:31.372Z	info	service/collector.go:144	Everything is ready. Begin running and processing data.
```

**Comment by djaglowski** [comment]
Thanks for capturing this. Looking into it.

**Comment by djaglowski** [comment]
I suspect it is due to [this bug](https://github.com/gonum/gonum/issues/1775) in `gonum/graph`, which apparently has appeared in go 1.18. 

Are you using 1.18 by chance?

**Comment by djaglowski** [comment]
The fix appears to have been rolled out in a [release](https://github.com/gonum/gonum/releases/tag/v0.11.0) just hours ago.

**Comment by damemi** [comment]
Update -- works now, thanks again for the quick fix
