### ISSUE TITLE
Flaky test - TestReceiver at k8sclusterreceiver

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#9002]
```
=== RUN   TestReceiver
E0401 09:44:01.929108   56159 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 54 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x23a16e0, 0x3815600})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/runtime/runtime.go:74 +0xe6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0000db898})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/runtime/runtime.go:48 +0xb0
panic({0x23a16e0, 0x3815600})
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/panic.go:1047 +0x266
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0001c4380, 0xc00007e3f0, 0xc0000ba000, 0xc0000dbb00)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:319 +0x127a
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0001c4380, 0xc0000ba000)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:361 +0x2d6
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:221 +0x45
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0000caed8)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:155 +0x82
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00038c380, {0x28f4580, 0xc00004e500}, 0x1, 0xc0000ba000)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:156 +0xcf
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0001c4380, 0xc0000ba000)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:220 +0x296
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:56 +0x3f
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:73 +0x7f
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:71 +0xdf
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference

goroutine 54 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0000db898})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/runtime/runtime.go:55 +0x145
panic({0x23a16e0, 0x3815600})
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/panic.go:1047 +0x266
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0001c4380, 0xc00007e3f0, 0xc0000ba000, 0xc0000dbb00)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:319 +0x127a
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0001c4380, 0xc0000ba000)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:361 +0x2d6
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:221 +0x45
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0000caed8)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:155 +0x82
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00038c380, {0x28f4580, 0xc00004e500}, 0x1, 0xc0000ba000)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:156 +0xcf
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0001c4380, 0xc0000ba000)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:220 +0x296
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:56 +0x3f
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:73 +0x7f
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:71 +0xdf
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sclusterreceiver	0.139s
```

Seen here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5785311188?check_suite_focus=true

cc @dmitryax

**Comment by tigrannajaryan** [comment]
Again https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5994286583?check_suite_focus=true
I think there is no other way, we need to disable it for now.

**Comment by djaglowski** [comment]
Here again: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6038443724?check_suite_focus=true#step:8:16418
